CREATE OR REPLACE PACKAGE BODY PA_ELDECANO IS
  
  FUNCTION CO_TIEMPO RETURN SYS_REFCURSOR IS TIEMPO SYS_REFCURSOR;
  BEGIN 
    TIEMPO := PC_PROFESORES.CO_TIEMPO;
    RETURN TIEMPO;
  END;
  
  FUNCTION CO_TALLERES RETURN SYS_REFCURSOR IS TALLERES SYS_REFCURSOR;
  BEGIN
	TALLERES := PC_TALLERES.CO_TALLERES;
	RETURN TALLERES;
	
  FUNCTION CO_PROFESORES RETURN SYS_REFCURSOR IS PROFESORES SYS_REFCURSOR;
  BEGIN
	PROFESORES := PC_PROFESORES.CO_PROFESORES;
	RETURN PROFESORES;
	
  END;
  
END PA_ELDECANO;

CREATE OR REPLACE PACKAGE BODY PA_PROFESORES IS

  FUNCTION CO_PROFESORES RETURN SYS_REFCURSOR IS PROFESORES SYS_REFCURSOR;
  BEGIN
	PROFESORES := PC_PROFESORES.CO_PROFESORES;
	RETURN PROFESORES;
  END;
  
  FUNCTION CO_RECONOCIMIENTO RETURN XMLTYPE IS CO_RECONOCIMIENTO_XML XMLTYPE;
  BEGIN
	CO_RECONOCIMIENTO_XML := PC_PROFESORES.CO_HOJADEVIDA;
    RETURN CO_RECONOCIMIENTO_XML;
  END;
  
END PA_PROFESORES;
