
CREATE OR REPLACE PACKAGE PA_ELDECANO IS
  FUNCTION CO_TIEMPO RETURN SYS_REFCURSOR;
  FUNCTION CO_TALLERES RETURN SYS_REFCURSOR;
  FUNCTION CO_PROFESORES RETURN SYS_REFCURSOR;
END PA_ELDECANO;

CREATE OR REPLACE PACKAGE PA_PROFESORES IS
  FUNCTION CO_PROFESORES RETURN SYS_REFCURSOR;
  FUNCTION CO_RECONOCIMIENTO RETURN XMLTYPE;  
END PA_PROFESORES;