CREATE OR REPLACE PACKAGE BODY PC_PROFESORES IS
  PROCEDURE AD_PROFESORES(XNAME IN VARCHAR) IS
  BEGIN
    INSERT INTO staff(name) VALUES (XNAME);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
         RAISE_APPLICATION_ERROR(-20012,'gola');
    END;
    
  PROCEDURE EL_PROFESORES(XID IN VARCHAR) IS
  BEGIN
      DELETE FROM staff WHERE id = XID;
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
        RAISE_APPLICATION_ERROR(-20150,'gola');
    END;
    
  PROCEDURE MO_PROFESORES (XID IN VARCHAR,XNAME IN VARCHAR) IS
  BEGIN
    UPDATE staff SET name = XNAME WHERE id = XID;
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
        RAISE_APPLICATION_ERROR(-20103,'Error al modificar en staff');
    END;
  FUNCTION CO_PROFESORES(PROID IN VARCHAR) RETURN SYS_REFCURSOR IS CON SYS_REFCURSOR;
  BEGIN
    OPEN CON FOR
      SELECT *
      FROM staff
      WHERE id = PROID;
    RETURN CON;
  END;
  
  FUNCTION CO_HOJAVIDA RETURN XMLTYPE IS CO_XML XMLTYPE;
  BEGIN
    CO_XML := dbms_xmlgen.getxmltype(
      'SELECT * FROM STAFF');
    RETURN CO_XML;
  END;
END PC_PROFESORES;
/

CREATE OR REPLACE PACKAGE BODY PC_TALLERES IS
    PROCEDURE AD_TALLERES(xmodle IN VARCHAR,xkind IN CHAR,xdow IN VARCHAR,xtod IN VARCHAR,xduration IN NUMBER,xroom IN VARCHAR) IS
  BEGIN
    INSERT INTO event(modle,kind,dow,tod,duration,room) VALUES (xmodle,xkind,xdow,xtod,xduration,xroom);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE_APPLICATION_ERROR(-20012,SQLERRM);
    END AD_TALLERES;
    FUNCTION CO_TALLERES(tallid VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
    BEGIN
        OPEN CONSULTA FOR
        SELECT dow,tod 
        FROM event
        WHERE id = tallid;
        RETURN CONSULTA;
    END;
END PC_TALLERES;






/

