CREATE OR REPLACE PACKAGE BODY PC_PROFESORES IS
  PROCEDURE AD_PROFESORES(XNAME IN VARCHAR) IS
  BEGIN
    INSERT INTO staff(name) VALUES (XNAME);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE_APPLICATION_ERROR(-20012,SQLERRM);
    END AD_PROFESORES;
    
  PROCEDURE EL_PROFESORES IS
  BEGIN
      DELETE FROM staff;
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE_APPLICATION_ERROR(-20150,SQLERRM);
    END EL_PROFESORES;
    
  PROCEDURE MO_PROFESORES (XNAME IN VARCHAR) IS
  BEGIN
    UPDATE staff SET id = XNAME;
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE_APPLIACTION_ERROR(-20010,SQLERRM);
    END MO_PROFESORES;
    
  FUNCTION CO_PROFESORES(PROID VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
  BEGIN
    OPEN CONSULTA FOR
      SELECT *
      FROM staff
      WHERE id = PROID;
      RETURN CONSULTA;
  END;
END PC_PROFESORES;
/

CREATE OR REPLACE PACKAGE BODY PC_TALLERES IS
    PROCEDURE AD_TALLERES(xmodle IN VARCHAR,xkind IN CHAR,xdow IN VARCHAR,xtod IN VARCHAR,xduration IN NUMBER,xroom IN VARCHAR) IS
  BEGIN
    INSERT INTO event(modle,kind,dow,tod,duration,room) VALUES (xmodle,xkind,xdow,xtod,xduration,xroom);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE_APPLICATION_ERROR(-20012,SQLERRM);
    END AD_TALLERES;
    FUNCTION CO_TALLERES(tallid VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
    BEGIN
        OPEN CONSULTA FOR
        SELECT dow,tod 
        FROM event
        WHERE id = tallid;
        RETURN CONSULTA;
    END;
END PC_TALLERES;






/

