CREATE OR REPLACE PACKAGE PC_PROFESORES IS
    PROCEDURE AD_PROFESORES(XNAME IN VARCHAR);
    PROCEDURE EL_PROFESORES;
    PROCEDURE MO_PROFESORES(XNAME IN VARCHAR);
    FUNCTION CO_PROFESORES RETURN SYS_REFCURSOR;
    FUNCTION CO_RECONOCIMIETOS RETURN XMLTYPE;
END PC_PROFESORES;
/
CREATE OR REPLACE PACKAGE PC_TALLERES IS
    PROCEDURE AD_TALLERES(xmodle IN VARCHAR,xkind IN CHAR,xdow IN VARCHAR,xtod IN VARCHAR,xduration IN NUMBER,xroom IN VARCHAR);
    FUNCTION CO_TALLERES(tallid IN VARCHAR) RETURN SYS_REFCURSOR;
END PC_TALLERES;
/
