CREATE OR REPLACE PACKAGE PC_PROFESORES IS
    PROCEDURE AD_PROFESOR(NAME IN VARCHAR);
    PROCEDURE EL_PROFESOR;
    PROCEDURE MO_PROFESOR(NAME IN VARCHAR);
    FUNCTION CO_PROFESOR RETURN SYS_REFCURSOR;
END PC_PROFESORES;

CREATE OR REPLACE PACKAGE PC_TALLERES IS
    PROCEDURE AD_TALLERES(NAME IN VARCHAR);
END PC_TALLERES;