INSERT INTO animes (nombre,genero) VALUES ('your name.' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Fullmetal Alchemist: Brotherhood' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Steins;Gate' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Clannad After Story' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Rurouni Kenshin: Trust y Betrayal' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Code Geass: Lelouch of the Rebellion R' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Spirited Away' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('A Silent Voice' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Cowboy Bebop' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Mushishi: The Next Chapter' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('(The) Disappearance of Haruhi Suzumiya' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Princess Mononoke' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('(The) Legend of the Galactic Heroes' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Mushi-Shi' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Death Note' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Maria Watches Over Us rd Season' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Made in Abyss' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Maria Watches Over Us Season : Printemps' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Code Geass: Lelouch of the Rebellion' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Gintama' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('anohana: The Flower We Saw That Day' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Descending Stories: Showa Genroku Rakugo Shinju' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Maria Watches Over Us th Season' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Gintama' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Gintama (movie)' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Bunny Drop' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Evangelion: . You Can (Not) Advance' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Monster' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Grave of the Fireflies' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Cross Game' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Stand Alone Complex nd GIG' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Summer Wars' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Fighting Spirit' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Fullmetal Alchemist' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Hunter × Hunter' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Nodame Cantabile' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('(The) Girl Who Leapt Through Time' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Centimeters Per Second' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Nausicaä of the Valley of the Wind' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Gurren Lagann' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('(The) Garden of Sinners' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Wolf Children' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('My Neighbor Totoro' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Baccano!' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Honey and Clover II' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Natsumes Book of Friends' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Gintama: The Final Movie' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Hajime no Ippo: New Challenger' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Kanon' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Star Blazers' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('GTO: Great Teacher Onizuka' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Kinos Journey' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Howls Moving Castle' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Time of Eve' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Puella Magi Madoka Magica' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Mushishi Tokubetsu-hen: Hihamukage' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Natsumes Book of Friends' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Millennium Actress' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Time of Eve' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Monogatari Series Second Season' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Kaleido Star' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Mononoke' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Kids on the Slope' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Natsumes Book of Friends' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('(The) Melancholy of Haruhi Suzumiya' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Gankutsuou: The Count of Monte Cristo' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Clannad' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Planetes' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('NANA' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Looking Up At The Half-Moon' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Castle in the Sky' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Your Lie in April' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Whisper of the Heart' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Samurai Champloo' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Ouran High School Host Club' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('A Place Further Than the Universe' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Gurren Lagann the Movie – The Lights in the Sky Are Stars' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('(The) Beast Player Erin' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Stand Alone Complex' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Maria Watches Over Us' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Aria the Origination' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Spice and Wolf II' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Angel Beats!' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Moribito - Guardian of the Spirit' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('March comes in like a lion' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Haikyu!! Second Season' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('My Hero Academia' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('ef: a tale of melodies' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('ef: a tale of memories' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Haikyu!!' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Black Lagoon: The Second Barrage' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Welcome to the NHK' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Re:ZERO -Starting Life in Another World-' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Legend of the Galactic Heroes: Overture to a New War' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Mushishi: Zoku-Sh?: Suzu no Shizuku' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('(The) Tale of the Princess Kaguya' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Honey and Clover' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Sword of the Stranger' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Haibane Renmei' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Sh?wa Genroku Rakugo Shinj?' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('(The) Twelve Kingdoms' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Hunter X Hunter' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('My Hero Academia' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Cowboy Bebop: The Movie' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Tokyo Godfathers' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Toradora!' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Romeo × Juliet' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Owarimonogatari' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Maison Ikkoku' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Major' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Evangelion: . You Are (Not) Alone' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Shirobako' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Hellsing Ultimate' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Chihayafuru' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Tsubasa Toyo Revelations' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Katanagatari' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam UC' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('(The) Garden of Words' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Full Metal Panic! The Second Raid' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Gintama.' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Hunter X Hunter' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Fate/Zero' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('ERASED' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('BECK: Mongolian Chop Squad' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Kimi ni Todoke - From Me to You' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('(La) Maison en Petits Cubes' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Den-noh Coil' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Bakuman' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('One Piece Episode of Nami: K?kaishi no Namida to Nakama no Kizuna' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Natsumes Book of Friends' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Attack on Titan' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('JoJos Bizarre Adventure: Diamond Is Unbreakable' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Nodame Cantabile: Paris' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Lupin the Third: Part' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Berserk' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Brave King GaoGaiGar Final' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Kaiba' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Ping Pong' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Princess Tutu' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Conan, the Boy in Future' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Hotarubi no Mori e' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Azumanga Daioh' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Full Metal Panic? Fumoffu' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Nodame Cantabile: Finale' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Eden of the East' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('(The) Rose of Versailles' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Mushishi Zoku-Sh? Tokubetsu-hen: Odoro no Michi' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('unter X Hunter: G I Final' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Haikyu!!' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Yuri!!! on Ice' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Girls und Panzer der Film' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Natsume Y?jin-Ch? Roku' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Mob Psycho' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Assassination Classroom' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Kimi ni Todoke nd Season' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Maquia - When the Promised Flower Blooms' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Hanasaku Iroha - Blossoms for Tomorrow' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Trigun' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Stand Alone Complex: Solid State Society' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Paprika' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Spice and Wolf' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Magnetic Rose' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('School Rumble: nd Semester' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('R.O.D -The TV-' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Violet Evergarden' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Ashita no Joe' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Sound! Euphonium' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Berserk: The Golden Age Arc III - The Advent' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('(The) Eccentric Family' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Gungrave' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Last Exile' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Bakuman.' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Rurouni Kenshin' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Legend of the Galactic Heroes: My Conquest is the Sea of Stars' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Comedy' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Land of the Lustrous' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('When Marnie Was There' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Skip Beat!' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Natsume Y?jin-Ch? Go' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('In This Corner of the World' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('xxxHOLiC: Kei' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Attack on Titan' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Neon Genesis Evangelion: The End of Evangelion' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Bakemonogatari' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('(The) Super Dimension Fortress Macross: Do You Remember Love?' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Master Keaton' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Kikis Delivery Service' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Hunter X Hunter: Greed Island' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Romeo and the Black Brothers' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Hajime no Ippo - Champion Road' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('(The) Super Dimension Fortress Macross' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Gintama' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('One Outs' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Tiger y Bunny' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Black Lagoon' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Neon Genesis Evangelion' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Fate/stay night: Unlimited Blade Works' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Stand Alone Complex - Individual Eleven' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('(The) Boy and The Beast' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('(The) Anthem of the Heart' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Fate/Zero' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Food Wars! Shokugeki no Soma' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam  Second Season' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Macross Frontier' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Darker than Black' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Nichijou - My Ordinary Life' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Space Brothers' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Gosick' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('No Game, No Life Zero' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('One Punch Man' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Lupin III: The Castle of Cagliostro' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Aria the Avvenire' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Welcome to THE SPACE SHOW' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Denpa teki na Kanojo' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Monthly Girls Nozaki-kun' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Nobodys Boy Remi' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Elfen Lied' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Emma: A Victorian Romance Second Act' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Kizumonogatari Part : Reiketsu' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('My Hero Academia' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Rainbow - Nisha Rokub? no Shichinin' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Wolfs Rain' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('No Game, No Life' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Stand Alone Complex - The Laughing Man' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Magical Girl Lyrical Nanoha the Movie nd As' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Junj? Romantica' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Tokyo Magnitude .' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Eureka Seven' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('School Rumble' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Parasyte -the maxim-' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Hinamatsuri' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Kizumonogatari Part : Nekketsu (movie)' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Kill la Kill' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell (movie)' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Puella Magi Madoka Magica the Movie Part : Eternal' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Now and Then, Here and There' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Berserk: The Golden Age Arc II - The Battle for Doldrey (movie)' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Puella Magi Madoka Magica the Movie Part : Beginnings' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Kizumonogatari Part : Tekketsu (movie)' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Wagnaria!!' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Kimagure Orange Road: The Movie' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Lovely Complex' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Porco Rosso (movie)' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('(The) Place Promised in Our Early Days (movie)' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Hikaru No Go: New Year Special' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('planetarian: Hoshi no Hito (movie)' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam - The Movie Trilogy' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Hajime no Ippo - Mashiba vs. Kimura' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Puella Magi Madoka Magica The Movie Part : Rebellion' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Cardcaptor Sakura Movie : The Sealed Card' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('(The) Wind Rises (movie)' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Legend of the Galactic Heroes: A Hundred Billion Stars, A Hundred Billion Lights' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Detroit Metal City' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('(The) Slayers Next' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('One Piece Film Strong World (movie )' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Strawberry Panic!' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('KenIchi the Mightiest Disciple' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Princess Jellyfish' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Bamboo Blade' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Initial D: Fourth Stage' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Owarimonogatari' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Bakuman.' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Silver Spoon' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Hikaru no Go' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('ReLIFE' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Hajime no Ippo Rising' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Banner of the Stars II' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Higurashi no Naku Koroni Kai' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Gunbuster' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('ReLIFE' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Food Wars! The Second Plate' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed: The Phantom of Baker Street (movie)' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Samurai' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Voices of a Distant Star' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('lam Dunk' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Doraemon the Movie: Nobita and the Steel Troops: The New Age' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('(The) Ancient Magus Bride' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Full Moon o Sagashite' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Miss Kobayashis Dragon Maid' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('A Lull in the Sea' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Zeta Gundam' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Psycho-Pass' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Sayonara, Zetsubou-Sensei' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('(The) Story of Saiunkoku Second Series' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('FLCL' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Treasure Island' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed: Captured in Her Eyes (movie)' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed: The Last Magician of the Century (movie)' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('(The) Secret World of Arrietty (movie)' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Genshiken' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Touch (TV)' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Kyo kara Maoh! rd Series' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Black Lagoon: Robertas Blood Trail' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Log Horizon' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Genshiken' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Big Windup! Season' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed: Countdown to Heaven (movie)' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Kaleido Star: Legend of Phoenix - Layla Hamilton Story' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Saint Seiya: The Hades Chapter - Sanctuary' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Junj? Romantica' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Aria - The Natural' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Claymore' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Zoku Sayonara Zetsub? Sensei' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Giant Robo' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Legend of the Galactic Heroes: Spiral Labyrinth' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Nisemonogatari' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Ace of Diamond: Second Season' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('(The) Garden of Sinners/recalled out summer (movie)' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Non Non Biyori Repeat' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Fruits Basket' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('From Up On Poppy Hill (movie)' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Perfect Blue (movie)' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('When They Cry - Higurashi' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Kimagure Orange Road' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Birdy the Mighty Decode:' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Penguindrum' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Soul Eater' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Full Metal Panic!' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Hanada Sh?nen-shi' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Hare+Guu Deluxe' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Baby Blue (movie)' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('xxxHOLiC: R?' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Emma: A Victorian Romance' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Macross Zero' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Space Battleship Yamato' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Fairy Tail Zero' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam: The Origin' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('One Piece DY Ace no Shi wo Koete! Luffy Nakama to no Chikai' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Chihayafuru' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('(The) Tatami Galaxy' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Tamayura: Sotsugy? Shashin (movie series)' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('(The) Vision of Escaflowne' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam: Iron-Blooded Orphans' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Magical Girl Lyrical Nanoha As' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Black Butler: Book of Murder' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('(The) Eccentric Family (TV)' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Read or Die' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Durarara!!' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Broken Blade (movie series)' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Yu Yu Hakusho: Ghost Files' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Fate/stay night: Unlimited Blade Works' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Ga-Rei-Zero' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Macross Plus Movie Edition' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Kaiji' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Gintama Season' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Tsubasa: Spring Thunder' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('(The) Story of Saiunkoku' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Crest of the Stars' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('On Your Mark (movie)' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Urusei Yatsura: Beautiful Dreamer (movie)' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Gintama' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Hanamonogatari' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('KONOSUBA - Gods blessing on this wonderful world!' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Toward the Terra' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Mind Game (movie)' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Genshiken' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam Seed' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Goku Sayonara Zetsub? Sensei' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Daicon films (special)' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('One Piece Film Z (movie)' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Baby Steps' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('City Hunter' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Redline (movie)' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Big Windup!' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Saga of Tanya the Evil' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Initial D: Second Stage' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('K-ON! (movie)' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('InuYasha: The Final Act' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Jormungand Perfect Order' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('(The) Dog of Flanders (movie)' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Mah? Sensei Negima!: M? Hitotsu no Sekai (OAV)' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Gintama: The Movie' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('(The) Disastrous Life of Saiki K.' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Lunar Legend Tsukihime' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Zan Sayonara Zetsub? Sensei' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Rurouni Kenshin: Reflection' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Hanasaku Iroha: Home Sweet Home (movie)' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Aggressive Retsuko' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Fate/stay night: Heavens Feel I. presage flower (movie)' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Kurenai' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Steins;Gate: The Movie - Load Region of Dejà Vu' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Kyousougiga' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Girls Last Tour' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Barakamon' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('(The) Irresponsible Captain Tylor' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Death Parade' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Detective Conan: The Lost Ship in The Sky (movie )' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Patema Inverted (movie)' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Banner of the Stars' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Yona of the Dawn' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Revolutionary Girl Utena' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Hidamari Sketch × Honeycomb' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Wagnaria!!' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Barefoot Gen (movie)' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Children Who Chase Lost Voices' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed: The Fourteenth Target' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell S.A.C. Solid State Society D' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('My-HiME' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Natsume Y?jin-Ch?: Itsuka Yuki no Hi ni' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Sound! Euphonium' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Hozukis Coolheadedness' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('One Piece' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Shigofumi - Letters from the Departed' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Trigun: Badlands Rumble' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Hidamari Sketch × Hoshimittsu' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('INTERSTELLA : The tory of the ecret tar ystem' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Silver Spoon' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Lucky Star' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Tsukimonogatari' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('RahXephon' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('My Teen Romantic Comedy SNAFU TOO!' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Laid-Back Camp' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Gurren Lagann the Movie –Childhoods End-' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Tsukigakirei' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('His and Her Circumstances' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('(The) Seven Deadly Sins: Revival of The Commandments' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Vampire Hunter D: Bloodlust' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Kobato.' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Berserk: The Golden Age Arc I - The Egg of the King' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Doukyusei -Classmates-' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('House of Five Leaves' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('School Rumble: Extra Class' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Nekomonogatari' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Glass Mask' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('(The) Ancient Magus Bride: Those Awaiting a Star' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('My Love Story!!' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Ergo Proxy' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Arise' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Tenchi Muyo! Ryo-Ohki' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Love, Chunibyo y Other Delusions!' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Strawberry Marshmallow' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Initial D: Third Stage (movie)' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Master Keaton' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Banner of the Stars III' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Attack on Titan: No Regrets' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Final Fantasy VII: Advent Children' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Attack on Titan' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Fullmetal Alchemist: The Movie - Conqueror of Shamballa' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Macross Plus' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Hayate the Combat Butler!!' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Daily Lives of High School Boys' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Hy?ka' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Hidamari Sketch: Sae/Hiro Sotsugy?-hen' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Tekkonkinkreet' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Initial D: Final Stage' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Food Wars! The Third Plate' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Tari Tari' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Detective Conan: The Private Eyes Requiem' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Moshidora' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Shakugan no Shana' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('A Letter to Momo' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Rage of Bahamut: Genesis' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Little Witch Academia' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('(The) Cat Returns' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('xxxHOLiC: Shunmuki' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('xxxHOLiC: R? Adayume' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Kinos Travels: Life Goes On' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam: The th MS Team' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Heartcatch Precure! Hana no Miyako de Fashion Show…Desu ka!?' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Sword Art Online the Movie: Ordinal Scale' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('JoJos Bizarre Adventure: Stardust Crusaders Egypt Arc' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Kamichu!' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Hidamari Sketch × Hoshimittsu' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('GATE' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Noein - to your other self' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Seto no Hanayome' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('H?zuki no Reitetsu' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Scrapped Princess' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Ushio y Tora' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Shonen Onmyouji' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Food Wars! The Third Plate' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Zan Sayonara Zetsub? Sensei Bangai-chi' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Tiger y Bunny The Movie -The Rising-' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('White Album' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Full Metal Panic! The Second Raid' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Tenchi Muyo! War on Geminar' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Hidamari Sketch ×' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Queen Millennia' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Megalobox' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Gunslinger Girl' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('(The) Disastrous Life of Saiki K.' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Inuyashiki Last Hero' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Colorful' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Detective Conan: The Raven Chaser' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Another' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Giovannis Island' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Planetarian' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Full Metal Panic! Invisible Victory' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Akira' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Blood+' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Waiting in the Summer' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Strawberry Marshmallow' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Fullmetal Alchemist: Brotherhood' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed The Movie: The Time Bombed Skyscraper' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Hi Score Girl' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('From the New World' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Aria the Animation' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Detective Conan: Magician of the Silver Sky' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Macross Frontier: Itsuwari no Utahime' , 'Gore');

INSERT INTO animes(nombre,genero) VALUES ('3D Kanojo' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('12-Sai: Chicchana Mune no Tokimeki' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('12-Sai: Chicchana Mune no Tokimeki 2nd Season' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('18if' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('91 Days' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('25-Sai no Joshikousei' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Absolute Duo' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Acca: 13 ku Kansatsu-ka' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Active Raid' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Action Herione Cheer Fruits' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Aho Girl' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Ai Mai Mi: Surgical Friends' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Ajin 2nd Season' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Akagami no Shirayuki Hime' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Akagami no Shirayuki Hime 2nd Season' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Akame ga Kill!' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Akanesasu Shoujo' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Akibas Trip The Animation' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Aki no Kanade' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Akkun to Kanojo' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Aldnoah.Zero' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Aldnoah.Zero S2' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Alice to Zouroku' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Alice or Alice' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Amaama to Inazuma' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Amanchu!' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Amanchu! Advance S2' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Angolmois: Genkou Kassenki' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Anime Gataris' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Anne Happy' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Anitore EX' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Anitore! XX' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Another' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Ame iro Cocoa Rainy color e Youkoso' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Ame-iro Cocoa in Hawaii' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Amai Choubatsu: Watashi wa Kanshu Senyou Pet' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Angel Beats! OVA 2 2015' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Ange Vierge' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Aoharu x kikanjuu' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Aooni The Blue Monster' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Ao no Exorcist: Kyoto Fujouou-Hen' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Aquarion Logos' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Arslan Senki' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Arslan Senki (TV) Fuujin Ranbu' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Asobi Asobase' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('B-Project: Kodou Ambitous' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Back Street Girls' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Bakuon!!' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Bang Dream!' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Bang Dream! Girls Band Party! Pico' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Ballroom e Youkoso' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Banana Fish' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Basilisk: Ouka Ninpouchou' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Battle Girl High School Battle Girl Project' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Beatles' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Bernard-Jou Iwaku' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Berserk (2016)' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Berserk (2017)' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Bikini Warrios' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Bishoujo Yuugi Unit Crane Game Girls' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Bishoujo Yuugi Unit Crane Game Girls Galaxy' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Black Clover' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Blend S' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Bloodivores' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Boku Dake ga Inai Machi' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Boku no Hero Academia' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Boku no Hero Academia 2nd Season 2017' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Boku no Hero Academia Season 3' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Boku no Kanojo ga Majime Sugiru Shoujo Bitch na Ken' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Boruto: Naruto The Movie' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Boruto: Naruto Next Generations' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Brave Witches' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Bubuki Buranki' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Bubuki Buranki: Hoshi no Kyojin' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Bungou Stray Dogs' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Bungou Stray Dogs 2nd Season' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Busou Shoujo Machiavllianism' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Caligula' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Capitan Tsubasa 2018' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Cardcaptor Sakura: Clear Card-Hen' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Centaur no Nayami' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Chaos;Child' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Chaos Dragon Sekiryuu Seneki' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Charlotte' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Cheer Danshi!!' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Cheating Craft' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Chio.chan no Tsuugakuro' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Chiruran Nibun no Ichi' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Cinderella Girls Gekijou' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Cinderella Girls Gekijou Segunda Temporada' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Cinderella Girls Gekijou Tercera Temporada' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Citrus' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Classroom Crisis' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Clione no Akari' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('ClockWork Planet' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Code: Realize - Sousei no Himegimi' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Comet Lucifer' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Comic girs' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Concrete Revolution Choujin Gensou' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Concrete Revolution Choujin Gensou - The Last Song' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Cross Ange: Tenshi to Ryuu no Rondo' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('D. Gray-Man Hallow' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Dagashi Kashi' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Dagashi Kashi 2' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Dance with Devils' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Danna ga Nani wo Itteiru ka Wakaranai Ken 2 Suru-Me' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Danganronpa 3: The End Of Kibougamine Gakuen - Mirai-Hen' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Danganronpa 3: The End Of Kibougamine Gakuen - Zetsubou-Hen' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('DanMachi: Sword Oratoria' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Darling in The Franxx' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Days' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Dragon Ball Z:Fukatsu no F' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Dragon Ball Super' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Deadman Wonderlan' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Deatg March Kara Hajimaru Isekai Kyousoukyoku' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Demi-chan wa Kataritai' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Denpa Kyoushi' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Devil Line' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Diamon no Ace S2' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Dies Irae' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Dive!!' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Divine Gate' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Dynamic Chord' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('DOUBLE DECKER! Doug y Kirill' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Dog Days' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Dog Days 2nd Season' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Dog Days 3S' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Dorei-ku The Animation' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Drifters' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Dungeon ni Deai wo Motomeru no Wa Machigatte iru Darou ka' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Durarara!!' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Durarara!! x2 Shou' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Durarara!! x2 Ten' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Durarara!! x2 Ketsu' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Ebiten: Kouritsu Ebisugawa Koukou Tenmonbu' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Emiya-san Chi no Kyou Gohan' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Enmusubi no Youko-chan' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Etotama!' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Eldlive' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Endride' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('EroManga-Sensei - Recomendado' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('FLCL Progressive' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Alternativa FLCL' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Fairy Tail (2014)' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Fairy Tail (2018)' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Flip Flappers' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('FOOD WARS: SHOKUGEKI NO SOMA' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Fate/Apocrypha' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Fate/Gran Order Moonlight/Lostroom' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Fate/Extra Last Encore' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Fate/stay night' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Fate/stay night: Unlimited Blade Works' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Fate/Stay Night: Unlimited Works 2' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Fate/Kaleid Liner Prisma Illya 2wei Herz!' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Fate/Kaleid Liner Prisma Illya 3Rei!!' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Fate Zero Temporadas 1 y 2' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Flying Witch' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Frame Arms Girl' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Free! Dive to the Future' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Fukigen na Mononokean' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Fukumenkei Noise' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Fudanshi Koukou seikatsu' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Full Metal Panic! Invisible Victory' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Fushigi na Somera-chan' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Fuuka' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Gabriel DropOut' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Gate jieitai Nite Kaku' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Gakkou Gurashi' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Gakusen Toshi Asterisk' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Gakusen Toshi Asterisk 2nd Season' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Gakuen Babysitters' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Gamers!' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Gangsta' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Garo Guren no Tsuki' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Garo -Vanishing Line-' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Gatchaman Crowds Insight' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('GATE: JIEITAI KANOCHI NITE' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES (' KAKU TATAKAERI - ENRYUU-HEN' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Gegege no Kitarou (2018)' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Getsuyoubi no Tawawa' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Gin no Guardian' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Gin no Guardian 2' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Ginga Eiyuu Densetsu -Die Neue These- Kaikou' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Gintama 2017' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Gintama 2015 - Cuarta Temporada' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Gintama Shinyaku Benizakura-hen Special' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Gintama 2015 OVA' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Gintama (Shinsaku)' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Girls und Panzer + Akiyama Yukari s Tank Corner' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Girlish Number' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Gyakuten Siaban: Sono Shinjitsu' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES (' Igi Ari!' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Ghots in The Shell: Arise - Alternative' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Goblin Slayer' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Gochuumon wa usagi desu ka S2' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Golden Kamuy' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Golden Kamuy 2' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Grand Blue' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('GrandBlue Fantasy' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Grancrest Senki' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Grisaia no Kajitsu Especiales' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Grisaia no Mekyuu' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Grisaia no Rakuen' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Gunslinger Stratos' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Hacka Doll The Animation' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('HaiFuri' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Hagure Yuusha no Estetica' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Hajimete no Gal' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Haikyuu Second Season' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Haikyuu!! Third Season' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Haiyore Nyaruko-san F OVA' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Hakata Tonkotsu Ramens' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Hakumei to Mikochi' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Handa-kun' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Hanebado' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Happy sugar life' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Haruchika Haruta to Chika Wa Seishun' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Harukana Receive' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Hand Shakers' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Hataraku Saibou' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Hatsukoi Monster' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Hellsing' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Hello Kiniro-Mosaic' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Heavy Object' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Hetalia World Twinkle' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Hibike! Euphonium' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Hibike! Euphonium 2' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Hidan no Aria AA' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('High Score Girl' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('High School DxD New' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('High School DxD Born' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('High School DxD Born Especiales' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('High School DxD Hero' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Himouto Umaru-chan R (Segunda Temporada)' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Hinako Note' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Hina Logic: From Luck y Logic' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Hinamatsuri' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Hitori no Shita: the Outcast' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Hitori no Shita: the Outcast 2nd Season' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Hitoijime my Hero' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Hitsugi no Chaika: Avening Battle' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Houkago no Pleiades' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Houseki no Kuni' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Hoozuki no Reitetsu' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Huyao Xiao Hongniang' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Hyakka Ryouran Samurai Girls' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Hyakka Ryouran Samurai Bride S2' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Hyakuren no Haou to Seiyaku no Valkyria' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Isuca' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Idol Jihen' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Idol Memories' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Imouto Sae Ireba Li' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Inazuma Eleven Ares no Tenbin' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Ingress' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Inuyashiki' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Irozuku Sekai no Ashita kara' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Isekai Maou to Shoukan Shoujo no Dorei Majutsu' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Isekai Shokudou' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Isekai wa Smartphone to Tomo ni' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Isekai Izakaya: Koto Aitheria no Izakaya Nobi' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Island' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Ito Junji: Collection' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Itsudatte Bokura no koi wa 10 Cm Datta' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Jigoku Shoujo: Yoi no Togi' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Jikan no Shihaisha' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Jingai-san no Yome' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Jitsu wa Watashi wa' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('JK Meshi' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Joker Game' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Joukamachi no Dandelion' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Jojo no Kimyou na Bouken: Diamond wa Kudakenai' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Jojo no Kimyou na Bouken: Ougon no Kaze' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Jungektsu no Maria' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Just Because!' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Juuou Taisen' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Juuou Mujin no Fafnir' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Juushinki Pandora' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('K: Missing Kings' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('K: Return of Kings' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Kabukibu!' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Kagewani' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Kagewani: Shou' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Kakegurui' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Karakai Jouzu no Takagi-san' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Kakuriyo no Yadomeshi' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Katsugeki/Touken Ranbu' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Kaze ga Tsuyoku Fuiteiru' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Keijo!!!!!!!!' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Kaito Tenshi Twin Angel (TV)' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Kekkai Sensen' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Kekkai Sensen y Beyond' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Kemono Friends' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Keppeki Danshi Aoyama-Kun' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Kiitarou Shounen no Youkai Enikki' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Killing Bites' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Kill la Kill' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Kimi ni Todoke' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Kimi ni Todoke 2nd Season' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Kindaichi Shounen no Jikenbo Returnsn' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Kino no Tabi: Beautiful - The Animated Series' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Knights y Magic' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Kishuku Gakkou no Juliet/span>' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Kiseijuu sei no Kakuritsu' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('KissXsis' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Kiznaiver' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Kizumonogatari 1: Tekketsu-Hen' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Kizumonogatari 2: Nekketsu-Hen' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Kobayashi-san Chi no Maid Dragon' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Koe no Katachi' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Koi to Uso' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Koi wa Ameagari no You ni' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Kokoro Connect' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Kokkoku' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Koufuku Graffiti' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Komori-san wa Kotowarenai' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Konbini Kareshi' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Konohana Kitan' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Kono Bijutsubu ni wa Mondai ga Aru!' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Kono Subarashii Sekai ni Shukufuku Wo! 2' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Koro-Sensei Quest!' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Kotoura-san' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Koukaku no Pandora' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Koutetsujou no Kabaneri' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Kowabon' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Kujira no Kora wa Sajou Utau' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Kuroko no Basuke' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Kuromukuro' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Kuma Miko' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Kuzu no Honkai' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Kyokai no Kanata Movie: Ill be Here' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Kyokai no Kanata Movie: Ill be Here - Mirai-hen' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Kyoto Teramachi Sanjou no Holmes' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Kyoukai no Rinne' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Lance N Masques' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Last Period: Owarinaki Rasen no Monogatari' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Layton Mystery tanteish: Katori no Nazotoki File' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Little Witch Academia (TV)' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Long Riders!' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Log Horizon S2' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Lord of Vermillion: Guren no Ou' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Lostorage Incited Wixoss' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Lostorage Conflated WIXOSS' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Lost Song' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Love Live! Sunshine!!' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Love Live! Sunshine!! Segunda temporada' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Love Kome: We Love Rice' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Luck and Logic' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Lupin III: Part V' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Macross Delta' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Made in Abyss' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Magi: The Labyrinth of Magic' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Magi: Sinbad no Bouken' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Magic Kaito 1412' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Magic Kyun! Renaissance' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Mahou Shoujo lyrical Nanoha Vivid' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Mahou Shoujo Ikusei Keikaku' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Mahou Shoujo Nante Mou II Desukara' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Mahou Shoujo Nante Mou II Desukara 2nd Season' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Mahou Shoujo Site' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Mahou Shoujo Ore' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Mahou Tsukai No Yome – Hoshi Matsu Hito' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('MahouTsukai No Yome' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Maken-ki!' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Maoyuu Mao Yuusha' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Marchan Madchen' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Masamune-kun no Revenge' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Masou Gakuen HxH Sin Censura' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Mayoiga' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('ME!ME!ME!' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Megalo Box' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Mikagura Gakuen Kumikyoku' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Military!' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Minami Kamakura Koukou Joshi Jitensha-Bu' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Miss Miira no Kaikata' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Miss Monochrome Animation 2' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Miss Monochrome Animation 3' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Miss Monochrome Animation 3' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Mitsuboshi Colors' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Mob Psycho 100' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('MomoKuri' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Monster Musume sin censura' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Musaigen no Phanton World' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Muhyo to Rouji no Mahoritsu Soudan Jimusou' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Nagato Yuki Chan No Shoushitsu' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Seiren' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Nanatsu: Imashime no Fukkatsu' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Nanatsu no Taizai Seisen no Shirushi' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Nanatsu no Bitoku' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Nana Maru San Batsu' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Nanbaka' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Nanbaka (2017)' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Naruto Shippuden Latino' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Naruto Shippuden' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Natsume Yuujinchou Go' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Nazotokine' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Nejimaki Seirei Senki: Tenkyou no Alderamin' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Netsuzou Trap -NTR-' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Ne-Juu no Susume' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Netoge no Yome wa Onnanoko Ja Nai to Omotta' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('New Game!' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('New Game!! Segunda Temporada' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Nil Admirari no Tenbin' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Ninja Slayer From Animation' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Nisekoi 2nd Season' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Nisekoi Ovas' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Nobunaga no Shinobi' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Nobunaga no Shinobi: Ise Kanegasaki-Hen' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Noragami Aragato' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Nora to Oujo to Noraneko Heart' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Norn9 Norn+Nonet' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Non Non Biyori Repeat' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Nyanko Days' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Occultic;Nine' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Ojisan to Marshmallow' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Okusama ga Soitokaichou' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Okusama ga Soitokaichou 2nd Season' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Omamori Himari!' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Omiai Aite wa Oshiego Tsuyoki na Monaiji' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Onsen Yousei Hakone-chan' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('One Punch Man' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('One Room' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Ongaku Shoujo (TV)' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Onigiri Anime' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Orange' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Ore ga Ojousama gakkou ni Shomin Sample' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Ore ga Suki nano wa Imouto dakedo Imouto ja Nai' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Ore Monogatari!!' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Ore Tachi ni Tsubasa wa Nai' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Osake wa Fuufu ni Natte Kara' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Osomatsu-san 2 (Segunda Temporada)' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Ousama Game The Animation' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Overlord' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Overlord Segunda Temporada' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Overlord Tercera Temporada' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Owari no Seraph' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Owari no Seraph Nagova Kessen-Hen' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Owarimonogatari' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Owarimonogatari Segunda temporada' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Ozmafia' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Pan de Peace!' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Persona 5 The Animation' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Phantom in the Twilight' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Piace: Watashi no Italian' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Piano no Mori (tv)' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Planetarian: Chiisana Hoshi no Yume' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Planet With' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Plastic Memories' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Plastic Nee-san' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Pokemon XYyZ' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Pokemon Sun y Moon' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Poo Team Epic' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Prince of Stride - Alternative' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Princess Principal' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Prison School' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Punchline' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Qualidea Code' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Queens Blade: Grimoire' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Radiant' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Rakudai Kishi no Cavalry' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Ramen Daisuki Koizumi-san' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Ranpo Kitan: Kitan Game of Laplace' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Re:Creators' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Regalia: The Three Sacred Stars' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Reikenzan: Eichi e No Shikaku' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('RELEASE THE SPYCE' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('ReLIFE' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('ReLIFE Kanketsu-hen' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Renai Boukun' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('RErideD: Koku Koe no Derrida' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Re:Zero Kara Hajimeru Isekai Seikatsu' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Rewrite' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Rewrite Moon and Terra' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Rick and Morty Temporada 3' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Rokudenashi Majutsu Koushi to Akashic Records' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Rokka no Yuusha' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('RWBY Volumen 4' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('RWBY Volumen 5' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Ryuuou no Oshigoto' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('SSSS.GRIDMAN' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Sakura Card Captor' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Saenai Heroine no Sodatekata' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Saenai Heroine no Sodatekata 2 (2017)' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Sakamoto Desu Ga?' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Sakura Quest' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Sakurada Reset' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Sakurako-san Ashimoto ni Wa Shitai' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Shakunetsu no Takkyuu Musume' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Saiki Kusuo no Psi' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Saiki Kusuo no Psi 2' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Saiyuuki Reload Blast' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Skirt no Naka wa Kedamono Deshita' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Sailor Moon Crystal 2014' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Sailor Moon crystal: death Busters-Hen' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Sangatsu no Lion' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Sangatsu no Lion Segunda temporada' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Sansha Sanyou' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Sanrio Danshi' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Saint Seiya: Soul of Gould' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Samurai Jack Season 5' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Saredo Tsumibito wa Ryuu to Odoru' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Satsuriku no Tenshi' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Scared Rider Xechs' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('SchoolGirl Strikers: Animation Channel' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Seisen Cerberus: ryuukoku no Fatalites' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Seikaisuru Kado' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Seiken tsukai no World Break' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Sieshun Buta Yarou wa Bunny Girl-senpai no Yume wo Minai' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Sekkou Boys' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Sengoku Night Blood' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Senki Zesshou Symphogear' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Senki Zesshou Symphogear G' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Senki Zesshou Symphogear GX' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Senki Zesshou Symphogear AXZ' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Servamp' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Sidonia no Kishi Segunda Temporada' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Shichisei no Subaru' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Shimoneta to Iu Gainen ga Sonzai Shinai' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Shigatsu wa Kimi no Uso' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Shingeki no Bahamut: Virgin Soul' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Shingeki no Kyojin Season 2' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Shingeki no Kyojin Season 3' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Shingeki no Kyojin: Kuinaki Sentaku' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Shingeki no Kyojin: Chuugakkou' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Shinmai Maou no Testament sin censura' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Shinmai Maou no Testament Burst sin censura' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Shinryaku! ika Musume' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Shinryaku! Ika Musume S2' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Shirobako' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Shiyan pin Jiating' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Shoujo Shuumatsu Ryokou' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Shoukoku no Altair' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-Hen' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Shuumatsu nani Shitemasu ka? Isogashi Desu ka? Sukutte Moratte II Desu Ka?' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Shuumatsu no Izetta' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Slow Start' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Sin: Nanatsu no Taizai' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Souten no Ken: Regenesis' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Sousei no Onmyouji' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Soushin Shoujo Matoi' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('SchoolGirl Strikers: Animation Channel' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Shoujo Kageki Revue Starlight' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Shoujo Tachi wa Kouya wo Mezasu' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Shokugeki no Souma: Ni no Sara' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Shokugeki no Souma: San no Sara' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Shokugeki no Souma: San no Sara - Tootsuki Ressha-hen' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Show by Rock' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Show by Rock!! #' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Shouwa Genroku Rakugo Shinjuu' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Sora to Umi no Aida' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Sora Yori mo Tooi Basho' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Sore ga Seiyuu' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Souryo to Majiwaru Shikiyoku no Yoru ni...' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Soul Buster' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('SpiritPact' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Star vs Forces of Evil Tercera Temporada' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Steins;Gate: Kyoukaimenjou no Missing Link' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Steins;Gate: 0' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Stella no Mahou' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Sunoharasou no Kanrinin-san' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Super Lovers' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Super Lovers 2' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Sword Art Online: Alicization' , 'Anime progresivo');
INSERT INTO animes(nombre,genero) VALUES ('Sword Art Online Alternative: Gun Gale Online' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Taboo Tatto' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Tachibanakan to Lie Angle' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Tada-kun wa Koi wo Shinai' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Taimadou Gakuen 35 Shiken Shoutai' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Takamiya Nasuno Desu!: Teekyuu Spin Off' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Taifuu no noruda' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Tanaka-kun wa Itsumo Kedaruge' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Tantei Team Kz Jiken Note' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Tensei Shitara Slime Datta Ken' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Tales of Zestiria The X' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Tales of Zestiria The X (2017)' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Teekyuu 4' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Tengen Toppa Gurren Lagann' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Tenrou: Sirius the Jaeger' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Tenshi no 3p!' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Terra Formars Revenge' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('The Rolling Girls' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Time Travel Shoujo: Mari waka To 8-nin no Kagakusha-Tachi' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Toaru Majutsu no Index III' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('To Be Heroine' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('To Love ru Darkness Sin Censura' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('To Love ru Darkness 2nd Sin Censura' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Toji no Miko' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Tokunomi' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Tokyo Ghoul S2' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Tokyo Ghoul:re' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Tokyo Ghoul:re 2nd Season' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Tokyo Ghoul Jack OVA' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Touken Ranbu: Hanamaru' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Tonari no Kyuuketsuki-san' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Tonkatsu Dj Agetarou' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Triage X' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Trickster: Edogawa Ranpo Shounen Tanteidan Yori' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes(nombre,genero) VALUES ('Tsurezure Children' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Tsuki ga Kirei' , 'Shonen');
INSERT INTO animes(nombre,genero) VALUES ('Tsukiuta The Animation' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Tsukipro The Animation' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Tsukumogami Kashimasu' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Tsugumomo' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('Two Car' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Uchi no Maid ga Uzasugiru' , 'Moe');
INSERT INTO animes(nombre,genero) VALUES ('Uchuu Patrol Luluco' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Uchuu Senkan Tiramisu' , 'Kemono');
INSERT INTO animes(nombre,genero) VALUES ('UQ Holder Mahou Sensei Negima! 2' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Ulysses: Jeanne d Arc to Renkin no Kishi' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Uma Musume Pretty Derby' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Ushio to tora' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Ushio to Tora (TV) 2nd Season' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Urahara' , 'Bish?jo');
INSERT INTO animes(nombre,genero) VALUES ('Urara Meirochou' , 'Mecha');
INSERT INTO animes(nombre,genero) VALUES ('Urawa no usagi-Chan' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Uta no Prince-Sama MAji Love Legend Star' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Utawarerumono Itsuwari no Kamen' , 'Super deformed');
INSERT INTO animes(nombre,genero) VALUES ('Valkyrie Drive Mermaid + Especiales' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Vatican Kiseki Chousakan' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Violet Evergarden' , 'Sentai');
INSERT INTO animes(nombre,genero) VALUES ('Vivid Strike!' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Wakaba Girl' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('Wakako Zake' , 'Mahô shôjo');
INSERT INTO animes(nombre,genero) VALUES ('Wake Up' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES (' Girls! Shin Shou' , 'Hentai');
INSERT INTO animes(nombre,genero) VALUES ('World Trigger' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Working!!! 3' , 'Magical Girlfriend');
INSERT INTO animes(nombre,genero) VALUES ('Watashi ga Motete Dousunda' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('WWW.Working!!' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Wotaku ni Koi wa Muzukashii' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Yagate Kimi ni Naru' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Yahari Ore no Seishun love Come Wa Machigatteiru 2nd Season' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Yamada-kun to 7-nin no Majo' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Yama no Susume 3' , 'Bish?nen');
INSERT INTO animes(nombre,genero) VALUES ('Yami Shibai 6' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Yoru no Yatterman' , 'Josei');
INSERT INTO animes(nombre,genero) VALUES ('Youkai Apartment no Yuuga na Nichijou' , 'Meitantei');
INSERT INTO animes(nombre,genero) VALUES ('Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Young Black Jack' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Youjo Senki' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Yowamushi Pedal New Generation' , 'Ecchi');
INSERT INTO animes(nombre,genero) VALUES ('Yowamushi Pedal: Glory Line' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('YU-GI-OH! GX' , 'Sh?jo-ai y Yuri');
INSERT INTO animes(nombre,genero) VALUES ('Yuuki Yuuna Wa Yuusha de Aru: Washio Sumi no Shou' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Yuuki Yuuna Wa Yuusha de Aru: Yuusha no Shou' , 'Harem Reverso');
INSERT INTO animes(nombre,genero) VALUES ('Yuri!!! One Ice' , 'Harem');
INSERT INTO animes(nombre,genero) VALUES ('Yuragi-sou no Yuuna-san' , 'Post-apocaliptico');
INSERT INTO animes(nombre,genero) VALUES ('Yuri Kuma Arashi' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Yuri Kuma Arashi' , 'Kodomo');
INSERT INTO animes(nombre,genero) VALUES ('Yuru Yuri Nachuyachumi Ova' , 'Gore');
INSERT INTO animes(nombre,genero) VALUES ('Yuru Yuri Nachuyachumi Plus' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Yuru Yuri-san Hai' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Yuru Camp' , 'Seinen');
INSERT INTO animes(nombre,genero) VALUES ('Zero Kara Hajimeru Mahou no Sho' , 'Spokon');
INSERT INTO animes(nombre,genero) VALUES ('Zoku Touken Ranbu: Hanamaru' , 'Sh?jo');
INSERT INTO animes(nombre,genero) VALUES ('Zombieland Saga' , 'Spokon');