INSERT INTO figuras ( peranime, tama_o) VALUES ('Elset Varley', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Darby Caplis', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Aarika Davitashvili', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ahmad Newlan', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Nona Tolle', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jackie Galey', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wilhelm Stegers', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Miriam Duffield', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Orland Klyner', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Aristotle Pyott', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Maddi Glusby', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Haley Follett', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Sigvard Meah', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Donia Warlock', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Meade Sergison', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Tulley Goodluck', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Neysa Picott', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Emelyne Goldstein', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Minni Gloyens', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Honey Shanley', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ker Talks', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wash Cauley', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bevin Downes', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Eloisa Bazire', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Donavon Lowthian', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Tom Keys', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Janina Clemoes', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Boote Fortie', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ignacius Lindsay', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bendix Renvoise', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jocelin Rodolfi', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ursola Pilch', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Adrian Van Castele', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jody Hallawell', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Tandi Fumagalli', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Esther Rippon', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jennee Sibbs', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Grant Rapps', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Sherie Petrusch', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Anissa Flannery', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rudyard de Clerk', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Misty Reen', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ursa Dymoke', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kurtis Lidgard', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kristofor Baldcock', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Diane-marie Brennenstuhl', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gerry Esom', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Sophie Sanches', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Etan Crilly', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Theresa Brownrigg', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Max Sturm', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Desirae Lowthian', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Korella Polack', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Carena Saltmarsh', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Blondell Plews', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Yardley Fugere', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('ip_address', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Merry Wardingly', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Griffin Bailles', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Harli Batcock', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Penny Sinderland', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wilbur Ca', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Shannan Pollard', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Winthrop Strafen', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Micah Nani', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bevvy Guilliatt', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Eldin Kissell', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Tracy Fidilis', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Thatcher Mochar', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Shandee ORiordan', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Chantal Elliott', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Aldridge Serchwell', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Marisa Sibborn', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Fred Blackden', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Thedric Woollaston', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Joyan Chenery', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Peirce Ferentz', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Barclay Kynson', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Locke Pardew', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Aleta Randall', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Cathlene Yurin', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rhetta Asipenko', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Brigit Lowdes', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Merrily Ingold', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Cahra Cordon', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Inna Heaney', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Chadd Hinchcliffe', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bellanca Braxton', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gerrie Sullly', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Eartha Clemence', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Larine Jolley', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Nate Binnall', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hermann Zannetti', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Roddie Boow', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Barron Cudihy', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Audrey Merryman', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Washington Skehens', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Arni Robrose', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dulci Losseljong', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Aimee Toleman', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Amabel Lacey', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Elbertine Abbyss', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bary Ceresa', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Abbe Petren', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rosamond Cloney', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Andeee Hillett', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kennett Alfonso', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rubetta McCrow', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Felicia Feld', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Tymothy Itschakov', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Florette Ebunoluwa', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Eilis Quickenden', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Cynthia Goatman', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Andy Priddis', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kelvin Rabbitt', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Camila Ingrem', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lorenzo Skelbeck', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bernita Swinglehurst', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Baudoin Livoir', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Patrice Spadoni', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hilda Girk', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Felike Stranks', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('James McReidy', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hazlett Jendrassik', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Clerc Antunez', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Shelton Cawtheray', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rosamund Benian', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Darn Plumbley', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Shelly McGraw', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rubia Dawidowicz', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dolph Straneo', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Reece Durant', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Liana Sawdy', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Francesca Sunners', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Annadiane Cosens', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Grover Denisovo', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Celle Rozec', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Freedman Dwyr', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ferdy Balazin', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Pet Isaaksohn', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dela Evreux', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Siana Romeo', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rory Lehr', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kylie Draysey', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ansel Treleven', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jobie Havik', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Humphrey Turvie', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wadsworth Merigot', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gilemette Ethridge', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Shae Lockwood', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Connie Balderson', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lexy Lyster', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Livvyy Gagan', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Man Denyukhin', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Amalie Baldwin', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Constancia Desbrow', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wilona Ourtic', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Charmine Stelfax', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ric Brigham', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Noni Pitone', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ken Marlen', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bax Taphouse', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rodolphe Bignold', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Karyn Sunner', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Giorgia Brett', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Galvin Goodredge', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Liva Gornar', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Emmerich Mertel', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lilla Pattini', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Charmion Gamblin', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Aleece Johnsson', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ingrim Satchell', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rahal Baptiste', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Claribel Gurrado', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Konstanze Heigho', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Marylynne Boyne', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Padraic Hanbidge', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Noelani Saiens', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wren Calvard', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Goober Toten', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rees Linwood', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hakeem Delwater', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Haywood Phetteplace', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Suzette Tilling', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Edie Shade', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hall Clemensen', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Darell Wakeford', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Heidi OScandall', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Matty Tardiff', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Laetitia Jackes', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Micah MacGlory', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bernita Slay', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Steve Maidlow', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hyacintha Wandtke', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Cookie Canon', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Reagan Potebury', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Berrie Plummer', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Waylon Foyston', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hedvige Fidian', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Krystal Benitez', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lenore de Grey', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Viv Gosart', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Tanney Weiser', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gianni Boydle', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gwenneth Shercliff', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jemimah Zuan', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ketti Stigell', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Caritta Robart', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Pamella Pattingson', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Far Scarasbrick', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Sanders Kellar', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Eustacia Orhtmann', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Berkie Blackett', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ilaire Mac', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Zia Leat', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Moyna Mapledoram', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Johnathan Lumby', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Valery Synder', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lin Fuster', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Boonie Blodgetts', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gareth Miranda', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Mick Lovel', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Abagail Haughan', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wheeler Ixer', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ned Sanbrook', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jerrie Mundall', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Marwin Tudbald', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Catriona Rebichon', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jackquelin Crush', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Edgardo Becraft', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Fulvia Cassidy', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lanette Pestricke', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bev Petrelli', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Vernice McEachern', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Carey Whitehair', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lucas Masselin', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Timi Castilla', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gayla Cleere', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Carol-jean Budnik', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Reamonn Turnor', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Mackenzie Rohmer', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ranice Waplinton', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Carlynn Perview', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Faith Landsberg', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Murdoch Tembridge', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Karylin Trent', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ruy McDool', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rosita Kenelin', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Raimundo Sturney', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Nikolai Dowe', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Irvin Dugget', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Barrett Conradie', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Val Rickman', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kerry Burder', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ruthann Ganforthe', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bradley Hayller', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Geri Renzini', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gilles Ferrarotti', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rori Mates', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wandis Andri', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Agosto Jordine', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Aurea Winsbury', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Connie Brower', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Doretta Martineau', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Constantino Fitzhenry', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Clayborne Larenson', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Holmes Antham', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Noby Seeviour', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Demetris Roz', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Winn Burcombe', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Clifford Queree', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Martainn Merali', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kai Stempe', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Benito Creavan', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Eldridge Dukes', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bronny Wissbey', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Emlen Baumaier', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Roderic Burtonwood', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Glori Fayter', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Aldridge Chelsom', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jean Maddocks', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jaimie Bernholt', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Catherina Banasevich', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Beulah Gaynesford', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Coleman Manass', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jesse Salthouse', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rheta Longbone', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Crystie Drillingcourt', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Myron Gustus', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Valerye Ricart', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Merry Nappin', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Mandel Wogden', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gunar Berrecloth', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Tiebout Meiklem', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wyndham Keinrat', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jamey Mouget', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Emmanuel Igoe', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Mirna Izzatt', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dmitri Pratley', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gan Beartup', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jordan Valerius', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Charita Akrigg', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Berkeley Dawnay', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Eberto Kloster', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Myron Powys', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hanna McClaren', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bobina Deluce', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kathrine Hartburn', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ermin Worlock', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Benn Grimsdike', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Luther Giron', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Greg Crate', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rockey Mawhinney', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Adolph Harkes', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kristian Blankley', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Carley Schruur', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ted Pettis', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lebbie Cassedy', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Asa Berringer', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bronnie Caizley', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Iolande Cowlard', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Florentia Summerly', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Glen Maystone', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hermina Murrhaupt', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dulcie Dufer', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Tiphany Dietmar', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wendy Goodison', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Robyn Fligg', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Vlad Chittenden', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Alon Newton', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lombard Lednor', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jacky Totman', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ernestine Leat', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Stillmann Hue', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dorelia Du Plantier', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Danice Stivey', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Sharleen Pessolt', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Car Romanini', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Honor Titcomb', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Myrle MacGlory', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Johann Turnpenny', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Marina Penreth', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Andrew Angear', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jason Chupin', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Suzie Crinson', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wadsworth Carefull', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hussein Bartrum', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Clerc Kirby', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Cristie Linley', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ronni Hebblethwaite', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Augustine Ligertwood', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jewel Matousek', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Windy Scipsey', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ferrell Hutton', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Merralee Shrimptone', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Erie Gotcher', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ransom Mulvin', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Corny Crossfeld', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Renaud Bortolazzi', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Nonie Jerzyk', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lonny Santos', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Paulina Hembrow', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Maurine McCarver', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Alfi Bracco', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Edvard Pantridge', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Nevins Flecknoe', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jarid Hunte', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Levi Gentile', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Perceval Di Biasio', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Patrick Graves', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Isidro Fehely', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Shandeigh Widdison', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Nicol Calcutt', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dulcea Toogood', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Mariette Wornum', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Danita Winsiowiecki', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Perla Faccini', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Garth Reddihough', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Mack Oxbury', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Linette Puttick', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Moria Gunther', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Nanine Bithany', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kaylyn Okill', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dulcea Clitheroe', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Laughton Remnant', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Camilla Dunk', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lionel OBeirne', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Filide Gandley', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dixie Stonhard', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Melisenda Normanvill', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Marti Passie', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Adelle Blind', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Aluin Jessard', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kimberley Ruffler', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ossie Baldin', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hadley Jesson', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Maxie Burgin', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Merrel Frediani', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Mellisa Bohike', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Rosalinde Langdale', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Atlante True', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Perceval Hierro', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Sully Fallanche', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dorita Drysdall', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gaston Francis', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Alexia Crossfield', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jessica Madgwich', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kaye Ribou', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Carney Barnett', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Guendolen Giannotti', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Fair Iacovaccio', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Billie Fitzsimon', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Keane Khomich', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Analiese Maudlin', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Graehme Kubicek', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Titos Maine', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Florida Baggiani', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kevin Gair', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Wendi Swettenham', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Alicea Moggach', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Adella Bownass', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bord Strahan', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Stacee Vaillant', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Fairfax Gleadhall', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Port Dumbell', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Liam Friary', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Laurence Phillp', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Catharina Gronow', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kynthia Wahlberg', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Andrei Sprott', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Shanna Stoven', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Niko Tinsley', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kristine Swadden', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Carlota McCord', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jessa Struijs', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Mead Hughman', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Marillin Bryning', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Allister Morrallee', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Onida Pollins', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Bee Longfoot', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hillyer Ayce', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Hakim Younie', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Aurore Sparks', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Brok Noblett', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Cecilio Riatt', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Melva Drakard', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gideon Findlay', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Cam Rothon', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Michaela Geale', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Moreen Janicek', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Dannie Pick', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jojo Yoxall', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Margaux Estable', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Mignon Frankton', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Arleyne Coffelt', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Nolan Gristock', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Izabel Yeatman', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Irvine Chewter', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Titos MacKartan', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jasun Secret', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Patti Allchorn', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Allin Pocknell', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Randy Veart', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Devina O Timony', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Virgilio Champneys', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Perice Domel', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Nye Messent', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Gare Ambrus', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Celestina Huntly', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Granger Fleis', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Sonny Deane', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Crystal Burnall', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ellen Itscovitz', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ringo McGinly', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Filbert Moller', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Ursulina Kyle', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Fabian Labusquiere', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Jarred Grinaway', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Drucill Parnaby', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Sully Ralton', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Josefa Galia', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Baxie Waterhowse', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Elfrieda Martinets', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Vinita Dolligon', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Loutitia Braban', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Vincent Kedslie', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Woody Screen', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Joseph Ferriby', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Binny Burchnall', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Cesya Itzkovwitch', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Marice Fredson', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Callean Linder', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Stacia Gostyke', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Paco Fawcett', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Lyda Tumber', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Janna Baldwin', 'Real');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Colene Kittoe', 'Pequeño');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Daniel Kovelmann', 'Mediano');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Annie Stockman', 'Grande');
INSERT INTO figuras ( peranime, tama_o) VALUES ('Kelvin Bicksteth', 'Real');

INSERT INTO figuras(peranime,tama_o) VALUES ('Hare (personaje)' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mireille Bouquet' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Okuyasu Nijimura' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Genji Kamogawa' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kotaro Kobayashi' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Usagi Tsukino' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hideki Motosuwa' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mikoto Minagi' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yuki Nagato' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Genji Kamogawa' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kaede Saito' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Capitán Kuro' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Louise Françoise le Blanc de la Vallière' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Takumi Tokiha' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Zoe Ayamoto' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kazuto Kirigaya' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shizuka Domeki' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Lan Hikari' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yoichi Hiruma' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mikoto Minagi' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jonathan Joestar' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kaiketsu Zorori' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('La abeja Maya' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Usuario:VictiniLikeWaffles/Taller' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Nao Yuuki' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Genji Kamogawa' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yoshikage Kira' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sakura Kinomoto' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yuko Ichihara' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tala Valkov' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yuno Gasai' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kimihiro Watanuki' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kyon' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Fly (Dragon Quest)' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Makoto Ito' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yuko Ichihara' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Akira (personaje)' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Neuro Nogami' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tamayo Kisaki' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Astroboy' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shuko Suzuhara' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sumilidon' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Vash' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jet Marte' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tamayo Kisaki' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsumi Tsujimoto' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Relena Darlian' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Joseph Joestar' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ban Mido' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Makoto Ito' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Batou' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Josuke Higashikata' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Takumi Tokiha' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ban Mido' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('OS-tan' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Rohan Kishibe' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Astroboy' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kamome Sengakuji' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mikan Sakura' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yoichi Hiruma' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sumilidon' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Relena Darlian' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yoshikage Kira' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Gatchaman' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tala Valkov' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Dio Brando' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('DArtacán y los tres mosqueperros' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Haruhi Suzumiya' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Katsura Kotonoha' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eichi Sakurai' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Akira (personaje)' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sumeragi Subaru' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Caesar A. Zeppeli' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('La pequeña Lulú' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Max Tate' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Miyuki Kobayakawa' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Miyuki Kobayakawa' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Relena Darlian' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('La abeja Maya' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Príncipe Planeta' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Usagi Tsukino' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shizuru Fujino' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Genjo Sanzo' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Suzume Sakurajosui' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Zoe Ayamoto' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mireille Bouquet' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Capitán Kuro' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hare (personaje)' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Metabee' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsuki Kuga' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Skyress' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hideki Motosuwa' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Koichi Hirose' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('El hombre que ríe (personaje)' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jungle Taitei' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Okuyasu Nijimura' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ichiro Mihara' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jean Pierre Polnareff' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Haruka Suzushiro' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ninja Hattori' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kyon' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yoichi Hiruma' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Muglox' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ryo Mashiba' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Genji Kamogawa' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ippo Makunouchi' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsume Hyuga' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kyatto Ninden Teyandee' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Abuelo de Heidi' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ryo Mashiba' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Skyress' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ryo Mashiba' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('My Melody' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Muhammad Avdol' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hokuto Sumeragi' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kaede Saito' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yuki Nagato' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Muglox' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Dragonoid' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsumi Tsujimoto' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Max Tate' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsuki Kuga' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ban Mido' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kimihiro Watanuki' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Noriaki Kakyoin' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Dio Brando' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mikan Sakura' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Anexo:Personajes de Shin-chan' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Momoko Hanasaki' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Joseph Joestar' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ban Mido' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Gintoki Sakata' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Norakuro' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Rohan Kishibe' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kyatto Ninden Teyandee' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Iggy (JoJos)' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('El gato Félix' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Allen Walker' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Genjo Sanzo' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mai Tokiha' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Dio Brando' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Boogiepop (personaje)' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kotaro Kobayashi' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Louise Françoise le Blanc de la Vallière' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Haruhi Suzumiya' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Heidi (personaje)' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jotaro Kujo' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Nana Komatsu' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kai Hiwatari' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Grosser' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Lan Hikari' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tsugumi Higashijujo' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kai Hiwatari' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Nana Komatsu' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Vash' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Metabee' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Akane Higurashi' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsuki Kuga' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Suzume Sakurajosui' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kiteretsu' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Rohan Kishibe' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jet Marte' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hokuto Sumeragi' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hibari Hanakoganei' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yui Kasuga' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hermanas Fujisaki' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Príncipe Planeta' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hibari Hanakoganei' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Akira (personaje)' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ojiro Mihara' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Cyborg 009' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Makoto Ito' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ricardo Espadas' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Usagi Tsukino' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mai Tokiha' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Haruhi Suzumiya' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ricardo Espadas' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shizuru Fujino' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('MS903 Doraemon' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hol Horse' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kiteretsu' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('MegaMan.EXE' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Fly (Dragon Quest)' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Lisa Lisa (JoJos)' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hermanas Fujisaki' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Relena Darlian' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shugo Kunisaki' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Katsura Kotonoha' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yuko Ichihara' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Khyron' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hol Horse' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ojiro Mihara' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Anexo:Personajes de Shin-chan' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tsugumi Higashijujo' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsumi Tsujimoto' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('El gato Félix' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Khyron' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kyon' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shinichi Kudo' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Dragonoid' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tokoroten no Suke' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Misaki Suzuhara' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('OS-tan' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eichi Sakurai' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tamayo Kisaki' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hatoko Kobayashi' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Vash' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sai Jonouchi' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Grosser' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Boogiepop (personaje)' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Enma Ai' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Usuario:VictiniLikeWaffles/Taller' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sai Jonouchi' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shizuka Domeki' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('El hombre que ríe (personaje)' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kiteretsu' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yoshikage Kira' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Usuario:VictiniLikeWaffles/Taller' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Rohan Kishibe' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tochiro Oyama' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jotaro Kujo' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Lisa Lisa (JoJos)' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kazuto Kirigaya' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('MegaMan.EXE' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('My Melody' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mariah (JoJos)' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Capitán Kuro' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eiichi Kite' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Nao Yuuki' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Calimero' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shuko Suzuhara' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sakura Kinomoto' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Iggy (JoJos)' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Max Tate' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ricardo Espadas' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hello Kitty' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jet Marte' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tochiro Oyama' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Vash' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Nao Yuuki' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ichiro Miyata' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Calimero' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hitomi Kanzaki' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Enma Ai' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hermanas Fujisaki' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('MS903 Doraemon' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ichiro Miyata' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tokoroten no Suke' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Momoko Hanasaki' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Koichi Hirose' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Gatchaman' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yui Kasuga' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Muhammad Avdol' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('El hombre que ríe (personaje)' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Misaki Suzuhara' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Lisa Lisa (JoJos)' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Metabee' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Lan Hikari' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('MegaMan.EXE' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shugo Kunisaki' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yuki Nagato' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sai Jonouchi' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Louise Françoise le Blanc de la Vallière' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Norakuro' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hare (personaje)' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Batou' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Akane Higurashi' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kotaro Kobayashi' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Toon' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Cho Hakkai' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mariah (JoJos)' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsume Hyuga' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('MS903 Doraemon' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('La pequeña Lulú' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Noriaki Kakyoin' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Haruhi Suzumiya' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ichiro Miyata' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Joseph Joestar' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Koichi Hirose' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Grosser' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Takumi Tokiha' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Príncipe Planeta' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Neuro Nogami' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsumi Tsujimoto' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Iggy (JoJos)' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('MegaMan.EXE' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hatoko Kobayashi' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hol Horse' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Momoko Hanasaki' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Calimero' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Genjo Sanzo' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('OS-tan' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Vickie el vikingo' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kazuto Kirigaya' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mamoru Takamura' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Gintoki Sakata' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('La pequeña Lulú' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sumilidon' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Strider Hiryu' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jasmine y Meddy' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hibari Hanakoganei' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mikoto Minagi' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hideki Motosuwa' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('OS-tan' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yoshikage Kira' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Vickie el vikingo' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mireille Bouquet' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Khyron' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tochiro Oyama' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kaede Saito' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Guu' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Okuyasu Nijimura' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tala Valkov' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tochiro Oyama' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mariah (JoJos)' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Muhammad Avdol' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Zoe Ayamoto' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Cho Hakkai' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hatoko Kobayashi' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sumeragi Subaru' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Max Tate' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('La abeja Maya' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Skyress' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Muhammad Avdol' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Enma Ai' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shizuru Fujino' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Astroboy' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yuno Gasai' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Heidi (personaje)' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ichiro Miyata' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eichi Sakurai' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kiteretsu' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kai Hiwatari' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Itsuki Koizumi' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jet Marte' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yuki Nagato' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Usuario:VictiniLikeWaffles/Taller' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kotaro Kobayashi' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kamome Sengakuji' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eikichi Onizuka' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('My Melody' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Motoko Kusanagi' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Calimero' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Strider Hiryu' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Merlin (personaje de Nanatsu no Taizai)' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mikan Sakura' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kimihiro Watanuki' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hello Kitty' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hitomi Kanzaki' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('MS903 Doraemon' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kaede Saito' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Misaki Suzuhara' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Itsuki Koizumi' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jungle Taitei' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eiichi Kite' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tamayo Kisaki' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Josuke Higashikata' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Suzume Sakurajosui' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Cyborg 009' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ninja Hattori' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mamoru Takamura' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ichiro Mihara' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mai Tokiha' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Lisa Lisa (JoJos)' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mariah (JoJos)' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jungle Taitei' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yui Kasuga' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hibari Hanakoganei' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Misaki Suzuhara' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Khyron' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sumeragi Subaru' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Skyress' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jotaro Kujo' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eichi Sakurai' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Arale Norimaki' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sai Jonouchi' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shuko Suzuhara' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Arale Norimaki' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jean Pierre Polnareff' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ippo Makunouchi' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Cho Hakkai' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sakura Kinomoto' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Guu' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Vickie el vikingo' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('My Melody' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Josuke Higashikata' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Muglox' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shugo Kunisaki' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shinichi Kudo' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Abuelo de Heidi' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mamoru Takamura' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hitomi Kanzaki' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Iggy (JoJos)' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsume Hyuga' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Metabee' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Noriaki Kakyoin' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hello Kitty' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Fly (Dragon Quest)' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Toon' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tokoroten no Suke' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Dio Brando' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Capitán Kuro' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kyatto Ninden Teyandee' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jonathan Joestar' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Gintoki Sakata' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jonathan Joestar' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Katsura Kotonoha' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Okuyasu Nijimura' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sekai Saionji' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Haruka Suzushiro' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Cyborg 009' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Motoko Kusanagi' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hitomi Kanzaki' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sekai Saionji' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Fly (Dragon Quest)' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jean Pierre Polnareff' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ichiro Mihara' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kyatto Ninden Teyandee' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Enma Ai' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eikichi Onizuka' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Allen Walker' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Gatchaman' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jean Pierre Polnareff' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sumilidon' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsuki Kuga' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Miyuki Kobayakawa' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hokuto Sumeragi' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Abuelo de Heidi' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Toon' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ippo Makunouchi' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Louise Françoise le Blanc de la Vallière' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eikichi Onizuka' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('El gato Félix' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Muglox' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kaiketsu Zorori' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Heidi (personaje)' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hideki Motosuwa' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tsugumi Higashijujo' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hol Horse' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Noriaki Kakyoin' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Haruka Suzushiro' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Norakuro' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kimihiro Watanuki' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Momoko Hanasaki' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hello Kitty' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Sekai Saionji' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kai Hiwatari' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eiichi Kite' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jasmine y Meddy' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Batou' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Takumi Tokiha' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Strider Hiryu' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Dragonoid' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Yuno Gasai' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Gintoki Sakata' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mamoru Takamura' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Norakuro' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shizuru Fujino' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Shugo Kunisaki' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Nana Komatsu' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Natsume Hyuga' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ippo Makunouchi' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Cho Hakkai' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('El gato Félix' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tala Valkov' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Akira (personaje)' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Eiichi Kite' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mikoto Minagi' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Haruka Suzushiro' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Príncipe Planeta' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kaiketsu Zorori' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Dragonoid' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('El hombre que ríe (personaje)' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Caesar A. Zeppeli' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Motoko Kusanagi' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hokuto Sumeragi' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Mikan Sakura' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Merlin (personaje de Nanatsu no Taizai)' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Tokoroten no Suke' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Grosser' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Lan Hikari' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Vickie el vikingo' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Abuelo de Heidi' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ninja Hattori' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jotaro Kujo' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Jungle Taitei' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Itsuki Koizumi' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('DArtacán y los tres mosqueperros' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Nao Yuuki' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Ninja Hattori' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Allen Walker' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('La abeja Maya' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Itsuki Koizumi' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Boogiepop (personaje)' , 'Pequeño');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hare (personaje)' , 'Mediano');
INSERT INTO figuras(peranime,tama_o) VALUES ('Kazuto Kirigaya' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Hermanas Fujisaki' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Caesar A. Zeppeli' , 'Real');
INSERT INTO figuras(peranime,tama_o) VALUES ('Guu' , 'Grande');
INSERT INTO figuras(peranime,tama_o) VALUES ('Boogiepop (personaje)' , 'Real');