INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Elset Varley', 'your name.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Darby Caplis', 'Fullmetal Alchemist: Brotherhood');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aarika Davitashvili', 'Steins;Gate');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ahmad Newlan', 'Clannad After Story');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nona Tolle', 'Rurouni Kenshin: Trust y  Betrayal');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jackie Galey', 'Code Geass: Lelouch of the Rebellion R');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wilhelm Stegers', 'Spirited Away');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Miriam Duffield', 'A Silent Voice');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Orland Klyner', 'Cowboy Bebop');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aristotle Pyott', 'Mushishi: The Next Chapter');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Maddi Glusby', '(The) Disappearance of Haruhi Suzumiya');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Haley Follett', 'Princess Mononoke');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sigvard Meah', '(The) Legend of the Galactic Heroes');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Donia Warlock', 'Mushi-Shi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Meade Sergison', 'Death Note');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tulley Goodluck', 'Maria Watches Over Us rd Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Neysa Picott', 'Made in Abyss');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Emelyne Goldstein', 'Maria Watches Over Us Season : Printemps');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Minni Gloyens', 'Code Geass: Lelouch of the Rebellion');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Honey Shanley', 'Gintama');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ker Talks', 'anohana: The Flower We Saw That Day');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wash Cauley', 'Descending Stories: Showa Genroku Rakugo Shinju');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bevin Downes', 'Maria Watches Over Us th Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eloisa Bazire', 'Gintama');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Donavon Lowthian', 'Gintama (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tom Keys', 'Bunny Drop');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Janina Clemoes', 'Evangelion: . You Can (Not) Advance');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Boote Fortie', 'Monster');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ignacius Lindsay', 'Grave of the Fireflies');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bendix Renvoise', 'Cross Game');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jocelin Rodolfi', 'Ghost in the Shell: Stand Alone Complex nd GIG');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ursola Pilch', 'Summer Wars');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Adrian Van Castele', 'Fighting Spirit');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jody Hallawell', 'Fullmetal Alchemist');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tandi Fumagalli', 'Hunter × Hunter');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Esther Rippon', 'Nodame Cantabile');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jennee Sibbs', '(The) Girl Who Leapt Through Time');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Grant Rapps', 'Centimeters Per Second');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sherie Petrusch', 'Nausicaä of the Valley of the Wind');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Anissa Flannery', 'Gurren Lagann');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rudyard de Clerk', '(The) Garden of Sinners');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Misty Reen', 'Wolf Children');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ursa Dymoke', 'My Neighbor Totoro');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kurtis Lidgard', 'Baccano!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kristofor Baldcock', 'Honey and Clover II');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Diane-marie Brennenstuhl', 'Natsumes Book of Friends');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gerry Esom', 'Gintama: The Final Movie');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sophie Sanches', 'Hajime no Ippo: New Challenger');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Etan Crilly', 'Kanon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Theresa Brownrigg', 'Star Blazers');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Max Sturm', 'GTO: Great Teacher Onizuka');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Desirae Lowthian', 'Kinos Journey');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Korella Polack', 'Howls Moving Castle');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carena Saltmarsh', 'Time of Eve');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Blondell Plews', 'Puella Magi Madoka Magica');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Yardley Fugere', 'Mushishi Tokubetsu-hen: Hihamukage');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'ip_address', 'Natsumes Book of Friends');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Merry Wardingly', 'Millennium Actress');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Griffin Bailles', 'Time of Eve');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Harli Batcock', 'Monogatari Series Second Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Penny Sinderland', 'Kaleido Star');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wilbur Ca', 'Mononoke');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shannan Pollard', 'Kids on the Slope');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Winthrop Strafen', 'Natsumes Book of Friends');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Micah Nani', '(The) Melancholy of Haruhi Suzumiya');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bevvy Guilliatt', 'Gankutsuou: The Count of Monte Cristo');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eldin Kissell', 'Clannad');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tracy Fidilis', 'Planetes');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Thatcher Mochar', 'NANA');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shandee ORiordan', 'Looking Up At The Half-Moon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Chantal Elliott', 'Castle in the Sky');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aldridge Serchwell', 'Your Lie in April');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marisa Sibborn', 'Whisper of the Heart');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Fred Blackden', 'Samurai Champloo');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Thedric Woollaston', 'Ouran High School Host Club');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Joyan Chenery', 'A Place Further Than the Universe');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Peirce Ferentz', 'Gurren Lagann the Movie – The Lights in the Sky Are Stars');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Barclay Kynson', '(The) Beast Player Erin');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Locke Pardew', 'Ghost in the Shell: Stand Alone Complex');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aleta Randall', 'Maria Watches Over Us');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cathlene Yurin', 'Aria the Origination');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rhetta Asipenko', 'Spice and Wolf II');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Brigit Lowdes', 'Angel Beats!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Merrily Ingold', 'Moribito - Guardian of the Spirit');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cahra Cordon', 'March comes in like a lion');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Inna Heaney', 'Haikyu!! Second Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Chadd Hinchcliffe', 'My Hero Academia');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bellanca Braxton', 'ef: a tale of melodies');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gerrie Sullly', 'ef: a tale of memories');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eartha Clemence', 'Haikyu!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Larine Jolley', 'Black Lagoon: The Second Barrage');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nate Binnall', 'Welcome to the NHK');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hermann Zannetti', 'Re:ZERO -Starting Life in Another World-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Roddie Boow', 'Legend of the Galactic Heroes: Overture to a New War');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Barron Cudihy', 'Mushishi: Zoku-Sho: Suzu no Shizuku');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Audrey Merryman', '(The) Tale of the Princess Kaguya');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Washington Skehens', 'Honey and Clover');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Arni Robrose', 'Sword of the Stranger');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dulci Losseljong', 'Haibane Renmei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aimee Toleman', 'Showa Genroku Rakugo Shinju');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Amabel Lacey', '(The) Twelve Kingdoms');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Elbertine Abbyss', 'Hunter X Hunter');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bary Ceresa', 'My Hero Academia');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Abbe Petren', 'Cowboy Bebop: The Movie');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rosamond Cloney', 'Tokyo Godfathers');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Andeee Hillett', 'Toradora!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kennett Alfonso', 'Romeo × Juliet');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rubetta McCrow', 'Owarimonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Felicia Feld', 'Maison Ikkoku');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tymothy Itschakov', 'Major');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Florette Ebunoluwa', 'Evangelion: . You Are (Not) Alone');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eilis Quickenden', 'Shirobako');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cynthia Goatman', 'Hellsing Ultimate');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Andy Priddis', 'Chihayafuru');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kelvin Rabbitt', 'Tsubasa Toyo Revelations');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Camila Ingrem', 'Katanagatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lorenzo Skelbeck', 'Mobile Suit Gundam UC');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bernita Swinglehurst', '(The) Garden of Words');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Baudoin Livoir', 'Full Metal Panic! The Second Raid');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Patrice Spadoni', 'Gintama.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hilda Girk', 'Hunter X Hunter');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Felike Stranks', 'Fate/Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'James McReidy', 'ERASED');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hazlett Jendrassik', 'BECK: Mongolian Chop Squad');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Clerc Antunez', 'Kimi ni Todoke - From Me to You');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shelton Cawtheray', '(La) Maison en Petits Cubes');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rosamund Benian', 'Den-noh Coil');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Darn Plumbley', 'Bakuman');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shelly McGraw', 'One Piece Episode of Nami: Kokaishi no Namida to Nakama no Kizuna');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rubia Dawidowicz', 'Natsumes Book of Friends');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dolph Straneo', 'Attack on Titan');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Reece Durant', 'JoJos Bizarre Adventure: Diamond Is Unbreakable');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Liana Sawdy', 'Nodame Cantabile: Paris');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Francesca Sunners', 'Lupin the Third: Part');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Annadiane Cosens', 'Berserk');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Grover Denisovo', 'Brave King GaoGaiGar Final');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Celle Rozec', 'Kaiba');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Freedman Dwyr', 'Ping Pong');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ferdy Balazin', 'Princess Tutu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Pet Isaaksohn', 'Conan, the Boy in Future');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dela Evreux', 'Hotarubi no Mori e');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Siana Romeo', 'Azumanga Daioh');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rory Lehr', 'Full Metal Panic? Fumoffu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kylie Draysey', 'Nodame Cantabile: Finale');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ansel Treleven', 'Eden of the East');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jobie Havik', '(The) Rose of Versailles');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Humphrey Turvie', 'Mushishi Zoku-Sho Tokubetsu-hen: Odoro no Michi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wadsworth Merigot', 'unter X Hunter: G I Final');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gilemette Ethridge', 'Haikyu!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shae Lockwood', 'Yuri!!! on Ice');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Connie Balderson', 'Girls und Panzer der Film');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lexy Lyster', 'Natsume Yujin-Cho Roku');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Livvyy Gagan', 'Mob Psycho');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Man Denyukhin', 'Assassination Classroom');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Amalie Baldwin', 'Kimi ni Todoke nd Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Constancia Desbrow', 'Maquia - When the Promised Flower Blooms');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wilona Ourtic', 'Hanasaku Iroha - Blossoms for Tomorrow');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Charmine Stelfax', 'Trigun');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ric Brigham', 'Ghost in the Shell: Stand Alone Complex: Solid State Society');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Noni Pitone', 'Paprika');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ken Marlen', 'Spice and Wolf');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bax Taphouse', 'Magnetic Rose');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rodolphe Bignold', 'School Rumble: nd Semester');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Karyn Sunner', 'R.O.D -The TV-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Giorgia Brett', 'Violet Evergarden');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Galvin Goodredge', 'Ashita no Joe');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Liva Gornar', 'Sound! Euphonium');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Emmerich Mertel', 'Berserk: The Golden Age Arc III - The Advent');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lilla Pattini', '(The) Eccentric Family');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Charmion Gamblin', 'Gungrave');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aleece Johnsson', 'Last Exile');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ingrim Satchell', 'Bakuman.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rahal Baptiste', 'Rurouni Kenshin');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Claribel Gurrado', 'Legend of the Galactic Heroes: My Conquest is the Sea of Stars');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Konstanze Heigho', 'Comedy');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marylynne Boyne', 'Land of the Lustrous');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Padraic Hanbidge', 'When Marnie Was There');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Noelani Saiens', 'Skip Beat!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wren Calvard', 'Natsume Yujin-Cho Go');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Goober Toten', 'In This Corner of the World');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rees Linwood', 'xxxHOLiC: Kei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hakeem Delwater', 'Attack on Titan');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Haywood Phetteplace', 'Neon Genesis Evangelion: The End of Evangelion');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Suzette Tilling', 'Bakemonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Edie Shade', '(The) Super Dimension Fortress Macross: Do You Remember Love?');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hall Clemensen', 'Master Keaton');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Darell Wakeford', 'Kikis Delivery Service');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Heidi OScandall', 'Hunter X Hunter: Greed Island');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Matty Tardiff', 'Romeo and the Black Brothers');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Laetitia Jackes', 'Hajime no Ippo - Champion Road');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Micah MacGlory', '(The) Super Dimension Fortress Macross');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bernita Slay', 'Gintama');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Steve Maidlow', 'One Outs');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hyacintha Wandtke', 'Tiger y  Bunny');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cookie Canon', 'Black Lagoon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Reagan Potebury', 'Neon Genesis Evangelion');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Berrie Plummer', 'Fate/stay night: Unlimited Blade Works');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Waylon Foyston', 'Ghost in the Shell: Stand Alone Complex - Individual Eleven');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hedvige Fidian', '(The) Boy and The Beast');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Krystal Benitez', '(The) Anthem of the Heart');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lenore de Grey', 'Fate/Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Viv Gosart', 'Food Wars! Shokugeki no Soma');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tanney Weiser', 'Mobile Suit Gundam  Second Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gianni Boydle', 'Macross Frontier');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gwenneth Shercliff', 'Darker than Black');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jemimah Zuan', 'Nichijou - My Ordinary Life');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ketti Stigell', 'Space Brothers');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Caritta Robart', 'Gosick');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Pamella Pattingson', 'No Game, No Life Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Far Scarasbrick', 'One Punch Man');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sanders Kellar', 'Lupin III: The Castle of Cagliostro');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eustacia Orhtmann', 'Aria the Avvenire');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Berkie Blackett', 'Welcome to THE SPACE SHOW');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ilaire Mac', 'Denpa teki na Kanojo');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Zia Leat', 'Monthly Girls Nozaki-kun');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Moyna Mapledoram', 'Nobodys Boy Remi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Johnathan Lumby', 'Elfen Lied');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Valery Synder', 'Emma: A Victorian Romance Second Act');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lin Fuster', 'Kizumonogatari Part : Reiketsu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Boonie Blodgetts', 'My Hero Academia');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gareth Miranda', 'Rainbow - Nisha Rokubo no Shichinin');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mick Lovel', 'Wolfs Rain');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Abagail Haughan', 'No Game, No Life');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wheeler Ixer', 'Ghost in the Shell: Stand Alone Complex - The Laughing Man');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ned Sanbrook', 'Magical Girl Lyrical Nanoha the Movie nd As');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jerrie Mundall', 'Junjo Romantica');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marwin Tudbald', 'Tokyo Magnitude .');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Catriona Rebichon', 'Eureka Seven');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jackquelin Crush', 'School Rumble');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Edgardo Becraft', 'Parasyte -the maxim-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Fulvia Cassidy', 'Hinamatsuri');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lanette Pestricke', 'Kizumonogatari Part : Nekketsu (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bev Petrelli', 'Kill la Kill');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Vernice McEachern', 'Ghost in the Shell (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carey Whitehair', 'Puella Magi Madoka Magica the Movie Part : Eternal');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lucas Masselin', 'Now and Then, Here and There');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Timi Castilla', 'Berserk: The Golden Age Arc II - The Battle for Doldrey (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gayla Cleere', 'Puella Magi Madoka Magica the Movie Part : Beginnings');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carol-jean Budnik', 'Kizumonogatari Part : Tekketsu (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Reamonn Turnor', 'Wagnaria!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mackenzie Rohmer', 'Kimagure Orange Road: The Movie');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ranice Waplinton', 'Lovely Complex');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carlynn Perview', 'Porco Rosso (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Faith Landsberg', '(The) Place Promised in Our Early Days (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Murdoch Tembridge', 'Hikaru No Go: New Year Special');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Karylin Trent', 'planetarian: Hoshi no Hito (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ruy McDool', 'Mobile Suit Gundam - The Movie Trilogy');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rosita Kenelin', 'Hajime no Ippo - Mashiba vs. Kimura');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Raimundo Sturney', 'Puella Magi Madoka Magica The Movie Part : Rebellion');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nikolai Dowe', 'Cardcaptor Sakura Movie : The Sealed Card');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Irvin Dugget', '(The) Wind Rises (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Barrett Conradie', 'Legend of the Galactic Heroes: A Hundred Billion Stars, A Hundred Billion Lights');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Val Rickman', 'Detroit Metal City');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kerry Burder', '(The) Slayers Next');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ruthann Ganforthe', 'One Piece Film Strong World (movie )');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bradley Hayller', 'Strawberry Panic!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Geri Renzini', 'KenIchi the Mightiest Disciple');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gilles Ferrarotti', 'Princess Jellyfish');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rori Mates', 'Bamboo Blade');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wandis Andri', 'Initial D: Fourth Stage');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Agosto Jordine', 'Mobile Suit Gundam');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aurea Winsbury', 'Owarimonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Connie Brower', 'Bakuman.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Doretta Martineau', 'Silver Spoon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Constantino Fitzhenry', 'Hikaru no Go');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Clayborne Larenson', 'ReLIFE');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Holmes Antham', 'Hajime no Ippo Rising');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Noby Seeviour', 'Banner of the Stars II');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Demetris Roz', 'Higurashi no Naku Koroni Kai');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Winn Burcombe', 'Gunbuster');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Clifford Queree', 'ReLIFE');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Martainn Merali', 'Food Wars! The Second Plate');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kai Stempe', 'Case Closed: The Phantom of Baker Street (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Benito Creavan', 'Samurai');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eldridge Dukes', 'Voices of a Distant Star');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bronny Wissbey', 'lam Dunk');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Emlen Baumaier', 'Doraemon the Movie: Nobita and the Steel Troops: The New Age');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Roderic Burtonwood', '(The) Ancient Magus Bride');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Glori Fayter', 'Full Moon o Sagashite');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aldridge Chelsom', 'Miss Kobayashis Dragon Maid');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jean Maddocks', 'A Lull in the Sea');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jaimie Bernholt', 'Mobile Suit Zeta Gundam');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Catherina Banasevich', 'Psycho-Pass');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Beulah Gaynesford', 'Sayonara, Zetsubou-Sensei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Coleman Manass', '(The) Story of Saiunkoku Second Series');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jesse Salthouse', 'FLCL');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rheta Longbone', 'Treasure Island');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Crystie Drillingcourt', 'Case Closed: Captured in Her Eyes (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Myron Gustus', 'Case Closed: The Last Magician of the Century (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Valerye Ricart', '(The) Secret World of Arrietty (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Merry Nappin', 'Genshiken');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mandel Wogden', 'Touch (TV)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gunar Berrecloth', 'Kyo kara Maoh! rd Series');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tiebout Meiklem', 'Black Lagoon: Robertas Blood Trail');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wyndham Keinrat', 'Log Horizon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jamey Mouget', 'Genshiken');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Emmanuel Igoe', 'Big Windup! Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mirna Izzatt', 'Case Closed: Countdown to Heaven (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dmitri Pratley', 'Kaleido Star: Legend of Phoenix - Layla Hamilton Story');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gan Beartup', 'Saint Seiya: The Hades Chapter - Sanctuary');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jordan Valerius', 'Junjo Romantica');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Charita Akrigg', 'Aria - The Natural');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Berkeley Dawnay', 'Claymore');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eberto Kloster', 'Zoku Sayonara Zetsubo Sensei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Myron Powys', 'Giant Robo');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hanna McClaren', 'Legend of the Galactic Heroes: Spiral Labyrinth');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bobina Deluce', 'Nisemonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kathrine Hartburn', 'Ace of Diamond: Second Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ermin Worlock', '(The) Garden of Sinners/recalled out summer (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Benn Grimsdike', 'Non Non Biyori Repeat');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Luther Giron', 'Fruits Basket');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Greg Crate', 'From Up On Poppy Hill (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rockey Mawhinney', 'Perfect Blue (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Adolph Harkes', 'When They Cry - Higurashi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kristian Blankley', 'Kimagure Orange Road');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carley Schruur', 'Birdy the Mighty Decode:');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ted Pettis', 'Penguindrum');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lebbie Cassedy', 'Soul Eater');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Asa Berringer', 'Full Metal Panic!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bronnie Caizley', 'Hanada Shonen-shi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Iolande Cowlard', 'Hare+Guu Deluxe');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Florentia Summerly', 'Baby Blue (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Glen Maystone', 'xxxHOLiC: Ro');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hermina Murrhaupt', 'Emma: A Victorian Romance');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dulcie Dufer', 'Macross Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tiphany Dietmar', 'Space Battleship Yamato');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wendy Goodison', 'Fairy Tail Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Robyn Fligg', 'Mobile Suit Gundam: The Origin');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Vlad Chittenden', 'One Piece DY Ace no Shi wo Koete! Luffy Nakama to no Chikai');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Alon Newton', 'Chihayafuru');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lombard Lednor', '(The) Tatami Galaxy');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jacky Totman', 'Tamayura: Sotsugyo Shashin (movie series)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ernestine Leat', '(The) Vision of Escaflowne');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Stillmann Hue', 'Mobile Suit Gundam: Iron-Blooded Orphans');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dorelia Du Plantier', 'Magical Girl Lyrical Nanoha As');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Danice Stivey', 'Black Butler: Book of Murder');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sharleen Pessolt', '(The) Eccentric Family (TV)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Car Romanini', 'Read or Die');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Honor Titcomb', 'Durarara!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Myrle MacGlory', 'Broken Blade (movie series)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Johann Turnpenny', 'Yu Yu Hakusho: Ghost Files');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marina Penreth', 'Fate/stay night: Unlimited Blade Works');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Andrew Angear', 'Ga-Rei-Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jason Chupin', 'Macross Plus Movie Edition');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Suzie Crinson', 'Kaiji');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wadsworth Carefull', 'Gintama Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hussein Bartrum', 'Tsubasa: Spring Thunder');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Clerc Kirby', '(The) Story of Saiunkoku');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cristie Linley', 'Crest of the Stars');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ronni Hebblethwaite', 'On Your Mark (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Augustine Ligertwood', 'Urusei Yatsura: Beautiful Dreamer (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jewel Matousek', 'Gintama');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Windy Scipsey', 'Hanamonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ferrell Hutton', 'KONOSUBA - Gods blessing on this wonderful world!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Merralee Shrimptone', 'Toward the Terra');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Erie Gotcher', 'Mind Game (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ransom Mulvin', 'Genshiken');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Corny Crossfeld', 'Mobile Suit Gundam Seed');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Renaud Bortolazzi', 'Goku Sayonara Zetsubo Sensei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nonie Jerzyk', 'Daicon films (special)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lonny Santos', 'One Piece Film Z (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Paulina Hembrow', 'Baby Steps');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Maurine McCarver', 'City Hunter');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Alfi Bracco', 'Redline (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Edvard Pantridge', 'Big Windup!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nevins Flecknoe', 'Saga of Tanya the Evil');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jarid Hunte', 'Initial D: Second Stage');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Levi Gentile', 'K-ON! (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Perceval Di Biasio', 'InuYasha: The Final Act');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Patrick Graves', 'Jormungand Perfect Order');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Isidro Fehely', '(The) Dog of Flanders (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shandeigh Widdison', 'Maho Sensei Negima!: Mo Hitotsu no Sekai (OAV)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nicol Calcutt', 'Gintama: The Movie');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dulcea Toogood', '(The) Disastrous Life of Saiki K.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mariette Wornum', 'Lunar Legend Tsukihime');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Danita Winsiowiecki', 'Zan Sayonara Zetsubo Sensei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Perla Faccini', 'Rurouni Kenshin: Reflection');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Garth Reddihough', 'Hanasaku Iroha: Home Sweet Home (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mack Oxbury', 'Aggressive Retsuko');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Linette Puttick', 'Fate/stay night: Heavens Feel I. presage flower (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Moria Gunther', 'Kurenai');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nanine Bithany', 'Steins;Gate: The Movie - Load Region of Dejà Vu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kaylyn Okill', 'Kyousougiga');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dulcea Clitheroe', 'Girls Last Tour');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Laughton Remnant', 'Barakamon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Camilla Dunk', '(The) Irresponsible Captain Tylor');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lionel OBeirne', 'Death Parade');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Filide Gandley', 'Detective Conan: The Lost Ship in The Sky (movie )');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dixie Stonhard', 'Patema Inverted (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Melisenda Normanvill', 'Banner of the Stars');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marti Passie', 'Yona of the Dawn');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Adelle Blind', 'Revolutionary Girl Utena');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aluin Jessard', 'Hidamari Sketch × Honeycomb');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kimberley Ruffler', 'Wagnaria!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ossie Baldin', 'Barefoot Gen (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hadley Jesson', 'Children Who Chase Lost Voices');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Maxie Burgin', 'Case Closed: The Fourteenth Target');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Merrel Frediani', 'Ghost in the Shell S.A.C. Solid State Society D');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mellisa Bohike', 'My-HiME');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rosalinde Langdale', 'Natsume Yujin-Cho: Itsuka Yuki no Hi ni');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Atlante True', 'Sound! Euphonium');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Perceval Hierro', 'Hozukis Coolheadedness');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sully Fallanche', 'One Piece');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dorita Drysdall', 'Shigofumi - Letters from the Departed');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gaston Francis', 'Trigun: Badlands Rumble');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Alexia Crossfield', 'Hidamari Sketch × Hoshimittsu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jessica Madgwich', 'INTERSTELLA : The tory of the ecret tar ystem');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kaye Ribou', 'Silver Spoon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carney Barnett', 'Lucky Star');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Guendolen Giannotti', 'Tsukimonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Fair Iacovaccio', 'RahXephon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Billie Fitzsimon', 'My Teen Romantic Comedy SNAFU TOO!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Keane Khomich', 'Laid-Back Camp');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Analiese Maudlin', 'Gurren Lagann the Movie –Childhoods End-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Graehme Kubicek', 'Tsukigakirei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Titos Maine', 'His and Her Circumstances');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Florida Baggiani', '(The) Seven Deadly Sins: Revival of The Commandments');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kevin Gair', 'Vampire Hunter D: Bloodlust');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wendi Swettenham', 'Kobato.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Alicea Moggach', 'Berserk: The Golden Age Arc I - The Egg of the King');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Adella Bownass', 'Doukyusei -Classmates-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bord Strahan', 'House of Five Leaves');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Stacee Vaillant', 'School Rumble: Extra Class');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Fairfax Gleadhall', 'Nekomonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Port Dumbell', 'Glass Mask');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Liam Friary', '(The) Ancient Magus Bride: Those Awaiting a Star');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Laurence Phillp', 'My Love Story!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Catharina Gronow', 'Ergo Proxy');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kynthia Wahlberg', 'Ghost in the Shell: Arise');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Andrei Sprott', 'Tenchi Muyo! Ryo-Ohki');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shanna Stoven', 'Love, Chunibyo y  Other Delusions!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Niko Tinsley', 'Strawberry Marshmallow');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kristine Swadden', 'Initial D: Third Stage (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carlota McCord', 'Master Keaton');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jessa Struijs', 'Banner of the Stars III');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mead Hughman', 'Attack on Titan: No Regrets');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marillin Bryning', 'Final Fantasy VII: Advent Children');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Allister Morrallee', 'Attack on Titan');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Onida Pollins', 'Fullmetal Alchemist: The Movie - Conqueror of Shamballa');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bee Longfoot', 'Macross Plus');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hillyer Ayce', 'Hayate the Combat Butler!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hakim Younie', 'Daily Lives of High School Boys');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aurore Sparks', 'Hyoka');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Brok Noblett', 'Hidamari Sketch: Sae/Hiro Sotsugyo-hen');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cecilio Riatt', 'Tekkonkinkreet');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Melva Drakard', 'Initial D: Final Stage');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gideon Findlay', 'Food Wars! The Third Plate');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cam Rothon', 'Tari Tari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Michaela Geale', 'Detective Conan: The Private Eyes Requiem');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Moreen Janicek', 'Moshidora');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dannie Pick', 'Shakugan no Shana');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jojo Yoxall', 'A Letter to Momo');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Margaux Estable', 'Rage of Bahamut: Genesis');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mignon Frankton', 'Little Witch Academia');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Arleyne Coffelt', '(The) Cat Returns');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nolan Gristock', 'xxxHOLiC: Shunmuki');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Izabel Yeatman', 'xxxHOLiC: Ro Adayume');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Irvine Chewter', 'Kinos Travels: Life Goes On');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Titos MacKartan', 'Mobile Suit Gundam: The th MS Team');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jasun Secret', 'Heartcatch Precure! Hana no Miyako de Fashion Show…Desu ka!?');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Patti Allchorn', 'Sword Art Online the Movie: Ordinal Scale');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Allin Pocknell', 'JoJos Bizarre Adventure: Stardust Crusaders Egypt Arc');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Randy Veart', 'Kamichu!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Devina O Timony', 'Hidamari Sketch × Hoshimittsu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Virgilio Champneys', 'GATE');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Perice Domel', 'Noein - to your other self');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nye Messent', 'Seto no Hanayome');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gare Ambrus', 'Hozuki no Reitetsu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Celestina Huntly', 'Scrapped Princess');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Granger Fleis', 'Ushio y  Tora');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sonny Deane', 'Shonen Onmyouji');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Crystal Burnall', 'Food Wars! The Third Plate');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ellen Itscovitz', 'Zan Sayonara Zetsubo Sensei Bangai-chi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ringo McGinly', 'Tiger y  Bunny The Movie -The Rising-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Filbert Moller', 'White Album');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ursulina Kyle', 'Full Metal Panic! The Second Raid');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Fabian Labusquiere', 'Tenchi Muyo! War on Geminar');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jarred Grinaway', 'Hidamari Sketch ×');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Drucill Parnaby', 'Queen Millennia');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sully Ralton', 'Megalobox');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Josefa Galia', 'Gunslinger Girl');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Baxie Waterhowse', '(The) Disastrous Life of Saiki K.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Elfrieda Martinets', 'Inuyashiki Last Hero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Vinita Dolligon', 'Colorful');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Loutitia Braban', 'Detective Conan: The Raven Chaser');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Vincent Kedslie', 'Another');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Woody Screen', 'Giovannis Island');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Joseph Ferriby', 'Planetarian');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Binny Burchnall', 'Full Metal Panic! Invisible Victory');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cesya Itzkovwitch', 'Akira');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marice Fredson', 'Blood+');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Callean Linder', 'Waiting in the Summer');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Stacia Gostyke', 'Strawberry Marshmallow');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Paco Fawcett', 'Fullmetal Alchemist: Brotherhood');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lyda Tumber', 'Case Closed The Movie: The Time Bombed Skyscraper');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Janna Baldwin', 'Hi Score Girl');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Colene Kittoe', 'From the New World');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Daniel Kovelmann', 'Aria the Animation');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Annie Stockman', 'Detective Conan: Magician of the Silver Sky');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kelvin Bicksteth', 'Macross Frontier: Itsuwari no Utahime');

INSERT INTO personajes(nombre, nombreanime) VALUES ('Akane Higurashi' , 'Cinderella Girls Gekijou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumilidon' , 'Keppeki Danshi Aoyama-Kun');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Merlin (personaje de Nanatsu no Taizai)' , 'Aldnoah.Zero');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Merlin (personaje de Nanatsu no Taizai)' , 'Hanebado');
INSERT INTO personajes(nombre, nombreanime) VALUES ('El hombre que ríe (personaje)' , 'Hina Logic: From Luck y Logic');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Fly (Dragon Quest)' , 'Brave Witches');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yoichi Hiruma' , 'Shouwa Genroku Rakugo Shinjuu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shizuru Fujino' , 'Sieshun Buta Yarou wa Bunny Girl-senpai no Yume wo Minai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Heidi (personaje)' , 'Tales of Zestiria The X');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ninja Hattori' , 'Owarimonogatari Segunda temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yoshikage Kira' , 'Tenrou: Sirius the Jaeger');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jotaro Kujo' , 'Hinamatsuri');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Norakuro' , 'Ore Tachi ni Tsubasa wa Nai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Usagi Tsukino' , 'Touken Ranbu: Hanamaru');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Astroboy' , 'Fairy Tail (2014)');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kyatto Ninden Teyandee' , 'Urara Meirochou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MS903 Doraemon' , 'Ebiten: Kouritsu Ebisugawa Koukou Tenmonbu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ichiro Miyata' , 'Nobunaga no Shinobi: Ise Kanegasaki-Hen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Astroboy' , 'Ojisan to Marshmallow');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tochiro Oyama' , 'Grisaia no Rakuen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dio Brando' , 'Saredo Tsumibito wa Ryuu to Odoru');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sekai Saionji' , 'Jojo no Kimyou na Bouken: Diamond wa Kudakenai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mikan Sakura' , 'Grisaia no Kajitsu Especiales');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yoichi Hiruma' , 'Hatsukoi Monster');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hitomi Kanzaki' , 'To Love ru Darkness 2nd Sin Censura');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ichiro Miyata' , 'Denpa Kyoushi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Príncipe Planeta' , 'Flying Witch');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Usagi Tsukino' , 'Pokemon Sun y Moon');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MS903 Doraemon' , 'Imouto Sae Ireba Li');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kimihiro Watanuki' , 'Aquarion Logos');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Itsuki Koizumi' , 'Days');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yui Kasuga' , 'Kagewani');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kimihiro Watanuki' , 'Sieshun Buta Yarou wa Bunny Girl-senpai no Yume wo Minai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Eikichi Onizuka' , 'Gakusen Toshi Asterisk 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dio Brando' , 'Nyanko Days');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mariah (JoJos)' , 'Super Lovers 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ojiro Mihara' , 'Cardcaptor Sakura: Clear Card-Hen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hokuto Sumeragi' , 'Shinmai Maou no Testament Burst sin censura');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Usagi Tsukino' , 'Zoku Touken Ranbu: Hanamaru');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hare (personaje)' , 'Just Because!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kimihiro Watanuki' , 'Bishoujo Yuugi Unit Crane Game Girls Galaxy');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mariah (JoJos)' , 'Grand Blue');
INSERT INTO personajes(nombre, nombreanime) VALUES ('La abeja Maya' , 'Idol Memories');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ban Mido' , 'Piano no Mori (tv)');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Relena Darlian' , 'Akkun to Kanojo');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kyatto Ninden Teyandee' , 'Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yui Kasuga' , 'Sakurako-san Ashimoto ni Wa Shitai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Anexo:Personajes de Shin-chan' , 'Tada-kun wa Koi wo Shinai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kai Hiwatari' , 'Tales of Zestiria The X (2017)');
INSERT INTO personajes(nombre, nombreanime) VALUES ('La abeja Maya' , 'Akkun to Kanojo');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Makoto Ito' , 'Dungeon ni Deai wo Motomeru no Wa Machigatte iru Darou ka');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MS903 Doraemon' , 'Hataraku Saibou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Cho Hakkai' , 'Pokemon Sun y Moon');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hatoko Kobayashi' , 'Punchline');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Motoko Kusanagi' , '25-Sai no Joshikousei');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Grosser' , 'Nazotokine');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shizuru Fujino' , 'Sakurada Reset');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jean Pierre Polnareff' , 'Long Riders!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kiteretsu' , 'Ballroom e Youkoso');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vickie el vikingo' , 'Tsukipro The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ninja Hattori' , 'High School DxD Born Especiales');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kaiketsu Zorori' , 'Imouto Sae Ireba Li');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Noriaki Kakyoin' , 'Sidonia no Kishi Segunda Temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('OS-tan' , 'Sidonia no Kishi Segunda Temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MegaMan.EXE' , 'Amaama to Inazuma');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Genjo Sanzo' , 'Netoge no Yome wa Onnanoko Ja Nai to Omotta');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumeragi Subaru' , 'Yama no Susume 3');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Eikichi Onizuka' , 'Tada-kun wa Koi wo Shinai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vash' , 'Hajimete no Gal');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kaiketsu Zorori' , 'Danganronpa 3: The End Of Kibougamine Gakuen - Zetsubou-Hen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hibari Hanakoganei' , 'Shinryaku! ika Musume');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Itsuki Koizumi' , 'B-Project: Kodou Ambitous');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Genjo Sanzo' , 'Dorei-ku The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hare (personaje)' , 'Centaur no Nayami');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muhammad Avdol' , 'Saiki Kusuo no Psi 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Okuyasu Nijimura' , 'Boruto: Naruto The Movie');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Grosser' , 'Overlord Tercera Temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Makoto Ito' , 'Love Live! Sunshine!!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Joseph Joestar' , 'Ne-Juu no Susume');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Príncipe Planeta' , 'Jojo no Kimyou na Bouken: Diamond wa Kudakenai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Itsuki Koizumi' , 'Tokyo Ghoul Jack OVA');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Genji Kamogawa' , 'Nanatsu no Taizai Seisen no Shirushi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('OS-tan' , 'Mob Psycho 100');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Heidi (personaje)' , 'Busou Shoujo Machiavllianism');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Arale Norimaki' , 'Pokemon XYyZ');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Enma Ai' , 'Idol Jihen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Abuelo de Heidi' , 'Mahou Shoujo lyrical Nanoha Vivid');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muglox' , 'DanMachi: Sword Oratoria');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Gintoki Sakata' , 'Brave Witches');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mikan Sakura' , 'Akame ga Kill!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hitomi Kanzaki' , 'Koi wa Ameagari no You ni');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vickie el vikingo' , 'Action Herione Cheer Fruits');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Relena Darlian' , 'SpiritPact');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Strider Hiryu' , 'YU-GI-OH! GX');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Cyborg 009' , 'Miss Monochrome Animation 3');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Toon' , 'Acca: 13 ku Kansatsu-ka');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jotaro Kujo' , 'Ingress');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Makoto Ito' , 'Zoku Touken Ranbu: Hanamaru');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Gatchaman' , 'Haikyuu Second Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jotaro Kujo' , 'Toaru Majutsu no Index III');
INSERT INTO personajes(nombre, nombreanime) VALUES ('El hombre que ríe (personaje)' , 'Jojo no Kimyou na Bouken: Diamond wa Kudakenai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jungle Taitei' , '12-Sai: Chicchana Mune no Tokimeki');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Capitán Kuro' , 'Juuou Taisen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Metabee' , 'Ushio to Tora (TV) 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tsugumi Higashijujo' , 'Darling in The Franxx');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MS903 Doraemon' , 'Time Travel Shoujo: Mari waka To 8-nin no Kagakusha-Tachi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hol Horse' , 'Ballroom e Youkoso');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kiteretsu' , 'Tales of Zestiria The X (2017)');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tochiro Oyama' , 'Demi-chan wa Kataritai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Calimero' , 'Centaur no Nayami');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Heidi (personaje)' , 'Sengoku Night Blood');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Misaki Suzuhara' , 'Onsen Yousei Hakone-chan');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Genjo Sanzo' , 'Layton Mystery tanteish: Katori no Nazotoki File');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Akira (personaje)' , 'Senki Zesshou Symphogear GX');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hermanas Fujisaki' , 'Fate Zero Temporadas 1 y 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dragonoid' , 'High School DxD Hero');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Misaki Suzuhara' , 'Gakuen Babysitters');
INSERT INTO personajes(nombre, nombreanime) VALUES ('El gato Félix' , 'Charlotte');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yoshikage Kira' , 'Onigiri Anime');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Noriaki Kakyoin' , 'Fudanshi Koukou seikatsu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('El gato Félix' , 'Zero Kara Hajimeru Mahou no Sho');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sakura Kinomoto' , 'Back Street Girls');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yoichi Hiruma' , 'Sakura Card Captor');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hermanas Fujisaki' , 'Island');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Suzume Sakurajosui' , 'Kujira no Kora wa Sajou Utau');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dragonoid' , 'Fushigi na Somera-chan');
INSERT INTO personajes(nombre, nombreanime) VALUES ('El gato Félix' , 'Hataraku Saibou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Enma Ai' , 'Long Riders!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Katsura Kotonoha' , 'Jojo no Kimyou na Bouken: Diamond wa Kudakenai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ninja Hattori' , 'Inazuma Eleven Ares no Tenbin');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muglox' , 'Sangatsu no Lion Segunda temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mariah (JoJos)' , 'Osake wa Fuufu ni Natte Kara');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Joseph Joestar' , 'Nisekoi Ovas');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tamayo Kisaki' , 'Gintama Shinyaku Benizakura-hen Special');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Cyborg 009' , 'Boku no Hero Academia 2nd Season 2017');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ippo Makunouchi' , 'Gakkou Gurashi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vickie el vikingo' , 'Juushinki Pandora');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumeragi Subaru' , 'Nanatsu no Taizai Seisen no Shirushi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Misaki Suzuhara' , 'Basilisk: Ouka Ninpouchou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shugo Kunisaki' , 'Shinmai Maou no Testament sin censura');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vash' , 'Samurai Jack Season 5');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Gintoki Sakata' , 'Kill la Kill');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dragonoid' , 'Inuyashiki');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Usagi Tsukino' , 'Ongaku Shoujo (TV)');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jasmine y Meddy' , 'Yuru Camp');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Eiichi Kite' , 'Shirobako');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumeragi Subaru' , 'Hanebado');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Metabee' , 'Gabriel DropOut');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Abuelo de Heidi' , 'Tengen Toppa Gurren Lagann');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Natsume Hyuga' , 'Grisaia no Mekyuu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mai Tokiha' , 'Fate/stay night: Unlimited Blade Works');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hello Kitty' , 'Nobunaga no Shinobi: Ise Kanegasaki-Hen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ojiro Mihara' , 'Just Because!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Motoko Kusanagi' , 'Hitoijime my Hero');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Strider Hiryu' , 'RErideD: Koku Koe no Derrida');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumilidon' , 'Sailor Moon crystal: death Busters-Hen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('La pequeña Lulú' , 'Mahou Shoujo Ikusei Keikaku');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Heidi (personaje)' , 'WWW.Working!!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Motoko Kusanagi' , 'Tsukipro The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumeragi Subaru' , 'Satsuriku no Tenshi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ban Mido' , 'Ore Monogatari!!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('La pequeña Lulú' , 'Sidonia no Kishi Segunda Temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jonathan Joestar' , 'To Love ru Darkness Sin Censura');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vash' , 'Gakusen Toshi Asterisk 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shuko Suzuhara' , 'Killing Bites');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hatoko Kobayashi' , 'Mahou Shoujo Nante Mou II Desukara 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ryo Mashiba' , 'Gin no Guardian 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yuko Ichihara' , 'Joukamachi no Dandelion');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Takumi Tokiha' , 'Active Raid');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Fly (Dragon Quest)' , 'Long Riders!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Eikichi Onizuka' , 'Sora Yori mo Tooi Basho');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kyatto Ninden Teyandee' , 'GrandBlue Fantasy');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Metabee' , 'Ulysses: Jeanne d Arc to Renkin no Kishi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hitomi Kanzaki' , 'Fate/stay night');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Boogiepop (personaje)' , 'Jojo no Kimyou na Bouken: Ougon no Kaze');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MS903 Doraemon' , 'Fate/stay night');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ninja Hattori' , 'Planetarian: Chiisana Hoshi no Yume');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muhammad Avdol' , 'Fate Zero Temporadas 1 y 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Misaki Suzuhara' , 'Cinderella Girls Gekijou Tercera Temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Príncipe Planeta' , 'Lupin III: Part V');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Nao Yuuki' , 'Kokoro Connect');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kaede Saito' , 'Uchuu Senkan Tiramisu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Momoko Hanasaki' , 'Tonari no Kyuuketsuki-san');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sai Jonouchi' , 'Taimadou Gakuen 35 Shiken Shoutai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dio Brando' , 'Nana Maru San Batsu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumeragi Subaru' , 'Hellsing');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hitomi Kanzaki' , 'Mayoiga');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yuko Ichihara' , 'Grisaia no Mekyuu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumilidon' , 'Gegege no Kitarou (2018)');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kimihiro Watanuki' , 'Sousei no Onmyouji');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mariah (JoJos)' , 'Nagato Yuki Chan No Shoushitsu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Cyborg 009' , 'HaiFuri');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ichiro Miyata' , 'Fukigen na Mononokean');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Grosser' , 'Tokyo Ghoul:re');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vickie el vikingo' , 'Ozmafia');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ichiro Miyata' , 'Kino no Tabi: Beautiful - The Animated Series');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kaiketsu Zorori' , 'Taimadou Gakuen 35 Shiken Shoutai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ban Mido' , 'Shinryaku! ika Musume');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ricardo Espadas' , 'Knights y Magic');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Itsuki Koizumi' , 'Nobunaga no Shinobi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vickie el vikingo' , 'High School DxD Born');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mireille Bouquet' , 'Uta no Prince-Sama MAji Love Legend Star');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muhammad Avdol' , 'Girlish Number');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Genji Kamogawa' , 'Shokugeki no Souma: Ni no Sara');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Gorem' , '25-Sai no Joshikousei');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Haruka Suzushiro' , 'Saint Seiya: Soul of Gould');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Allen Walker' , 'Ame iro Cocoa Rainy color e Youkoso');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Neuro Nogami' , 'Fate/Kaleid Liner Prisma Illya 3Rei!!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MegaMan.EXE' , 'Lostorage Incited Wixoss');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Natsumi Tsujimoto' , 'Grisaia no Mekyuu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Haruhi Suzumiya' , 'Occultic;Nine');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Natsumi Tsujimoto' , 'Mahou Shoujo Ikusei Keikaku');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Misaki Suzuhara' , 'Mahou Shoujo lyrical Nanoha Vivid');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vickie el vikingo' , 'Deadman Wonderlan');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kaiketsu Zorori' , '18if');
INSERT INTO personajes(nombre, nombreanime) VALUES ('El gato Félix' , 'MomoKuri');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Arale Norimaki' , 'Gakkou Gurashi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumeragi Subaru' , 'Knights y Magic');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Strider Hiryu' , 'Berserk (2017)');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Enma Ai' , 'Kuroko no Basuke');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Momoko Hanasaki' , 'Chaos Dragon Sekiryuu Seneki');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kotaro Kobayashi' , 'Endride');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Calimero' , 'Mitsuboshi Colors');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yui Kasuga' , 'Deadman Wonderlan');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shugo Kunisaki' , 'Ao no Exorcist: Kyoto Fujouou-Hen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dio Brando' , 'Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yui Kasuga' , 'Dragon Ball Z:Fukatsu no F');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shugo Kunisaki' , 'Haikyuu Second Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kotaro Kobayashi' , 'Tokyo Ghoul:re');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MegaMan.EXE' , 'Golden Kamuy');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Batou' , 'Boku no Kanojo ga Majime Sugiru Shoujo Bitch na Ken');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tamayo Kisaki' , 'Ore Monogatari!!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Misaki Suzuhara' , 'Concrete Revolution Choujin Gensou - The Last Song');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dragonoid' , 'Koufuku Graffiti');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Noriaki Kakyoin' , 'Working!!! 3');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Suzume Sakurajosui' , 'Bernard-Jou Iwaku');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yuko Ichihara' , 'Alternativa FLCL');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muglox' , 'High School DxD Born Especiales');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kyon' , 'Terra Formars Revenge');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Merlin (personaje de Nanatsu no Taizai)' , 'Ore Tachi ni Tsubasa wa Nai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jasmine y Meddy' , 'Dorei-ku The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Makoto Ito' , 'Mayoiga');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Toon' , 'Hatsukoi Monster');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kazuto Kirigaya' , 'Naruto Shippuden Latino');
INSERT INTO personajes(nombre, nombreanime) VALUES ('El gato Félix' , 'Lance N Masques');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jungle Taitei' , 'MahouTsukai No Yome');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shuko Suzuhara' , 'Nejimaki Seirei Senki: Tenkyou no Alderamin');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Batou' , 'Rakudai Kishi no Cavalry');
INSERT INTO personajes(nombre, nombreanime) VALUES ('El hombre que ríe (personaje)' , 'Kokkoku');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hatoko Kobayashi' , 'Tenrou: Sirius the Jaeger');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hokuto Sumeragi' , 'Seikaisuru Kado');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ban Mido' , 'Danganronpa 3: The End Of Kibougamine Gakuen - Zetsubou-Hen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hibari Hanakoganei' , 'Saenai Heroine no Sodatekata');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ichiro Mihara' , 'Alternativa FLCL');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hatoko Kobayashi' , 'Hidan no Aria AA');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Toon' , 'Ryuuou no Oshigoto');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Iggy (JoJos)' , 'Tsurezure Children');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Lisa Lisa (JoJos)' , 'Natsume Yuujinchou Go');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kiteretsu' , 'Itsudatte Bokura no koi wa 10 Cm Datta');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ippo Makunouchi' , 'Netoge no Yome wa Onnanoko Ja Nai to Omotta');
INSERT INTO personajes(nombre, nombreanime) VALUES ('La abeja Maya' , 'Megalo Box');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Allen Walker' , 'Tanaka-kun wa Itsumo Kedaruge');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumeragi Subaru' , 'Regalia: The Three Sacred Stars');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Okuyasu Nijimura' , 'Gin no Guardian 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kimihiro Watanuki' , 'Berserk (2017)');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Usuario:VictiniLikeWaffles/Taller' , 'One Punch Man');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hideki Motosuwa' , 'Koufuku Graffiti');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hibari Hanakoganei' , 'Eldlive');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Cho Hakkai' , 'Chaos Dragon Sekiryuu Seneki');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hermanas Fujisaki' , 'Bubuki Buranki');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hibari Hanakoganei' , 'Bubuki Buranki: Hoshi no Kyojin');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MS903 Doraemon' , 'Nil Admirari no Tenbin');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jotaro Kujo' , 'Tantei Team Kz Jiken Note');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Boogiepop (personaje)' , 'K: Return of Kings');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Haruka Suzushiro' , 'Dog Days');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shizuka Domeki' , 'Sansha Sanyou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yoshikage Kira' , 'Shingeki no Kyojin: Chuugakkou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Norakuro' , 'ME!ME!ME!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Khyron' , 'Ore Monogatari!!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vickie el vikingo' , 'Hataraku Saibou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kimihiro Watanuki' , 'Macross Delta');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Gorem' , 'Time Travel Shoujo: Mari waka To 8-nin no Kagakusha-Tachi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muglox' , 'Gintama (Shinsaku)');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jean Pierre Polnareff' , 'Yuru Yuri Nachuyachumi Plus');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Boogiepop (personaje)' , 'Tsukipro The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tochiro Oyama' , 'Aho Girl');
INSERT INTO personajes(nombre, nombreanime) VALUES ('La pequeña Lulú' , 'Bang Dream!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Norakuro' , 'Itsudatte Bokura no koi wa 10 Cm Datta');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Relena Darlian' , 'Basilisk: Ouka Ninpouchou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mamoru Takamura' , 'Masou Gakuen HxH Sin Censura');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jotaro Kujo' , 'Seiren');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kyatto Ninden Teyandee' , 'Kimi ni Todoke');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Heidi (personaje)' , 'Durarara!! x2 Ten');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sekai Saionji' , 'ReLIFE Kanketsu-hen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Abuelo de Heidi' , 'Kino no Tabi: Beautiful - The Animated Series');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hideki Motosuwa' , 'Show by Rock!! #');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Takumi Tokiha' , 'MomoKuri');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Allen Walker' , 'Yoru no Yatterman');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Rohan Kishibe' , 'Joukamachi no Dandelion');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shizuru Fujino' , 'Youjo Senki');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Genjo Sanzo' , 'Noragami Aragato');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sai Jonouchi' , 'Inuyashiki');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jotaro Kujo' , 'Omamori Himari!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Katsura Kotonoha' , 'RErideD: Koku Koe no Derrida');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Khyron' , 'Himouto Umaru-chan R (Segunda Temporada)');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kamome Sengakuji' , 'Kowabon');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Itsuki Koizumi' , 'Ousama Game The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tokoroten no Suke' , 'Sore ga Seiyuu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Allen Walker' , 'Lord of Vermillion: Guren no Ou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dragonoid' , 'Mahou Shoujo lyrical Nanoha Vivid');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jungle Taitei' , 'Kujira no Kora wa Sajou Utau');
INSERT INTO personajes(nombre, nombreanime) VALUES ('OS-tan' , 'Island');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Skyress' , 'Anne Happy');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jean Pierre Polnareff' , 'Cinderella Girls Gekijou Tercera Temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Natsuki Kuga' , 'Akagami no Shirayuki Hime 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kotaro Kobayashi' , 'Dog Days');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Haruka Suzushiro' , 'Ore Monogatari!!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Toon' , 'Magi: Sinbad no Bouken');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Strider Hiryu' , 'Dagashi Kashi 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kai Hiwatari' , 'RWBY Volumen 4');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hello Kitty' , 'Boku no Kanojo ga Majime Sugiru Shoujo Bitch na Ken');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Genjo Sanzo' , 'Bishoujo Yuugi Unit Crane Game Girls');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vash' , 'Katsugeki/Touken Ranbu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Natsume Hyuga' , 'To Love ru Darkness Sin Censura');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Okuyasu Nijimura' , 'Ousama Game The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MegaMan.EXE' , 'Tanaka-kun wa Itsumo Kedaruge');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jonathan Joestar' , 'Magi: Sinbad no Bouken');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Haruhi Suzumiya' , 'Minami Kamakura Koukou Joshi Jitensha-Bu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Momoko Hanasaki' , 'Youkai Apartment no Yuuga na Nichijou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Batou' , 'Saiki Kusuo no Psi 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hokuto Sumeragi' , 'Persona 5 The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Guu' , 'Sword Art Online Alternative: Gun Gale Online');
INSERT INTO personajes(nombre, nombreanime) VALUES ('My Melody' , 'Watashi ga Motete Dousunda');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kai Hiwatari' , 'Beatles');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Grosser' , 'Killing Bites');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Arale Norimaki' , 'Kimi ni Todoke 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Eikichi Onizuka' , 'Yamada-kun to 7-nin no Majo');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Arale Norimaki' , 'Watashi ga Motete Dousunda');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Lisa Lisa (JoJos)' , 'Persona 5 The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Eichi Sakurai' , 'Hakumei to Mikochi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hermanas Fujisaki' , 'Tsuki ga Kirei');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kaiketsu Zorori' , 'Nobunaga no Shinobi: Ise Kanegasaki-Hen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hermanas Fujisaki' , 'Houseki no Kuni');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Guu' , 'Urahara');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jotaro Kujo' , 'Senki Zesshou Symphogear G');
INSERT INTO personajes(nombre, nombreanime) VALUES ('DArtacán y los tres mosqueperros' , 'Steins;Gate: Kyoukaimenjou no Missing Link');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Haruka Suzushiro' , 'Persona 5 The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kaiketsu Zorori' , 'Kiseijuu sei no Kakuritsu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yoichi Hiruma' , 'Hyakka Ryouran Samurai Bride S2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Iggy (JoJos)' , 'Grisaia no Rakuen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shizuka Domeki' , 'RWBY Volumen 4');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Max Tate' , 'Tokyo Ghoul:re');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Motoko Kusanagi' , 'Natsume Yuujinchou Go');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Enma Ai' , 'Bungou Stray Dogs 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Louise Françoise le Blanc de la Vallière' , 'Durarara!! x2 Ketsu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Abuelo de Heidi' , 'Frame Arms Girl');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shuko Suzuhara' , 'Orange');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MS903 Doraemon' , 'Punchline');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kai Hiwatari' , 'Killing Bites');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Anexo:Personajes de Shin-chan' , 'Slow Start');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yui Kasuga' , 'High School DxD New');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shizuka Domeki' , 'Tonari no Kyuuketsuki-san');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sekai Saionji' , 'Shimoneta to Iu Gainen ga Sonzai Shinai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Iggy (JoJos)' , 'Tsukipro The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Natsume Hyuga' , 'Devil Line');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Norakuro' , 'Yuuki Yuuna Wa Yuusha de Aru: Washio Sumi no Shou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Capitán Kuro' , 'ReLIFE Kanketsu-hen');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Lisa Lisa (JoJos)' , 'Kuroko no Basuke');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tokoroten no Suke' , 'Uchuu Senkan Tiramisu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mikoto Minagi' , 'Okusama ga Soitokaichou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jean Pierre Polnareff' , 'Dance with Devils');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Arale Norimaki' , 'Haikyuu Second Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shinichi Kudo' , 'Lost Song');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Boogiepop (personaje)' , 'Hinako Note');
INSERT INTO personajes(nombre, nombreanime) VALUES ('La pequeña Lulú' , 'Dorei-ku The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tamayo Kisaki' , 'Tsukipro The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Joseph Joestar' , 'Fukumenkei Noise');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shuko Suzuhara' , 'Taifuu no noruda');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mai Tokiha' , 'Scared Rider Xechs');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumilidon' , 'Pokemon XYyZ');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kiteretsu' , 'Teekyuu 4');
INSERT INTO personajes(nombre, nombreanime) VALUES ('La pequeña Lulú' , 'Flying Witch');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mamoru Takamura' , 'KissXsis');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Iggy (JoJos)' , 'Goblin Slayer');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hello Kitty' , 'Isekai Izakaya: Koto Aitheria no Izakaya Nobi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sekai Saionji' , 'Sansha Sanyou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mariah (JoJos)' , 'Dagashi Kashi 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('El gato Félix' , 'DanMachi: Sword Oratoria');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Katsura Kotonoha' , 'Bungou Stray Dogs');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kaede Saito' , 'Gintama 2015 OVA');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sai Jonouchi' , 'SpiritPact');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Cho Hakkai' , 'Occultic;Nine');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hello Kitty' , 'Isekai wa Smartphone to Tomo ni');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kyatto Ninden Teyandee' , 'Ai Mai Mi: Surgical Friends');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Anexo:Personajes de Shin-chan' , 'Happy sugar life');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hatoko Kobayashi' , 'Super Lovers');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ryo Mashiba' , 'Masou Gakuen HxH Sin Censura');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Makoto Ito' , 'Magi: Sinbad no Bouken');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Relena Darlian' , 'Shigatsu wa Kimi no Uso');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jasmine y Meddy' , 'Magic Kaito 1412');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mikan Sakura' , 'Overlord Segunda Temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Koichi Hirose' , 'Pokemon Sun y Moon');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tala Valkov' , 'Monster Musume sin censura');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Misaki Suzuhara' , 'Isekai Izakaya: Koto Aitheria no Izakaya Nobi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hokuto Sumeragi' , 'Dungeon ni Deai wo Motomeru no Wa Machigatte iru Darou ka');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Cho Hakkai' , 'Ushio to Tora (TV) 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Momoko Hanasaki' , 'Senki Zesshou Symphogear G');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Okuyasu Nijimura' , 'Koi wa Ameagari no You ni');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Relena Darlian' , 'Ore ga Ojousama gakkou ni Shomin Sample');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hello Kitty' , 'Shuumatsu nani Shitemasu ka? Isogashi Desu ka? Sukutte Moratte II Desu Ka?');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Metabee' , 'Natsume Yuujinchou Go');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Cho Hakkai' , 'Fate Zero Temporadas 1 y 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Abuelo de Heidi' , 'Sword Art Online: Alicization');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Takumi Tokiha' , 'Okusama ga Soitokaichou 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Shizuru Fujino' , 'Phantom in the Twilight');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ryo Mashiba' , 'Shinmai Maou no Testament sin censura');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Batou' , 'Durarara!! x2 Ketsu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jasmine y Meddy' , 'Owarimonogatari Segunda temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hideki Motosuwa' , 'Kono Subarashii Sekai ni Shukufuku Wo! 2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mikan Sakura' , 'Shimoneta to Iu Gainen ga Sonzai Shinai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Itsuki Koizumi' , 'Haruchika Haruta to Chika Wa Seishun');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dragonoid' , 'YU-GI-OH! GX');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kazuto Kirigaya' , 'Yami Shibai 6');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hibari Hanakoganei' , 'Active Raid');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tokoroten no Suke' , 'Shinmai Maou no Testament sin censura');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Iggy (JoJos)' , 'Yowamushi Pedal New Generation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Toon' , 'Mahou Shoujo Ikusei Keikaku');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Natsume Hyuga' , 'Boku Dake ga Inai Machi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Eiichi Kite' , 'Lord of Vermillion: Guren no Ou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jotaro Kujo' , 'Zoku Touken Ranbu: Hanamaru');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Strider Hiryu' , 'Pokemon XYyZ');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Cyborg 009' , 'Isuca');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Caesar A. Zeppeli' , 'Hibike! Euphonium');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yoshikage Kira' , 'Hello Kiniro-Mosaic');
INSERT INTO personajes(nombre, nombreanime) VALUES ('La pequeña Lulú' , 'Ingress');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Koichi Hirose' , 'Plastic Nee-san');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Joseph Joestar' , 'Dynamic Chord');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Boogiepop (personaje)' , 'Working!!! 3');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tochiro Oyama' , 'Akibas Trip The Animation');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yuno Gasai' , 'Hanebado');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hokuto Sumeragi' , 'ClockWork Planet');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mikoto Minagi' , 'Satsuriku no Tenshi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jotaro Kujo' , 'Fate/Gran Order Moonlight/Lostroom');
INSERT INTO personajes(nombre, nombreanime) VALUES ('El hombre que ríe (personaje)' , 'Saiyuuki Reload Blast');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Dio Brando' , 'Yagate Kimi ni Naru');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Gintoki Sakata' , 'Shakunetsu no Takkyuu Musume');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Anexo:Personajes de Shin-chan' , 'Hajimete no Gal');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muglox' , 'Free! Dive to the Future');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sekai Saionji' , 'Katsugeki/Touken Ranbu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Grosser' , 'Mitsuboshi Colors');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Itsuki Koizumi' , 'Pokemon XYyZ');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Natsume Hyuga' , 'Tsugumomo');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Nao Yuuki' , 'Nana Maru San Batsu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vash' , 'Emiya-san Chi no Kyou Gohan');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Lan Hikari' , 'Yuru Yuri Nachuyachumi Plus');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Momoko Hanasaki' , 'Akanesasu Shoujo');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MegaMan.EXE' , 'Tachibanakan to Lie Angle');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sai Jonouchi' , 'Magic Kyun! Renaissance');
INSERT INTO personajes(nombre, nombreanime) VALUES ('My Melody' , 'Sangatsu no Lion');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Batou' , 'Working!!! 3');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Misaki Suzuhara' , '12-Sai: Chicchana Mune no Tokimeki 2nd Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jean Pierre Polnareff' , 'Norn9 Norn+Nonet');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Natsume Hyuga' , 'Owarimonogatari');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kai Hiwatari' , 'HaiFuri');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Genjo Sanzo' , 'Bernard-Jou Iwaku');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jasmine y Meddy' , 'Eldlive');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Allen Walker' , 'Tensei Shitara Slime Datta Ken');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Tokoroten no Suke' , 'Imouto Sae Ireba Li');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jungle Taitei' , 'Terra Formars Revenge');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Mikoto Minagi' , 'Another');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sumilidon' , 'Hyakuren no Haou to Seiyaku no Valkyria');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Motoko Kusanagi' , 'Shoujo Tachi wa Kouya wo Mezasu');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Usuario:VictiniLikeWaffles/Taller' , 'Sailor Moon Crystal 2014');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muhammad Avdol' , 'Triage X');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Astroboy' , 'Shuumatsu no Izetta');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Boogiepop (personaje)' , 'Hidan no Aria AA');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yui Kasuga' , 'Heavy Object');
INSERT INTO personajes(nombre, nombreanime) VALUES ('MS903 Doraemon' , 'Comic girs');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hibari Hanakoganei' , 'Gintama 2015 - Cuarta Temporada');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muhammad Avdol' , 'Endride');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Vickie el vikingo' , 'Sakurada Reset');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Muhammad Avdol' , 'Megalo Box');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Grosser' , 'Kyoto Teramachi Sanjou no Holmes');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Yuki Nagato' , 'Tada-kun wa Koi wo Shinai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Haruhi Suzumiya' , 'Jojo no Kimyou na Bouken: Ougon no Kaze');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jonathan Joestar' , 'Ingress');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Boogiepop (personaje)' , 'Diamon no Ace S2');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Ichiro Mihara' , 'Saiki Kusuo no Psi');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Strider Hiryu' , 'Gintama 2017');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Abuelo de Heidi' , 'Sin: Nanatsu no Taizai');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Caesar A. Zeppeli' , 'GATE: JIEITAI KANOCHI NITE');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kazuto Kirigaya' , 'Haikyuu Second Season');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Capitán Kuro' , 'Frame Arms Girl');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Hare (personaje)' , 'Dive!!');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Jonathan Joestar' , 'Tsugumomo');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kazuto Kirigaya' , 'Bishoujo Yuugi Unit Crane Game Girls Galaxy');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Takumi Tokiha' , 'Youkai Apartment no Yuuga na Nichijou');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Kamome Sengakuji' , 'Aki no Kanade');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Sakura Kinomoto' , 'Occultic;Nine');
INSERT INTO personajes(nombre, nombreanime) VALUES ('Lan Hikari' , 'Mikagura Gakuen Kumikyoku');
