INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'your name.');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Fullmetal Alchemist: Brotherhood');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Steins;Gate');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Clannad After Story');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Rurouni Kenshin: Trust y  Betrayal');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Code Geass: Lelouch of the Rebellion R');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Spirited Away');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'A Silent Voice');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Cowboy Bebop');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Mushishi: The Next Chapter');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Disappearance of Haruhi Suzumiya');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Princess Mononoke');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', '(The) Legend of the Galactic Heroes');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Mushi-Shi');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Death Note');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Maria Watches Over Us rd Season');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Made in Abyss');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Maria Watches Over Us Season : Printemps');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Code Geass: Lelouch of the Rebellion');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Gintama');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'anohana: The Flower We Saw That Day');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Descending Stories: Showa Genroku Rakugo Shinju');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Maria Watches Over Us th Season');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Gintama');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Gintama (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Bunny Drop');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Evangelion: . You Can (Not) Advance');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Monster');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Grave of the Fireflies');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Cross Game');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Ghost in the Shell: Stand Alone Complex nd GIG');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Summer Wars');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Fighting Spirit');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Fullmetal Alchemist');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Hunter × Hunter');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Nodame Cantabile');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', '(The) Girl Who Leapt Through Time');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Centimeters Per Second');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Nausicaä of the Valley of the Wind');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Gurren Lagann');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Garden of Sinners');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Wolf Children');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'My Neighbor Totoro');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Baccano!');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Honey and Clover II');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Natsumes Book of Friends');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Gintama: The Final Movie');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hajime no Ippo: New Challenger');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Kanon');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Star Blazers');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'GTO: Great Teacher Onizuka');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Kinos Journey');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Howls Moving Castle');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Time of Eve');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Puella Magi Madoka Magica');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Mushishi Tokubetsu-hen: Hihamukage');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Natsumes Book of Friends');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Millennium Actress');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Time of Eve');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Monogatari Series Second Season');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Kaleido Star');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Mononoke');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Kids on the Slope');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Natsumes Book of Friends');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', '(The) Melancholy of Haruhi Suzumiya');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Gankutsuou: The Count of Monte Cristo');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Clannad');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Planetes');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'NANA');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Looking Up At The Half-Moon');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Castle in the Sky');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Your Lie in April');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Whisper of the Heart');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Samurai Champloo');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Ouran High School Host Club');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'A Place Further Than the Universe');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Gurren Lagann the Movie – The Lights in the Sky Are Stars');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', '(The) Beast Player Erin');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Ghost in the Shell: Stand Alone Complex');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Maria Watches Over Us');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Aria the Origination');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Spice and Wolf II');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Angel Beats!');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Moribito - Guardian of the Spirit');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'March comes in like a lion');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Haikyu!! Second Season');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'My Hero Academia');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'ef: a tale of melodies');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'ef: a tale of memories');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Haikyu!!');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Black Lagoon: The Second Barrage');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Welcome to the NHK');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Re:ZERO -Starting Life in Another World-');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Legend of the Galactic Heroes: Overture to a New War');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Mushishi: Zoku-Sh�?: Suzu no Shizuku');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', '(The) Tale of the Princess Kaguya');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Honey and Clover');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Sword of the Stranger');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Haibane Renmei');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Sh�?wa Genroku Rakugo Shinjū');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Twelve Kingdoms');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Hunter X Hunter');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'My Hero Academia');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Cowboy Bebop: The Movie');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Tokyo Godfathers');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Toradora!');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Romeo × Juliet');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Owarimonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Maison Ikkoku');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Major');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Evangelion: . You Are (Not) Alone');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Shirobako');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Hellsing Ultimate');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Chihayafuru');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Tsubasa Toyo Revelations');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Katanagatari');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Mobile Suit Gundam UC');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', '(The) Garden of Words');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Full Metal Panic! The Second Raid');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Gintama.');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Hunter X Hunter');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Fate/Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'ERASED');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'BECK: Mongolian Chop Squad');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Kimi ni Todoke - From Me to You');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', '(La) Maison en Petits Cubes');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Den-noh Coil');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Bakuman');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'One Piece Episode of Nami: K�?kaishi no Namida to Nakama no Kizuna');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Natsumes Book of Friends');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Attack on Titan');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'JoJos Bizarre Adventure: Diamond Is Unbreakable');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Nodame Cantabile: Paris');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Lupin the Third: Part');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Berserk');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Brave King GaoGaiGar Final');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Kaiba');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Ping Pong');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Princess Tutu');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Conan, the Boy in Future');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Hotarubi no Mori e');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Azumanga Daioh');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Full Metal Panic? Fumoffu');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Nodame Cantabile: Finale');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Eden of the East');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', '(The) Rose of Versailles');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Mushishi Zoku-Sh�? Tokubetsu-hen: Odoro no Michi');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'unter X Hunter: G I Final');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Haikyu!!');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Yuri!!! on Ice');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Girls und Panzer der Film');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Natsume Yūjin-Ch�? Roku');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Mob Psycho');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Assassination Classroom');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Kimi ni Todoke nd Season');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Maquia - When the Promised Flower Blooms');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Hanasaku Iroha - Blossoms for Tomorrow');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Trigun');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Ghost in the Shell: Stand Alone Complex: Solid State Society');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Paprika');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Spice and Wolf');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Magnetic Rose');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'School Rumble: nd Semester');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'R.O.D -The TV-');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Violet Evergarden');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Ashita no Joe');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Sound! Euphonium');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Berserk: The Golden Age Arc III - The Advent');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', '(The) Eccentric Family');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Gungrave');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Last Exile');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Bakuman.');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Rurouni Kenshin');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Legend of the Galactic Heroes: My Conquest is the Sea of Stars');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Comedy');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Land of the Lustrous');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'When Marnie Was There');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Skip Beat!');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Natsume Yūjin-Ch�? Go');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'In This Corner of the World');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'xxxHOLiC: Kei');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Attack on Titan');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Neon Genesis Evangelion: The End of Evangelion');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Bakemonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', '(The) Super Dimension Fortress Macross: Do You Remember Love?');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Master Keaton');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Kikis Delivery Service');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hunter X Hunter: Greed Island');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Romeo and the Black Brothers');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Hajime no Ippo - Champion Road');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Super Dimension Fortress Macross');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Gintama');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'One Outs');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Tiger y  Bunny');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Black Lagoon');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Neon Genesis Evangelion');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Fate/stay night: Unlimited Blade Works');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Ghost in the Shell: Stand Alone Complex - Individual Eleven');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', '(The) Boy and The Beast');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', '(The) Anthem of the Heart');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Fate/Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Food Wars! Shokugeki no Soma');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Mobile Suit Gundam  Second Season');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Macross Frontier');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Darker than Black');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Nichijou - My Ordinary Life');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Space Brothers');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Gosick');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'No Game, No Life Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'One Punch Man');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Lupin III: The Castle of Cagliostro');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Aria the Avvenire');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Welcome to THE SPACE SHOW');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Denpa teki na Kanojo');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Monthly Girls Nozaki-kun');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Nobodys Boy Remi');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Elfen Lied');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Emma: A Victorian Romance Second Act');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Kizumonogatari Part : Reiketsu');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'My Hero Academia');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Rainbow - Nisha Rokub�? no Shichinin');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Wolfs Rain');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'No Game, No Life');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Ghost in the Shell: Stand Alone Complex - The Laughing Man');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Magical Girl Lyrical Nanoha the Movie nd As');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Junj�? Romantica');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Tokyo Magnitude .');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Eureka Seven');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'School Rumble');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Parasyte -the maxim-');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Hinamatsuri');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Kizumonogatari Part : Nekketsu (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Kill la Kill');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Ghost in the Shell (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Puella Magi Madoka Magica the Movie Part : Eternal');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Now and Then, Here and There');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Berserk: The Golden Age Arc II - The Battle for Doldrey (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Puella Magi Madoka Magica the Movie Part : Beginnings');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Kizumonogatari Part : Tekketsu (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Wagnaria!!');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Kimagure Orange Road: The Movie');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Lovely Complex');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Porco Rosso (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', '(The) Place Promised in Our Early Days (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Hikaru No Go: New Year Special');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'planetarian: Hoshi no Hito (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Mobile Suit Gundam - The Movie Trilogy');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hajime no Ippo - Mashiba vs. Kimura');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Puella Magi Madoka Magica The Movie Part : Rebellion');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Cardcaptor Sakura Movie : The Sealed Card');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Wind Rises (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Legend of the Galactic Heroes: A Hundred Billion Stars, A Hundred Billion Lights');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Detroit Metal City');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', '(The) Slayers Next');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'One Piece Film Strong World (movie )');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Strawberry Panic!');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'KenIchi the Mightiest Disciple');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Princess Jellyfish');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Bamboo Blade');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Initial D: Fourth Stage');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Mobile Suit Gundam');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Owarimonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Bakuman.');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Silver Spoon');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Hikaru no Go');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'ReLIFE');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Hajime no Ippo Rising');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Banner of the Stars II');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Higurashi no Naku Koroni Kai');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Gunbuster');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'ReLIFE');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Food Wars! The Second Plate');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Case Closed: The Phantom of Baker Street (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Samurai');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Voices of a Distant Star');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'lam Dunk');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Doraemon the Movie: Nobita and the Steel Troops: The New Age');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', '(The) Ancient Magus Bride');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Full Moon o Sagashite');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Miss Kobayashis Dragon Maid');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'A Lull in the Sea');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Mobile Suit Zeta Gundam');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Psycho-Pass');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Sayonara, Zetsubou-Sensei');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', '(The) Story of Saiunkoku Second Series');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'FLCL');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Treasure Island');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Case Closed: Captured in Her Eyes (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Case Closed: The Last Magician of the Century (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', '(The) Secret World of Arrietty (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Genshiken');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Touch (TV)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Kyo kara Maoh! rd Series');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Black Lagoon: Robertas Blood Trail');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Log Horizon');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Genshiken');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Big Windup! Season');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Case Closed: Countdown to Heaven (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Kaleido Star: Legend of Phoenix - Layla Hamilton Story');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Saint Seiya: The Hades Chapter - Sanctuary');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Junj�? Romantica');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Aria - The Natural');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Claymore');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Zoku Sayonara Zetsub�? Sensei');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Giant Robo');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Legend of the Galactic Heroes: Spiral Labyrinth');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Nisemonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Ace of Diamond: Second Season');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', '(The) Garden of Sinners/recalled out summer (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Non Non Biyori Repeat');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Fruits Basket');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'From Up On Poppy Hill (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Perfect Blue (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'When They Cry - Higurashi');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Kimagure Orange Road');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Birdy the Mighty Decode:');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Penguindrum');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Soul Eater');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Full Metal Panic!');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Hanada Sh�?nen-shi');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Hare+Guu Deluxe');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Baby Blue (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'xxxHOLiC: R�?');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Emma: A Victorian Romance');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Macross Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Space Battleship Yamato');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Fairy Tail Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Mobile Suit Gundam: The Origin');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'One Piece DY Ace no Shi wo Koete! Luffy Nakama to no Chikai');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Chihayafuru');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Tatami Galaxy');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Tamayura: Sotsugy�? Shashin (movie series)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', '(The) Vision of Escaflowne');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Mobile Suit Gundam: Iron-Blooded Orphans');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Magical Girl Lyrical Nanoha As');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Black Butler: Book of Murder');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', '(The) Eccentric Family (TV)');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Read or Die');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Durarara!!');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Broken Blade (movie series)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Yu Yu Hakusho: Ghost Files');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Fate/stay night: Unlimited Blade Works');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Ga-Rei-Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Macross Plus Movie Edition');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Kaiji');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Gintama Season');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Tsubasa: Spring Thunder');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', '(The) Story of Saiunkoku');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Crest of the Stars');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'On Your Mark (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Urusei Yatsura: Beautiful Dreamer (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Gintama');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Hanamonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'KONOSUBA - Gods blessing on this wonderful world!');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Toward the Terra');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Mind Game (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Genshiken');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Mobile Suit Gundam Seed');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Goku Sayonara Zetsub�? Sensei');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Daicon films (special)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'One Piece Film Z (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Baby Steps');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'City Hunter');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Redline (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Big Windup!');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Saga of Tanya the Evil');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Initial D: Second Stage');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'K-ON! (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'InuYasha: The Final Act');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Jormungand Perfect Order');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Dog of Flanders (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Mah�? Sensei Negima!: M�? Hitotsu no Sekai (OAV)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Gintama: The Movie');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', '(The) Disastrous Life of Saiki K.');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Lunar Legend Tsukihime');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Zan Sayonara Zetsub�? Sensei');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Rurouni Kenshin: Reflection');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hanasaku Iroha: Home Sweet Home (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Aggressive Retsuko');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Fate/stay night: Heavens Feel I. presage flower (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Kurenai');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Steins;Gate: The Movie - Load Region of Dejà Vu');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Kyousougiga');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Girls Last Tour');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Barakamon');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', '(The) Irresponsible Captain Tylor');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Death Parade');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Detective Conan: The Lost Ship in The Sky (movie )');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Patema Inverted (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Banner of the Stars');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Yona of the Dawn');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Revolutionary Girl Utena');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Hidamari Sketch × Honeycomb');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Wagnaria!!');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Barefoot Gen (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Children Who Chase Lost Voices');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Case Closed: The Fourteenth Target');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Ghost in the Shell S.A.C. Solid State Society D');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'My-HiME');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Natsume Yūjin-Ch�?: Itsuka Yuki no Hi ni');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Sound! Euphonium');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Hozukis Coolheadedness');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'One Piece');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Shigofumi - Letters from the Departed');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Trigun: Badlands Rumble');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Hidamari Sketch × Hoshimittsu');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'INTERSTELLA : The tory of the ecret tar ystem');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Silver Spoon');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Lucky Star');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Tsukimonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'RahXephon');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'My Teen Romantic Comedy SNAFU TOO!');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Laid-Back Camp');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Gurren Lagann the Movie –Childhoods End-');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Tsukigakirei');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'His and Her Circumstances');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', '(The) Seven Deadly Sins: Revival of The Commandments');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Vampire Hunter D: Bloodlust');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Kobato.');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Berserk: The Golden Age Arc I - The Egg of the King');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Doukyusei -Classmates-');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'House of Five Leaves');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'School Rumble: Extra Class');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Nekomonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Glass Mask');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', '(The) Ancient Magus Bride: Those Awaiting a Star');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'My Love Story!!');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Ergo Proxy');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Ghost in the Shell: Arise');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Tenchi Muyo! Ryo-Ohki');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Love, Chunibyo y  Other Delusions!');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Strawberry Marshmallow');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Initial D: Third Stage (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Master Keaton');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Banner of the Stars III');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Attack on Titan: No Regrets');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Final Fantasy VII: Advent Children');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Attack on Titan');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Fullmetal Alchemist: The Movie - Conqueror of Shamballa');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Macross Plus');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Hayate the Combat Butler!!');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Daily Lives of High School Boys');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Hy�?ka');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Hidamari Sketch: Sae/Hiro Sotsugy�?-hen');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Tekkonkinkreet');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Initial D: Final Stage');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Food Wars! The Third Plate');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Tari Tari');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Detective Conan: The Private Eyes Requiem');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Moshidora');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Shakugan no Shana');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'A Letter to Momo');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Rage of Bahamut: Genesis');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Little Witch Academia');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', '(The) Cat Returns');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'xxxHOLiC: Shunmuki');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'xxxHOLiC: R�? Adayume');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Kinos Travels: Life Goes On');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Mobile Suit Gundam: The th MS Team');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Heartcatch Precure! Hana no Miyako de Fashion Show…Desu ka!?');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Sword Art Online the Movie: Ordinal Scale');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'JoJos Bizarre Adventure: Stardust Crusaders Egypt Arc');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Kamichu!');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Hidamari Sketch × Hoshimittsu');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'GATE');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Noein - to your other self');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Seto no Hanayome');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'H�?zuki no Reitetsu');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Scrapped Princess');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Ushio y  Tora');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Shonen Onmyouji');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Food Wars! The Third Plate');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Zan Sayonara Zetsub�? Sensei Bangai-chi');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Tiger y  Bunny The Movie -The Rising-');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'White Album');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Full Metal Panic! The Second Raid');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Tenchi Muyo! War on Geminar');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hidamari Sketch ×');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Queen Millennia');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Megalobox');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Gunslinger Girl');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', '(The) Disastrous Life of Saiki K.');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Inuyashiki Last Hero');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Colorful');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Detective Conan: The Raven Chaser');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Another');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Giovannis Island');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Planetarian');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Full Metal Panic! Invisible Victory');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Akira');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Blood+');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Waiting in the Summer');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Strawberry Marshmallow');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Fullmetal Alchemist: Brotherhood');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Case Closed The Movie: The Time Bombed Skyscraper');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Hi Score Girl');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'From the New World');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Aria the Animation');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Detective Conan: Magician of the Silver Sky');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Macross Frontier: Itsuwari no Utahime');

INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Sore ga Seiyuu');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Koi wa Ameagari no You ni');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Uta no Prince-Sama MAji Love Legend Star');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'DanMachi: Sword Oratoria');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Masou Gakuen HxH Sin Censura');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , ' Girls! Shin Shou');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , '91 Days');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Nora to Oujo to Noraneko Heart');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'KissXsis');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Concrete Revolution Choujin Gensou');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Chaos;Child');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Souryo to Majiwaru Shikiyoku no Yoru ni...');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Dance with Devils');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Kabukibu!');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Nanatsu: Imashime no Fukkatsu');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Tokyo Ghoul S2');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Prince of Stride - Alternative');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Sanrio Danshi');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Karakai Jouzu no Takagi-san');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Toji no Miko');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Yuri Kuma Arashi');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Dive!!');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Fukumenkei Noise');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'ClockWork Planet');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Getsuyoubi no Tawawa');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Zombieland Saga');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Kabukibu!');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Sakamoto Desu Ga?');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Persona 5 The Animation');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Orange');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Queens Blade: Grimoire');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Orange');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Anitore EX');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Gate jieitai Nite Kaku');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Ange Vierge');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Mahou Shoujo Nante Mou II Desukara 2nd Season');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'DOUBLE DECKER! Doug y Kirill');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Shoujo Kageki Revue Starlight');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Chiruran Nibun no Ichi');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Isekai Shokudou');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Hand Shakers');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Shokugeki no Souma: San no Sara - Tootsuki Ressha-hen');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Sanrio Danshi');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Tsukumogami Kashimasu');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Hatsukoi Monster');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'One Punch Man');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Lostorage Incited Wixoss');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Inazuma Eleven Ares no Tenbin');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Kujira no Kora wa Sajou Utau');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Utawarerumono Itsuwari no Kamen');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Aho Girl');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'New Game!! Segunda Temporada');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Two Car');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Tsukipro The Animation');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Kagewani: Shou');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Isuca');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Endride');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Satsuriku no Tenshi');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Dies Irae');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Dragon Ball Super');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Anne Happy');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , '12-Sai: Chicchana Mune no Tokimeki');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'YU-GI-OH! GX');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Tantei Team Kz Jiken Note');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Kujira no Kora wa Sajou Utau');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Sailor Moon crystal: death Busters-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Jitsu wa Watashi wa');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'EroManga-Sensei - Recomendado');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Cinderella Girls Gekijou Tercera Temporada');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Dog Days 3S');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Yoru no Yatterman');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Kaze ga Tsuyoku Fuiteiru');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Katsugeki/Touken Ranbu');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Lord of Vermillion: Guren no Ou');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Sengoku Night Blood');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Gamers!');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Inuyashiki');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'To Be Heroine');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Show by Rock!! #');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'JK Meshi');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Minami Kamakura Koukou Joshi Jitensha-Bu');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Bungou Stray Dogs 2nd Season');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Goblin Slayer');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Sieshun Buta Yarou wa Bunny Girl-senpai no Yume wo Minai');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Hitsugi no Chaika: Avening Battle');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Cheer Danshi!!');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Gyakuten Siaban: Sono Shinjitsu');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Hyakka Ryouran Samurai Bride S2');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Ninja Slayer From Animation');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Cardcaptor Sakura: Clear Card-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Koufuku Graffiti');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Lupin III: Part V');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Irozuku Sekai no Ashita kara');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Cheer Danshi!!');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Danganronpa 3: The End Of Kibougamine Gakuen - Mirai-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Konohana Kitan');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'High School DxD Born');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Kyokai no Kanata Movie: Ill be Here - Mirai-hen');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Boruto: Naruto Next Generations');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Alice or Alice');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Triage X');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Cinderella Girls Gekijou Segunda Temporada');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Urawa no usagi-Chan');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Hibike! Euphonium 2');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Nana Maru San Batsu');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Sangatsu no Lion Segunda temporada');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Masamune-kun no Revenge');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Saiki Kusuo no Psi 2');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Souryo to Majiwaru Shikiyoku no Yoru ni...');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Shokugeki no Souma: San no Sara');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Overlord');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Kowabon');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Bakuon!!');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Golden Kamuy 2');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Last Period: Owarinaki Rasen no Monogatari');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Saint Seiya: Soul of Gould');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Tokyo Ghoul S2');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Sakurako-san Ashimoto ni Wa Shitai');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Lostorage Incited Wixoss');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'RErideD: Koku Koe no Derrida');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Sangatsu no Lion');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Juuou Mujin no Fafnir');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Nobunaga no Shinobi: Ise Kanegasaki-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'HaiFuri');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Action Herione Cheer Fruits');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Girlish Number');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Star vs Forces of Evil Tercera Temporada');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Fate/Gran Order Moonlight/Lostroom');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Yuuki Yuuna Wa Yuusha de Aru: Washio Sumi no Shou');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Ange Vierge');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Ajin 2nd Season');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Saenai Heroine no Sodatekata 2 (2017)');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Tachibanakan to Lie Angle');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Karakai Jouzu no Takagi-san');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Working!!! 3');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Shoukoku no Altair');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Hagure Yuusha no Estetica');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Orange');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Vatican Kiseki Chousakan');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Megalo Box');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Durarara!! x2 Ketsu');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Ame-iro Cocoa in Hawaii');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Magi: The Labyrinth of Magic');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Luck and Logic');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Sakurako-san Ashimoto ni Wa Shitai');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'SchoolGirl Strikers: Animation Channel');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Punchline');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'High School DxD Hero');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Hajimete no Gal');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Marchan Madchen');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'MahouTsukai No Yome');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Minami Kamakura Koukou Joshi Jitensha-Bu');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Senki Zesshou Symphogear G');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'GATE: JIEITAI KANOCHI NITE');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Sekkou Boys');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Punchline');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Rewrite Moon and Terra');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Tales of Zestiria The X (2017)');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Jojo no Kimyou na Bouken: Ougon no Kaze');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Aki no Kanade');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Hitoijime my Hero');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Phantom in the Twilight');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Emiya-san Chi no Kyou Gohan');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Soushin Shoujo Matoi');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Bubuki Buranki: Hoshi no Kyojin');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , ' KAKU TATAKAERI - ENRYUU-HEN');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'B-Project: Kodou Ambitous');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Overlord');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Charlotte');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Omiai Aite wa Oshiego Tsuyoki na Monaiji');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'GrandBlue Fantasy');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Souten no Ken: Regenesis');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Ushio to Tora (TV) 2nd Season');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Shingeki no Kyojin: Chuugakkou');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Yama no Susume 3');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Noragami Aragato');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Ebiten: Kouritsu Ebisugawa Koukou Tenmonbu');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Uchuu Senkan Tiramisu');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Dog Days');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Boku Dake ga Inai Machi');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Boku no Hero Academia');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Ojisan to Marshmallow');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'MomoKuri');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Ebiten: Kouritsu Ebisugawa Koukou Tenmonbu');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Grisaia no Kajitsu Especiales');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Koi wa Ameagari no You ni');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Anne Happy');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Fudanshi Koukou seikatsu');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Toaru Majutsu no Index III');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Utawarerumono Itsuwari no Kamen');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Durarara!! x2 Shou');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Idol Memories');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Super Lovers 2');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Golden Kamuy 2');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Nisekoi Ovas');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Shoukoku no Altair');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Rewrite');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Kakuriyo no Yadomeshi');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Cardcaptor Sakura: Clear Card-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Re:Zero Kara Hajimeru Isekai Seikatsu');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Love Live! Sunshine!!');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Flip Flappers');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Tsugumomo');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Nanbaka (2017)');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Alice or Alice');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Toaru Majutsu no Index III');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Tales of Zestiria The X (2017)');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Ore ga Ojousama gakkou ni Shomin Sample');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Golden Kamuy');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Tada-kun wa Koi wo Shinai');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Shouwa Genroku Rakugo Shinjuu');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Takamiya Nasuno Desu!: Teekyuu Spin Off');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Working!!! 3');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Beatles');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Owarimonogatari');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Sword Art Online: Alicization');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Nobunaga no Shinobi');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Kyokai no Kanata Movie: Ill be Here');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Ghots in The Shell: Arise - Alternative');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Radiant');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Saiki Kusuo no Psi 2');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Aoharu x kikanjuu');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Durarara!!');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Dynamic Chord');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Caligula');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Etotama!');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Re:Zero Kara Hajimeru Isekai Seikatsu');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Busou Shoujo Machiavllianism');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'The Rolling Girls');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Owarimonogatari Segunda temporada');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Isekai Maou to Shoukan Shoujo no Dorei Majutsu');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Yuru Camp');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Super Lovers');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Gintama 2017');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Berserk (2016)');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Nisekoi Ovas');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Ao no Exorcist: Kyoto Fujouou-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'High Score Girl');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Anitore EX');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Two Car');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Re:Creators');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Demi-chan wa Kataritai');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Houseki no Kuni');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Nazotokine');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'ReLIFE');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Juuou Mujin no Fafnir');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Triage X');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Steins;Gate: Kyoukaimenjou no Missing Link');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Show by Rock');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Concrete Revolution Choujin Gensou');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Miss Monochrome Animation 2');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Uchuu Senkan Tiramisu');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Tsurezure Children');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Sora to Umi no Aida');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Servamp');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Nanbaka (2017)');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'FOOD WARS: SHOKUGEKI NO SOMA');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Harukana Receive');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Re:Zero Kara Hajimeru Isekai Seikatsu');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Clione no Akari');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Yuru Yuri Nachuyachumi Plus');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Rokudenashi Majutsu Koushi to Akashic Records');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Soul Buster');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Akkun to Kanojo');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Basilisk: Ouka Ninpouchou');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Darling in The Franxx');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Fukumenkei Noise');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Sangatsu no Lion');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Dragon Ball Z:Fukatsu no F');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Ojisan to Marshmallow');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Akibas Trip The Animation');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Overlord');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Hibike! Euphonium 2');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Tsukumogami Kashimasu');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Kuromukuro');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Angolmois: Genkou Kassenki');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Tsukiuta The Animation');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Bubuki Buranki: Hoshi no Kyojin');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Senki Zesshou Symphogear');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Koi to Uso');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Kagewani');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Concrete Revolution Choujin Gensou - The Last Song');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Himouto Umaru-chan R (Segunda Temporada)');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'High Score Girl');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Yama no Susume 3');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Kekkai Sensen y Beyond');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Wakaba Girl');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Omiai Aite wa Oshiego Tsuyoki na Monaiji');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Hacka Doll The Animation');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Lost Song');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Fate/Gran Order Moonlight/Lostroom');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Jojo no Kimyou na Bouken: Ougon no Kaze');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Back Street Girls');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , '12-Sai: Chicchana Mune no Tokimeki 2nd Season');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Anitore! XX');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Vivid Strike!');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Overlord Tercera Temporada');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Phantom in the Twilight');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Wakako Zake');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Shoujo Tachi wa Kouya wo Mezasu');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Pokemon XYyZ');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Kuroko no Basuke');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'New Game!! Segunda Temporada');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Nora to Oujo to Noraneko Heart');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Katsugeki/Touken Ranbu');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Dynamic Chord');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'MahouTsukai No Yome');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Heavy Object');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Imouto Sae Ireba Li');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Sin: Nanatsu no Taizai');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Grisaia no Kajitsu Especiales');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Nanbaka (2017)');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Ulysses: Jeanne d Arc to Renkin no Kishi');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Komori-san wa Kotowarenai');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Prison School');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Ore ga Suki nano wa Imouto dakedo Imouto ja Nai');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Rewrite');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Cinderella Girls Gekijou');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Owari no Seraph');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Ore ga Suki nano wa Imouto dakedo Imouto ja Nai');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Blend S');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Sailor Moon crystal: death Busters-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'MahouTsukai No Yome');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Urawa no usagi-Chan');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Shoukoku no Altair');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Bakuon!!');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Fate/Kaleid Liner Prisma Illya 2wei Herz!');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Renai Boukun');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Aki no Kanade');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Hyakuren no Haou to Seiyaku no Valkyria');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Centaur no Nayami');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Hajimete no Gal');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Tanaka-kun wa Itsumo Kedaruge');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Ojisan to Marshmallow');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Prince of Stride - Alternative');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Shoujo Shuumatsu Ryokou');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Boruto: Naruto The Movie');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Ore ga Suki nano wa Imouto dakedo Imouto ja Nai');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'FOOD WARS: SHOKUGEKI NO SOMA');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Onsen Yousei Hakone-chan');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Koutetsujou no Kabaneri');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Mahou Shoujo Ikusei Keikaku');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Durarara!!');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Miss Monochrome Animation 2');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Sansha Sanyou');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Hitoijime my Hero');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Plastic Nee-san');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Gamers!');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Sansha Sanyou');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Piace: Watashi no Italian');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Juushinki Pandora');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Kyoukai no Rinne');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Mayoiga');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Kakuriyo no Yadomeshi');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Gakkou Gurashi');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Jojo no Kimyou na Bouken: Ougon no Kaze');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Angolmois: Genkou Kassenki');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Flying Witch');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Koi wa Ameagari no You ni');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Saiki Kusuo no Psi 2');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Gin no Guardian');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Norn9 Norn+Nonet');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Shingeki no Kyojin: Kuinaki Sentaku');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Uchuu Senkan Tiramisu');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Queens Blade: Grimoire');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Amanchu! Advance S2');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Urawa no usagi-Chan');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Gintama 2017');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Sengoku Night Blood');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Nanatsu no Bitoku');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Fate Zero Temporadas 1 y 2');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Renai Boukun');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'SchoolGirl Strikers: Animation Channel');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Blend S');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Naruto Shippuden Latino');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Aldnoah.Zero');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Magic Kaito 1412');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Diamon no Ace S2');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Sakurako-san Ashimoto ni Wa Shitai');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Nana Maru San Batsu');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Juuou Taisen');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Ozmafia');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Maken-ki!');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Nanbaka');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Chiruran Nibun no Ichi');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Isekai Maou to Shoukan Shoujo no Dorei Majutsu');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Dragon Ball Z:Fukatsu no F');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Senki Zesshou Symphogear AXZ');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Hakumei to Mikochi');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Magic Kaito 1412');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Gintama Shinyaku Benizakura-hen Special');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Grisaia no Rakuen');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Piano no Mori (tv)');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Bishoujo Yuugi Unit Crane Game Girls');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Sakurako-san Ashimoto ni Wa Shitai');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Anitore! XX');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Yagate Kimi ni Naru');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Netsuzou Trap -NTR-');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Tonari no Kyuuketsuki-san');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Jitsu wa Watashi wa');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Kobayashi-san Chi no Maid Dragon');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Zombieland Saga');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Bang Dream! Girls Band Party! Pico');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Gakusen Toshi Asterisk');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Hibike! Euphonium 2');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Kekkai Sensen');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Rewrite');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Seiken tsukai no World Break');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Kimi ni Todoke');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Kaze ga Tsuyoku Fuiteiru');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Free! Dive to the Future');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Danganronpa 3: The End Of Kibougamine Gakuen - Mirai-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Non Non Biyori Repeat');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Eldlive');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Fukigen na Mononokean');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Karakai Jouzu no Takagi-san');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'One Punch Man');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Durarara!! x2 Ten');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Sengoku Night Blood');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Amanchu! Advance S2');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Aoharu x kikanjuu');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Urahara');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Classroom Crisis');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Boku no Hero Academia');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Ryuuou no Oshigoto');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , '18if');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Princess Principal');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Maoyuu Mao Yuusha');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Concrete Revolution Choujin Gensou');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Gintama 2015 - Cuarta Temporada');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Queens Blade: Grimoire');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Kiseijuu sei no Kakuritsu');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Hidan no Aria AA');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Owarimonogatari Segunda temporada');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Kill la Kill');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Ame iro Cocoa Rainy color e Youkoso');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Divine Gate');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Gatchaman Crowds Insight');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Mahou Shoujo Ore');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Yuru Yuri Nachuyachumi Ova');
INSERT INTO ropa(categoria,anime) VALUES ('Chaqueta' , 'Onigiri Anime');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , '12-Sai: Chicchana Mune no Tokimeki');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Nobunaga no Shinobi');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Kill la Kill');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Goblin Slayer');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Boruto: Naruto Next Generations');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Golden Kamuy 2');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Itsudatte Bokura no koi wa 10 Cm Datta');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Banana Fish');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Satsuriku no Tenshi');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Nobunaga no Shinobi: Ise Kanegasaki-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Dungeon ni Deai wo Motomeru no Wa Machigatte iru Darou ka');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Rewrite Moon and Terra');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Osake wa Fuufu ni Natte Kara');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Idol Jihen');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Sora to Umi no Aida');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Banana Fish');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Ousama Game The Animation');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Sakurada Reset');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Haiyore Nyaruko-san F OVA');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Imouto Sae Ireba Li');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Zoku Touken Ranbu: Hanamaru');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Minami Kamakura Koukou Joshi Jitensha-Bu');
INSERT INTO ropa(categoria,anime) VALUES ('Gorro' , 'Uchuu Senkan Tiramisu');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Kaze ga Tsuyoku Fuiteiru');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'To Love ru Darkness 2nd Sin Censura');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Tales of Zestiria The X');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Uma Musume Pretty Derby');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Ao no Exorcist: Kyoto Fujouou-Hen');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Brave Witches');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Flying Witch');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Ange Vierge');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Gintama 2015 OVA');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Saiyuuki Reload Blast');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Natsume Yuujinchou Go');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Yamada-kun to 7-nin no Majo');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Shinmai Maou no Testament sin censura');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Hello Kiniro-Mosaic');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Slow Start');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Muhyo to Rouji no Mahoritsu Soudan Jimusou');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'Dagashi Kashi');
INSERT INTO ropa(categoria,anime) VALUES ('Camiseta' , 'Mob Psycho 100');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Bang Dream!');
INSERT INTO ropa(categoria,anime) VALUES ('Saco' , 'Muhyo to Rouji no Mahoritsu Soudan Jimusou');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , '3D Kanojo');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'High School DxD Born');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Sakura Quest');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Akagami no Shirayuki Hime 2nd Season');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'ReLIFE Kanketsu-hen');
INSERT INTO ropa(categoria,anime) VALUES ('Pantaloneta' , 'Bishoujo Yuugi Unit Crane Game Girls Galaxy');
INSERT INTO ropa(categoria,anime) VALUES ('Pantalon' , 'One Punch Man');
INSERT INTO ropa(categoria,anime) VALUES ('Bufanda' , 'Hello Kiniro-Mosaic');
INSERT INTO ropa(categoria,anime) VALUES ('Camisa' , 'Nyanko Days');
INSERT INTO ropa(categoria,anime) VALUES ('Gorra' , 'Youkai Apartment no Yuuga na Nichijou');
INSERT INTO ropa(categoria,anime) VALUES ('Medias' , 'Hatsukoi Monster');