CREATE OR REPLACE PACKAGE BODY PC_PRODUCTOS IS
  PROCEDURE AD_ANIME(XNOMBRE IN VARCHAR,XGENERO IN VARCHAR) IS
  BEGIN
    INSERT INTO animes(nombre , genero) VALUES(XNOMBRE,XGENERO);
    COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20015,'NO');
    END AD_ANIME; 
    
  PROCEDURE AD_FIGURA(XPERANIME IN VARCHAR, XTAMA_O IN VARCHAR) IS
  BEGIN
    INSERT INTO figuras(peranime, tama_o) VALUES(XPERANIME,XTAMA_OV);
    COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20015,'NO');
    END AD_FIGURA; 
    
  PROCEDURE AD_PERSONAJE(XNOMBRE IN VARCHAR, XNOMBREANIMES IN VARCHAR) IS
  BEGIN
    INSERT INTO personajes(nombre , nombreanime) VALUES (XNOMBRE,XNOMBREANIMES);
    COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20015,'NO');
    END AD_PERSONAJE; 
    
  PROCEDURE AD_AUTOR(XNOMBRE IN VARCHAR) IS
  BEGIN
    INSERT INTO autores(nombre) VALUES (XNAME);
    COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20015,'NO');
    END AD_AUTOR;
    
  PROCEDURE AD_ROPA(XCATEGORIA IN VARCHAR, XANIME IN VARCHAR) IS
  BEGIN
    INSERT INTO ropa(categoria , anime) VALUES (XCATEGORIA,XANIME);
    COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20015,'NO');
    END AD_AUTOR;
    
  PROCEDURE AD_EJEMPLAR(XCANTIDAD IN VARCHAR, XPRECIO IN VARCHAR, XFIGURA IN VARCHAR, XROPA IN VARCHAR, XANIME IN VARCHAR, XVENTAS IN VARCHAR, XSEDE IN VARCHAR) IS
  BEGIN
    INSERT INTO ropa(categoria , anime) VALUES (XCATEGORIA,XANIME);
    COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20015,'NO');
    END AD_AUTOR;
END;