INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'ip_address', 'your name.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Darby Caplis', 'Fullmetal Alchemist: Brotherhood');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aarika Davitashvili', 'Steins;Gate');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ahmad Newlan', 'Clannad After Story');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nona Tolle', 'Rurouni Kenshin: Trust y  Betrayal');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jackie Galey', 'Code Geass: Lelouch of the Rebellion R');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wilhelm Stegers', 'Spirited Away');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Miriam Duffield', 'A Silent Voice');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Orland Klyner', 'Cowboy Bebop');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aristotle Pyott', 'Mushishi: The Next Chapter');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Maddi Glusby', '(The) Disappearance of Haruhi Suzumiya');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Haley Follett', 'Princess Mononoke');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sigvard Meah', '(The) Legend of the Galactic Heroes');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Donia Warlock', 'Mushi-Shi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Meade Sergison', 'Death Note');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tulley Goodluck', 'Maria Watches Over Us rd Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Neysa Picott', 'Made in Abyss');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Emelyne Goldstein', 'Maria Watches Over Us Season : Printemps');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Minni Gloyens', 'Code Geass: Lelouch of the Rebellion');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Honey Shanley', 'Gintama');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ker Talks', 'anohana: The Flower We Saw That Day');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wash Cauley', 'Descending Stories: Showa Genroku Rakugo Shinju');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bevin Downes', 'Maria Watches Over Us th Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eloisa Bazire', 'Gintama');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Donavon Lowthian', 'Gintama (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tom Keys', 'Bunny Drop');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Janina Clemoes', 'Evangelion: . You Can (Not) Advance');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Boote Fortie', 'Monster');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ignacius Lindsay', 'Grave of the Fireflies');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bendix Renvoise', 'Cross Game');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jocelin Rodolfi', 'Ghost in the Shell: Stand Alone Complex nd GIG');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ursola Pilch', 'Summer Wars');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Adrian Van Castele', 'Fighting Spirit');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jody Hallawell', 'Fullmetal Alchemist');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tandi Fumagalli', 'Hunter × Hunter');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Esther Rippon', 'Nodame Cantabile');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jennee Sibbs', '(The) Girl Who Leapt Through Time');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Grant Rapps', 'Centimeters Per Second');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sherie Petrusch', 'Nausicaä of the Valley of the Wind');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Anissa Flannery', 'Gurren Lagann');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rudyard de Clerk', '(The) Garden of Sinners');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Misty Reen', 'Wolf Children');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ursa Dymoke', 'My Neighbor Totoro');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kurtis Lidgard', 'Baccano!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kristofor Baldcock', 'Honey and Clover II');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Diane-marie Brennenstuhl', 'Natsumes Book of Friends');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gerry Esom', 'Gintama: The Final Movie');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sophie Sanches', 'Hajime no Ippo: New Challenger');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Etan Crilly', 'Kanon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Theresa Brownrigg', 'Star Blazers');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Max Sturm', 'GTO: Great Teacher Onizuka');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Desirae Lowthian', 'Kinos Journey');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Korella Polack', 'Howls Moving Castle');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carena Saltmarsh', 'Time of Eve');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Blondell Plews', 'Puella Magi Madoka Magica');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Yardley Fugere', 'Mushishi Tokubetsu-hen: Hihamukage');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Elset Varley', 'Natsumes Book of Friends');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Merry Wardingly', 'Millennium Actress');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Griffin Bailles', 'Time of Eve');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Harli Batcock', 'Monogatari Series Second Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Penny Sinderland', 'Kaleido Star');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wilbur Ca', 'Mononoke');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shannan Pollard', 'Kids on the Slope');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Winthrop Strafen', 'Natsumes Book of Friends');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Micah Nani', '(The) Melancholy of Haruhi Suzumiya');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bevvy Guilliatt', 'Gankutsuou: The Count of Monte Cristo');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eldin Kissell', 'Clannad');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tracy Fidilis', 'Planetes');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Thatcher Mochar', 'NANA');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shandee ORiordan', 'Looking Up At The Half-Moon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Chantal Elliott', 'Castle in the Sky');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aldridge Serchwell', 'Your Lie in April');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marisa Sibborn', 'Whisper of the Heart');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Fred Blackden', 'Samurai Champloo');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Thedric Woollaston', 'Ouran High School Host Club');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Joyan Chenery', 'A Place Further Than the Universe');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Peirce Ferentz', 'Gurren Lagann the Movie – The Lights in the Sky Are Stars');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Barclay Kynson', '(The) Beast Player Erin');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Locke Pardew', 'Ghost in the Shell: Stand Alone Complex');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aleta Randall', 'Maria Watches Over Us');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cathlene Yurin', 'Aria the Origination');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rhetta Asipenko', 'Spice and Wolf II');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Brigit Lowdes', 'Angel Beats!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Merrily Ingold', 'Moribito - Guardian of the Spirit');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cahra Cordon', 'March comes in like a lion');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Inna Heaney', 'Haikyu!! Second Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Chadd Hinchcliffe', 'My Hero Academia');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bellanca Braxton', 'ef: a tale of melodies');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gerrie Sullly', 'ef: a tale of memories');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eartha Clemence', 'Haikyu!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Larine Jolley', 'Black Lagoon: The Second Barrage');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nate Binnall', 'Welcome to the NHK');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hermann Zannetti', 'Re:ZERO -Starting Life in Another World-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Roddie Boow', 'Legend of the Galactic Heroes: Overture to a New War');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Barron Cudihy', 'Mushishi: Zoku-Sho: Suzu no Shizuku');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Audrey Merryman', '(The) Tale of the Princess Kaguya');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Washington Skehens', 'Honey and Clover');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Arni Robrose', 'Sword of the Stranger');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dulci Losseljong', 'Haibane Renmei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aimee Toleman', 'Showa Genroku Rakugo Shinju');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Amabel Lacey', '(The) Twelve Kingdoms');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Elbertine Abbyss', 'Hunter X Hunter');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bary Ceresa', 'My Hero Academia');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Abbe Petren', 'Cowboy Bebop: The Movie');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rosamond Cloney', 'Tokyo Godfathers');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Andeee Hillett', 'Toradora!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kennett Alfonso', 'Romeo × Juliet');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rubetta McCrow', 'Owarimonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Felicia Feld', 'Maison Ikkoku');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tymothy Itschakov', 'Major');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Florette Ebunoluwa', 'Evangelion: . You Are (Not) Alone');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eilis Quickenden', 'Shirobako');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cynthia Goatman', 'Hellsing Ultimate');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Andy Priddis', 'Chihayafuru');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kelvin Rabbitt', 'Tsubasa Toyo Revelations');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Camila Ingrem', 'Katanagatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lorenzo Skelbeck', 'Mobile Suit Gundam UC');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bernita Swinglehurst', '(The) Garden of Words');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Baudoin Livoir', 'Full Metal Panic! The Second Raid');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Patrice Spadoni', 'Gintama.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hilda Girk', 'Hunter X Hunter');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Felike Stranks', 'Fate/Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'James McReidy', 'ERASED');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hazlett Jendrassik', 'BECK: Mongolian Chop Squad');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Clerc Antunez', 'Kimi ni Todoke - From Me to You');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shelton Cawtheray', '(La) Maison en Petits Cubes');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rosamund Benian', 'Den-noh Coil');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Darn Plumbley', 'Bakuman');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shelly McGraw', 'One Piece Episode of Nami: Kokaishi no Namida to Nakama no Kizuna');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rubia Dawidowicz', 'Natsumes Book of Friends');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dolph Straneo', 'Attack on Titan');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Reece Durant', 'JoJos Bizarre Adventure: Diamond Is Unbreakable');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Liana Sawdy', 'Nodame Cantabile: Paris');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Francesca Sunners', 'Lupin the Third: Part');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Annadiane Cosens', 'Berserk');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Grover Denisovo', 'Brave King GaoGaiGar Final');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Celle Rozec', 'Kaiba');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Freedman Dwyr', 'Ping Pong');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ferdy Balazin', 'Princess Tutu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Pet Isaaksohn', 'Conan, the Boy in Future');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dela Evreux', 'Hotarubi no Mori e');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Siana Romeo', 'Azumanga Daioh');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rory Lehr', 'Full Metal Panic? Fumoffu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kylie Draysey', 'Nodame Cantabile: Finale');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ansel Treleven', 'Eden of the East');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jobie Havik', '(The) Rose of Versailles');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Humphrey Turvie', 'Mushishi Zoku-Sho Tokubetsu-hen: Odoro no Michi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wadsworth Merigot', 'unter X Hunter: G I Final');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gilemette Ethridge', 'Haikyu!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shae Lockwood', 'Yuri!!! on Ice');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Connie Balderson', 'Girls und Panzer der Film');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lexy Lyster', 'Natsume Yujin-Cho Roku');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Livvyy Gagan', 'Mob Psycho');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Man Denyukhin', 'Assassination Classroom');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Amalie Baldwin', 'Kimi ni Todoke nd Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Constancia Desbrow', 'Maquia - When the Promised Flower Blooms');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wilona Ourtic', 'Hanasaku Iroha - Blossoms for Tomorrow');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Charmine Stelfax', 'Trigun');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ric Brigham', 'Ghost in the Shell: Stand Alone Complex: Solid State Society');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Noni Pitone', 'Paprika');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ken Marlen', 'Spice and Wolf');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bax Taphouse', 'Magnetic Rose');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rodolphe Bignold', 'School Rumble: nd Semester');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Karyn Sunner', 'R.O.D -The TV-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Giorgia Brett', 'Violet Evergarden');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Galvin Goodredge', 'Ashita no Joe');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Liva Gornar', 'Sound! Euphonium');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Emmerich Mertel', 'Berserk: The Golden Age Arc III - The Advent');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lilla Pattini', '(The) Eccentric Family');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Charmion Gamblin', 'Gungrave');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aleece Johnsson', 'Last Exile');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ingrim Satchell', 'Bakuman.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rahal Baptiste', 'Rurouni Kenshin');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Claribel Gurrado', 'Legend of the Galactic Heroes: My Conquest is the Sea of Stars');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Konstanze Heigho', 'Comedy');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marylynne Boyne', 'Land of the Lustrous');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Padraic Hanbidge', 'When Marnie Was There');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Noelani Saiens', 'Skip Beat!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wren Calvard', 'Natsume Yujin-Cho Go');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Goober Toten', 'In This Corner of the World');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rees Linwood', 'xxxHOLiC: Kei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hakeem Delwater', 'Attack on Titan');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Haywood Phetteplace', 'Neon Genesis Evangelion: The End of Evangelion');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Suzette Tilling', 'Bakemonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Edie Shade', '(The) Super Dimension Fortress Macross: Do You Remember Love?');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hall Clemensen', 'Master Keaton');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Darell Wakeford', 'Kikis Delivery Service');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Heidi OScandall', 'Hunter X Hunter: Greed Island');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Matty Tardiff', 'Romeo and the Black Brothers');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Laetitia Jackes', 'Hajime no Ippo - Champion Road');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Micah MacGlory', '(The) Super Dimension Fortress Macross');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bernita Slay', 'Gintama');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Steve Maidlow', 'One Outs');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hyacintha Wandtke', 'Tiger y  Bunny');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cookie Canon', 'Black Lagoon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Reagan Potebury', 'Neon Genesis Evangelion');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Berrie Plummer', 'Fate/stay night: Unlimited Blade Works');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Waylon Foyston', 'Ghost in the Shell: Stand Alone Complex - Individual Eleven');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hedvige Fidian', '(The) Boy and The Beast');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Krystal Benitez', '(The) Anthem of the Heart');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lenore de Grey', 'Fate/Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Viv Gosart', 'Food Wars! Shokugeki no Soma');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tanney Weiser', 'Mobile Suit Gundam  Second Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gianni Boydle', 'Macross Frontier');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gwenneth Shercliff', 'Darker than Black');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jemimah Zuan', 'Nichijou - My Ordinary Life');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ketti Stigell', 'Space Brothers');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Caritta Robart', 'Gosick');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Pamella Pattingson', 'No Game, No Life Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Far Scarasbrick', 'One Punch Man');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sanders Kellar', 'Lupin III: The Castle of Cagliostro');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eustacia Orhtmann', 'Aria the Avvenire');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Berkie Blackett', 'Welcome to THE SPACE SHOW');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ilaire Mac', 'Denpa teki na Kanojo');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Zia Leat', 'Monthly Girls Nozaki-kun');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Moyna Mapledoram', 'Nobodys Boy Remi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Johnathan Lumby', 'Elfen Lied');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Valery Synder', 'Emma: A Victorian Romance Second Act');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lin Fuster', 'Kizumonogatari Part : Reiketsu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Boonie Blodgetts', 'My Hero Academia');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gareth Miranda', 'Rainbow - Nisha Rokubo no Shichinin');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mick Lovel', 'Wolfs Rain');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Abagail Haughan', 'No Game, No Life');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wheeler Ixer', 'Ghost in the Shell: Stand Alone Complex - The Laughing Man');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ned Sanbrook', 'Magical Girl Lyrical Nanoha the Movie nd As');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jerrie Mundall', 'Junjo Romantica');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marwin Tudbald', 'Tokyo Magnitude .');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Catriona Rebichon', 'Eureka Seven');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jackquelin Crush', 'School Rumble');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Edgardo Becraft', 'Parasyte -the maxim-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Fulvia Cassidy', 'Hinamatsuri');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lanette Pestricke', 'Kizumonogatari Part : Nekketsu (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bev Petrelli', 'Kill la Kill');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Vernice McEachern', 'Ghost in the Shell (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carey Whitehair', 'Puella Magi Madoka Magica the Movie Part : Eternal');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lucas Masselin', 'Now and Then, Here and There');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Timi Castilla', 'Berserk: The Golden Age Arc II - The Battle for Doldrey (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gayla Cleere', 'Puella Magi Madoka Magica the Movie Part : Beginnings');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carol-jean Budnik', 'Kizumonogatari Part : Tekketsu (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Reamonn Turnor', 'Wagnaria!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mackenzie Rohmer', 'Kimagure Orange Road: The Movie');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ranice Waplinton', 'Lovely Complex');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carlynn Perview', 'Porco Rosso (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Faith Landsberg', '(The) Place Promised in Our Early Days (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Murdoch Tembridge', 'Hikaru No Go: New Year Special');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Karylin Trent', 'planetarian: Hoshi no Hito (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ruy McDool', 'Mobile Suit Gundam - The Movie Trilogy');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rosita Kenelin', 'Hajime no Ippo - Mashiba vs. Kimura');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Raimundo Sturney', 'Puella Magi Madoka Magica The Movie Part : Rebellion');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nikolai Dowe', 'Cardcaptor Sakura Movie : The Sealed Card');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Irvin Dugget', '(The) Wind Rises (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Barrett Conradie', 'Legend of the Galactic Heroes: A Hundred Billion Stars, A Hundred Billion Lights');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Val Rickman', 'Detroit Metal City');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kerry Burder', '(The) Slayers Next');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ruthann Ganforthe', 'One Piece Film Strong World (movie )');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bradley Hayller', 'Strawberry Panic!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Geri Renzini', 'KenIchi the Mightiest Disciple');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gilles Ferrarotti', 'Princess Jellyfish');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rori Mates', 'Bamboo Blade');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wandis Andri', 'Initial D: Fourth Stage');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Agosto Jordine', 'Mobile Suit Gundam');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aurea Winsbury', 'Owarimonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Connie Brower', 'Bakuman.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Doretta Martineau', 'Silver Spoon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Constantino Fitzhenry', 'Hikaru no Go');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Clayborne Larenson', 'ReLIFE');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Holmes Antham', 'Hajime no Ippo Rising');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Noby Seeviour', 'Banner of the Stars II');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Demetris Roz', 'Higurashi no Naku Koroni Kai');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Winn Burcombe', 'Gunbuster');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Clifford Queree', 'ReLIFE');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Martainn Merali', 'Food Wars! The Second Plate');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kai Stempe', 'Case Closed: The Phantom of Baker Street (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Benito Creavan', 'Samurai');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eldridge Dukes', 'Voices of a Distant Star');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bronny Wissbey', 'lam Dunk');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Emlen Baumaier', 'Doraemon the Movie: Nobita and the Steel Troops: The New Age');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Roderic Burtonwood', '(The) Ancient Magus Bride');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Glori Fayter', 'Full Moon o Sagashite');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aldridge Chelsom', 'Miss Kobayashis Dragon Maid');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jean Maddocks', 'A Lull in the Sea');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jaimie Bernholt', 'Mobile Suit Zeta Gundam');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Catherina Banasevich', 'Psycho-Pass');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Beulah Gaynesford', 'Sayonara, Zetsubou-Sensei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Coleman Manass', '(The) Story of Saiunkoku Second Series');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jesse Salthouse', 'FLCL');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rheta Longbone', 'Treasure Island');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Crystie Drillingcourt', 'Case Closed: Captured in Her Eyes (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Myron Gustus', 'Case Closed: The Last Magician of the Century (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Valerye Ricart', '(The) Secret World of Arrietty (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Merry Nappin', 'Genshiken');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mandel Wogden', 'Touch (TV)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gunar Berrecloth', 'Kyo kara Maoh! rd Series');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tiebout Meiklem', 'Black Lagoon: Robertas Blood Trail');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wyndham Keinrat', 'Log Horizon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jamey Mouget', 'Genshiken');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Emmanuel Igoe', 'Big Windup! Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mirna Izzatt', 'Case Closed: Countdown to Heaven (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dmitri Pratley', 'Kaleido Star: Legend of Phoenix - Layla Hamilton Story');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gan Beartup', 'Saint Seiya: The Hades Chapter - Sanctuary');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jordan Valerius', 'Junjo Romantica');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Charita Akrigg', 'Aria - The Natural');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Berkeley Dawnay', 'Claymore');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Eberto Kloster', 'Zoku Sayonara Zetsubo Sensei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Myron Powys', 'Giant Robo');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hanna McClaren', 'Legend of the Galactic Heroes: Spiral Labyrinth');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bobina Deluce', 'Nisemonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kathrine Hartburn', 'Ace of Diamond: Second Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ermin Worlock', '(The) Garden of Sinners/recalled out summer (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Benn Grimsdike', 'Non Non Biyori Repeat');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Luther Giron', 'Fruits Basket');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Greg Crate', 'From Up On Poppy Hill (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rockey Mawhinney', 'Perfect Blue (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Adolph Harkes', 'When They Cry - Higurashi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kristian Blankley', 'Kimagure Orange Road');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carley Schruur', 'Birdy the Mighty Decode:');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ted Pettis', 'Penguindrum');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lebbie Cassedy', 'Soul Eater');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Asa Berringer', 'Full Metal Panic!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bronnie Caizley', 'Hanada Shonen-shi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Iolande Cowlard', 'Hare+Guu Deluxe');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Florentia Summerly', 'Baby Blue (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Glen Maystone', 'xxxHOLiC: Ro');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hermina Murrhaupt', 'Emma: A Victorian Romance');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dulcie Dufer', 'Macross Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Tiphany Dietmar', 'Space Battleship Yamato');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wendy Goodison', 'Fairy Tail Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Robyn Fligg', 'Mobile Suit Gundam: The Origin');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Vlad Chittenden', 'One Piece "DY" Ace no Shi wo Koete! Luffy Nakama to no Chikai');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Alon Newton', 'Chihayafuru');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lombard Lednor', '(The) Tatami Galaxy');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jacky Totman', 'Tamayura: Sotsugyo Shashin (movie series)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ernestine Leat', '(The) Vision of Escaflowne');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Stillmann Hue', 'Mobile Suit Gundam: Iron-Blooded Orphans');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dorelia Du Plantier', 'Magical Girl Lyrical Nanoha As');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Danice Stivey', 'Black Butler: Book of Murder');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sharleen Pessolt', '(The) Eccentric Family (TV)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Car Romanini', 'Read or Die');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Honor Titcomb', 'Durarara!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Myrle MacGlory', 'Broken Blade (movie series)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Johann Turnpenny', 'Yu Yu Hakusho: Ghost Files');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marina Penreth', 'Fate/stay night: Unlimited Blade Works');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Andrew Angear', 'Ga-Rei-Zero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jason Chupin', 'Macross Plus Movie Edition');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Suzie Crinson', 'Kaiji');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wadsworth Carefull', 'Gintama Season');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hussein Bartrum', 'Tsubasa: Spring Thunder');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Clerc Kirby', '(The) Story of Saiunkoku');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cristie Linley', 'Crest of the Stars');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ronni Hebblethwaite', 'On Your Mark (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Augustine Ligertwood', 'Urusei Yatsura: Beautiful Dreamer (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jewel Matousek', 'Gintama');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Windy Scipsey', 'Hanamonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ferrell Hutton', 'KONOSUBA - Gods blessing on this wonderful world!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Merralee Shrimptone', 'Toward the Terra');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Erie Gotcher', 'Mind Game (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ransom Mulvin', 'Genshiken');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Corny Crossfeld', 'Mobile Suit Gundam Seed');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Renaud Bortolazzi', 'Goku Sayonara Zetsubo Sensei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nonie Jerzyk', 'Daicon films (special)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lonny Santos', 'One Piece Film Z (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Paulina Hembrow', 'Baby Steps');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Maurine McCarver', 'City Hunter');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Alfi Bracco', 'Redline (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Edvard Pantridge', 'Big Windup!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nevins Flecknoe', 'Saga of Tanya the Evil');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jarid Hunte', 'Initial D: Second Stage');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Levi Gentile', 'K-ON! (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Perceval Di Biasio', 'InuYasha: The Final Act');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Patrick Graves', 'Jormungand Perfect Order');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Isidro Fehely', '(The) Dog of Flanders (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shandeigh Widdison', 'Maho Sensei Negima!: Mo Hitotsu no Sekai (OAV)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nicol Calcutt', 'Gintama: The Movie');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dulcea Toogood', '(The) Disastrous Life of Saiki K.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mariette Wornum', 'Lunar Legend Tsukihime');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Danita Winsiowiecki', 'Zan Sayonara Zetsubo Sensei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Perla Faccini', 'Rurouni Kenshin: Reflection');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Garth Reddihough', 'Hanasaku Iroha: Home Sweet Home (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mack Oxbury', 'Aggressive Retsuko');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Linette Puttick', 'Fate/stay night: Heavens Feel I. presage flower (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Moria Gunther', 'Kurenai');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nanine Bithany', 'Steins;Gate: The Movie - Load Region of Dejà Vu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kaylyn Okill', 'Kyousougiga');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dulcea Clitheroe', 'Girls Last Tour');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Laughton Remnant', 'Barakamon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Camilla Dunk', '(The) Irresponsible Captain Tylor');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lionel OBeirne', 'Death Parade');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Filide Gandley', 'Detective Conan: The Lost Ship in The Sky (movie )');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dixie Stonhard', 'Patema Inverted (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Melisenda Normanvill', 'Banner of the Stars');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marti Passie', 'Yona of the Dawn');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Adelle Blind', 'Revolutionary Girl Utena');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aluin Jessard', 'Hidamari Sketch × Honeycomb');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kimberley Ruffler', 'Wagnaria!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ossie Baldin', 'Barefoot Gen (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hadley Jesson', 'Children Who Chase Lost Voices');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Maxie Burgin', 'Case Closed: The Fourteenth Target');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Merrel Frediani', 'Ghost in the Shell S.A.C. Solid State Society D');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mellisa Bohike', 'My-HiME');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Rosalinde Langdale', 'Natsume Yujin-Cho: Itsuka Yuki no Hi ni');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Atlante True', 'Sound! Euphonium');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Perceval Hierro', 'Hozukis Coolheadedness');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sully Fallanche', 'One Piece');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dorita Drysdall', 'Shigofumi - Letters from the Departed');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gaston Francis', 'Trigun: Badlands Rumble');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Alexia Crossfield', 'Hidamari Sketch × Hoshimittsu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jessica Madgwich', 'INTERSTELLA : The tory of the ecret tar ystem');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kaye Ribou', 'Silver Spoon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carney Barnett', 'Lucky Star');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Guendolen Giannotti', 'Tsukimonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Fair Iacovaccio', 'RahXephon');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Billie Fitzsimon', 'My Teen Romantic Comedy SNAFU TOO!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Keane Khomich', 'Laid-Back Camp');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Analiese Maudlin', 'Gurren Lagann the Movie –Childhoods End-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Graehme Kubicek', 'Tsukigakirei');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Titos Maine', 'His and Her Circumstances');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Florida Baggiani', '(The) Seven Deadly Sins: Revival of The Commandments');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kevin Gair', 'Vampire Hunter D: Bloodlust');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Wendi Swettenham', 'Kobato.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Alicea Moggach', 'Berserk: The Golden Age Arc I - The Egg of the King');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Adella Bownass', 'Doukyusei -Classmates-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bord Strahan', 'House of Five Leaves');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Stacee Vaillant', 'School Rumble: Extra Class');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Fairfax Gleadhall', 'Nekomonogatari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Port Dumbell', 'Glass Mask');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Liam Friary', '(The) Ancient Magus Bride: Those Awaiting a Star');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Laurence Phillp', 'My Love Story!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Catharina Gronow', 'Ergo Proxy');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kynthia Wahlberg', 'Ghost in the Shell: Arise');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Andrei Sprott', 'Tenchi Muyo! Ryo-Ohki');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Shanna Stoven', 'Love, Chunibyo y  Other Delusions!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Niko Tinsley', 'Strawberry Marshmallow');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kristine Swadden', 'Initial D: Third Stage (movie)');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Carlota McCord', 'Master Keaton');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jessa Struijs', 'Banner of the Stars III');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mead Hughman', 'Attack on Titan: No Regrets');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marillin Bryning', 'Final Fantasy VII: Advent Children');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Allister Morrallee', 'Attack on Titan');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Onida Pollins', 'Fullmetal Alchemist: The Movie - Conqueror of Shamballa');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Bee Longfoot', 'Macross Plus');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hillyer Ayce', 'Hayate the Combat Butler!!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Hakim Younie', 'Daily Lives of High School Boys');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Aurore Sparks', 'Hyoka');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Brok Noblett', 'Hidamari Sketch: Sae/Hiro Sotsugyo-hen');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cecilio Riatt', 'Tekkonkinkreet');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Melva Drakard', 'Initial D: Final Stage');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gideon Findlay', 'Food Wars! The Third Plate');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cam Rothon', 'Tari Tari');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Michaela Geale', 'Detective Conan: The Private Eyes Requiem');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Moreen Janicek', 'Moshidora');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Dannie Pick', 'Shakugan no Shana');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jojo Yoxall', 'A Letter to Momo');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Margaux Estable', 'Rage of Bahamut: Genesis');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Mignon Frankton', 'Little Witch Academia');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Arleyne Coffelt', '(The) Cat Returns');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nolan Gristock', 'xxxHOLiC: Shunmuki');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Izabel Yeatman', 'xxxHOLiC: Ro Adayume');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Irvine Chewter', 'Kinos Travels: Life Goes On');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Titos MacKartan', 'Mobile Suit Gundam: The th MS Team');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jasun Secret', 'Heartcatch Precure! Hana no Miyako de Fashion Show…Desu ka!?');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Patti Allchorn', 'Sword Art Online the Movie: Ordinal Scale');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Allin Pocknell', 'JoJos Bizarre Adventure: Stardust Crusaders Egypt Arc');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Randy Veart', 'Kamichu!');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Devina O Timony', 'Hidamari Sketch × Hoshimittsu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Virgilio Champneys', 'GATE');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Perice Domel', 'Noein - to your other self');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Nye Messent', 'Seto no Hanayome');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Gare Ambrus', 'Hozuki no Reitetsu');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Celestina Huntly', 'Scrapped Princess');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Granger Fleis', 'Ushio y  Tora');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sonny Deane', 'Shonen Onmyouji');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Crystal Burnall', 'Food Wars! The Third Plate');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ellen Itscovitz', 'Zan Sayonara Zetsubo Sensei Bangai-chi');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ringo McGinly', 'Tiger y  Bunny The Movie -The Rising-');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Filbert Moller', 'White Album');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Ursulina Kyle', 'Full Metal Panic! The Second Raid');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Fabian Labusquiere', 'Tenchi Muyo! War on Geminar');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Jarred Grinaway', 'Hidamari Sketch ×');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Drucill Parnaby', 'Queen Millennia');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Sully Ralton', 'Megalobox');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Josefa Galia', 'Gunslinger Girl');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Baxie Waterhowse', '(The) Disastrous Life of Saiki K.');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Elfrieda Martinets', 'Inuyashiki Last Hero');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Vinita Dolligon', 'Colorful');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Loutitia Braban', 'Detective Conan: The Raven Chaser');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Vincent Kedslie', 'Another');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Woody Screen', 'Giovannis Island');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Joseph Ferriby', 'Planetarian');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Binny Burchnall', 'Full Metal Panic! Invisible Victory');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Cesya Itzkovwitch', 'Akira');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Marice Fredson', 'Blood+');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Callean Linder', 'Waiting in the Summer');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Stacia Gostyke', 'Strawberry Marshmallow');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Paco Fawcett', 'Fullmetal Alchemist: Brotherhood');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Lyda Tumber', 'Case Closed The Movie: The Time Bombed Skyscraper');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Janna Baldwin', 'Hi Score Girl');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Colene Kittoe', 'From the New World');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Daniel Kovelmann', 'Aria the Animation');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Annie Stockman', 'Detective Conan: Magician of the Silver Sky');
INSERT INTO personajes ( nombre , nombreanime) VALUES ( 'Kelvin Bicksteth', 'Macross Frontier: Itsuwari no Utahime');