INSERT INTO animes (nombre,genero) VALUES ('your name.' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Fullmetal Alchemist: Brotherhood' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Steins;Gate' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Clannad After Story' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Rurouni Kenshin: Trust y Betrayal' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Code Geass: Lelouch of the Rebellion R' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Spirited Away' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('A Silent Voice' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Cowboy Bebop' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Mushishi: The Next Chapter' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('(The) Disappearance of Haruhi Suzumiya' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Princess Mononoke' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('(The) Legend of the Galactic Heroes' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Mushi-Shi' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Death Note' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Maria Watches Over Us rd Season' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Made in Abyss' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Maria Watches Over Us Season : Printemps' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Code Geass: Lelouch of the Rebellion' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Gintama' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('anohana: The Flower We Saw That Day' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Descending Stories: Showa Genroku Rakugo Shinju' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Maria Watches Over Us th Season' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Gintama' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Gintama (movie)' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Bunny Drop' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Evangelion: . You Can (Not) Advance' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Monster' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Grave of the Fireflies' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Cross Game' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Stand Alone Complex nd GIG' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Summer Wars' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Fighting Spirit' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Fullmetal Alchemist' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Hunter × Hunter' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Nodame Cantabile' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('(The) Girl Who Leapt Through Time' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Centimeters Per Second' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Nausicaä of the Valley of the Wind' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Gurren Lagann' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('(The) Garden of Sinners' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Wolf Children' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('My Neighbor Totoro' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Baccano!' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Honey and Clover II' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Natsumes Book of Friends' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Gintama: The Final Movie' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Hajime no Ippo: New Challenger' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Kanon' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Star Blazers' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('GTO: Great Teacher Onizuka' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Kinos Journey' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Howls Moving Castle' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Time of Eve' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Puella Magi Madoka Magica' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Mushishi Tokubetsu-hen: Hihamukage' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Natsumes Book of Friends' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Millennium Actress' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Time of Eve' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Monogatari Series Second Season' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Kaleido Star' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Mononoke' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Kids on the Slope' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Natsumes Book of Friends' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('(The) Melancholy of Haruhi Suzumiya' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Gankutsuou: The Count of Monte Cristo' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Clannad' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Planetes' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('NANA' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Looking Up At The Half-Moon' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Castle in the Sky' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Your Lie in April' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Whisper of the Heart' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Samurai Champloo' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Ouran High School Host Club' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('A Place Further Than the Universe' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Gurren Lagann the Movie – The Lights in the Sky Are Stars' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('(The) Beast Player Erin' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Stand Alone Complex' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Maria Watches Over Us' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Aria the Origination' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Spice and Wolf II' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Angel Beats!' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Moribito - Guardian of the Spirit' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('March comes in like a lion' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Haikyu!! Second Season' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('My Hero Academia' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('ef: a tale of melodies' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('ef: a tale of memories' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Haikyu!!' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Black Lagoon: The Second Barrage' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Welcome to the NHK' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Re:ZERO -Starting Life in Another World-' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Legend of the Galactic Heroes: Overture to a New War' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Mushishi: Zoku-Sh?: Suzu no Shizuku' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('(The) Tale of the Princess Kaguya' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Honey and Clover' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Sword of the Stranger' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Haibane Renmei' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Sh?wa Genroku Rakugo Shinj?' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('(The) Twelve Kingdoms' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Hunter X Hunter' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('My Hero Academia' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Cowboy Bebop: The Movie' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Tokyo Godfathers' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Toradora!' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Romeo × Juliet' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Owarimonogatari' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Maison Ikkoku' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Major' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Evangelion: . You Are (Not) Alone' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Shirobako' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Hellsing Ultimate' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Chihayafuru' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Tsubasa Toyo Revelations' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Katanagatari' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam UC' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('(The) Garden of Words' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Full Metal Panic! The Second Raid' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Gintama.' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Hunter X Hunter' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Fate/Zero' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('ERASED' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('BECK: Mongolian Chop Squad' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Kimi ni Todoke - From Me to You' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('(La) Maison en Petits Cubes' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Den-noh Coil' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Bakuman' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('One Piece Episode of Nami: K?kaishi no Namida to Nakama no Kizuna' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Natsumes Book of Friends' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Attack on Titan' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('JoJos Bizarre Adventure: Diamond Is Unbreakable' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Nodame Cantabile: Paris' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Lupin the Third: Part' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Berserk' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Brave King GaoGaiGar Final' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Kaiba' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Ping Pong' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Princess Tutu' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Conan, the Boy in Future' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Hotarubi no Mori e' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Azumanga Daioh' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Full Metal Panic? Fumoffu' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Nodame Cantabile: Finale' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Eden of the East' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('(The) Rose of Versailles' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Mushishi Zoku-Sh? Tokubetsu-hen: Odoro no Michi' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('unter X Hunter: G I Final' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Haikyu!!' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Yuri!!! on Ice' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Girls und Panzer der Film' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Natsume Y?jin-Ch? Roku' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Mob Psycho' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Assassination Classroom' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Kimi ni Todoke nd Season' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Maquia - When the Promised Flower Blooms' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Hanasaku Iroha - Blossoms for Tomorrow' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Trigun' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Stand Alone Complex: Solid State Society' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Paprika' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Spice and Wolf' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Magnetic Rose' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('School Rumble: nd Semester' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('R.O.D -The TV-' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Violet Evergarden' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Ashita no Joe' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Sound! Euphonium' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Berserk: The Golden Age Arc III - The Advent' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('(The) Eccentric Family' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Gungrave' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Last Exile' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Bakuman.' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Rurouni Kenshin' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Legend of the Galactic Heroes: My Conquest is the Sea of Stars' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Comedy' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Land of the Lustrous' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('When Marnie Was There' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Skip Beat!' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Natsume Y?jin-Ch? Go' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('In This Corner of the World' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('xxxHOLiC: Kei' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Attack on Titan' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Neon Genesis Evangelion: The End of Evangelion' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Bakemonogatari' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('(The) Super Dimension Fortress Macross: Do You Remember Love?' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Master Keaton' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Kikis Delivery Service' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Hunter X Hunter: Greed Island' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Romeo and the Black Brothers' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Hajime no Ippo - Champion Road' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('(The) Super Dimension Fortress Macross' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Gintama' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('One Outs' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Tiger y Bunny' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Black Lagoon' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Neon Genesis Evangelion' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Fate/stay night: Unlimited Blade Works' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Stand Alone Complex - Individual Eleven' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('(The) Boy and The Beast' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('(The) Anthem of the Heart' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Fate/Zero' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Food Wars! Shokugeki no Soma' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam  Second Season' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Macross Frontier' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Darker than Black' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Nichijou - My Ordinary Life' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Space Brothers' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Gosick' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('No Game, No Life Zero' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('One Punch Man' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Lupin III: The Castle of Cagliostro' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Aria the Avvenire' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Welcome to THE SPACE SHOW' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Denpa teki na Kanojo' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Monthly Girls Nozaki-kun' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Nobodys Boy Remi' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Elfen Lied' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Emma: A Victorian Romance Second Act' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Kizumonogatari Part : Reiketsu' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('My Hero Academia' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Rainbow - Nisha Rokub? no Shichinin' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Wolfs Rain' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('No Game, No Life' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Stand Alone Complex - The Laughing Man' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Magical Girl Lyrical Nanoha the Movie nd As' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Junj? Romantica' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Tokyo Magnitude .' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Eureka Seven' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('School Rumble' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Parasyte -the maxim-' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Hinamatsuri' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Kizumonogatari Part : Nekketsu (movie)' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Kill la Kill' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell (movie)' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Puella Magi Madoka Magica the Movie Part : Eternal' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Now and Then, Here and There' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Berserk: The Golden Age Arc II - The Battle for Doldrey (movie)' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Puella Magi Madoka Magica the Movie Part : Beginnings' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Kizumonogatari Part : Tekketsu (movie)' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Wagnaria!!' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Kimagure Orange Road: The Movie' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Lovely Complex' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Porco Rosso (movie)' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('(The) Place Promised in Our Early Days (movie)' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Hikaru No Go: New Year Special' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('planetarian: Hoshi no Hito (movie)' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam - The Movie Trilogy' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Hajime no Ippo - Mashiba vs. Kimura' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Puella Magi Madoka Magica The Movie Part : Rebellion' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Cardcaptor Sakura Movie : The Sealed Card' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('(The) Wind Rises (movie)' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Legend of the Galactic Heroes: A Hundred Billion Stars, A Hundred Billion Lights' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Detroit Metal City' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('(The) Slayers Next' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('One Piece Film Strong World (movie )' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Strawberry Panic!' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('KenIchi the Mightiest Disciple' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Princess Jellyfish' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Bamboo Blade' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Initial D: Fourth Stage' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Owarimonogatari' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Bakuman.' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Silver Spoon' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Hikaru no Go' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('ReLIFE' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Hajime no Ippo Rising' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Banner of the Stars II' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Higurashi no Naku Koroni Kai' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Gunbuster' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('ReLIFE' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Food Wars! The Second Plate' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed: The Phantom of Baker Street (movie)' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Samurai' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Voices of a Distant Star' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('lam Dunk' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Doraemon the Movie: Nobita and the Steel Troops: The New Age' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('(The) Ancient Magus Bride' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Full Moon o Sagashite' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Miss Kobayashis Dragon Maid' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('A Lull in the Sea' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Zeta Gundam' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Psycho-Pass' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Sayonara, Zetsubou-Sensei' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('(The) Story of Saiunkoku Second Series' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('FLCL' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Treasure Island' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed: Captured in Her Eyes (movie)' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed: The Last Magician of the Century (movie)' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('(The) Secret World of Arrietty (movie)' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Genshiken' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Touch (TV)' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Kyo kara Maoh! rd Series' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Black Lagoon: Robertas Blood Trail' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Log Horizon' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Genshiken' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Big Windup! Season' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed: Countdown to Heaven (movie)' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Kaleido Star: Legend of Phoenix - Layla Hamilton Story' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Saint Seiya: The Hades Chapter - Sanctuary' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Junj? Romantica' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Aria - The Natural' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Claymore' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Zoku Sayonara Zetsub? Sensei' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Giant Robo' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Legend of the Galactic Heroes: Spiral Labyrinth' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Nisemonogatari' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Ace of Diamond: Second Season' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('(The) Garden of Sinners/recalled out summer (movie)' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Non Non Biyori Repeat' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Fruits Basket' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('From Up On Poppy Hill (movie)' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Perfect Blue (movie)' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('When They Cry - Higurashi' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Kimagure Orange Road' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Birdy the Mighty Decode:' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Penguindrum' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Soul Eater' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Full Metal Panic!' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Hanada Sh?nen-shi' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Hare+Guu Deluxe' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Baby Blue (movie)' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('xxxHOLiC: R?' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Emma: A Victorian Romance' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Macross Zero' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Space Battleship Yamato' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Fairy Tail Zero' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam: The Origin' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('One Piece "DY" Ace no Shi wo Koete! Luffy Nakama to no Chikai' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Chihayafuru' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('(The) Tatami Galaxy' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Tamayura: Sotsugy? Shashin (movie series)' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('(The) Vision of Escaflowne' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam: Iron-Blooded Orphans' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Magical Girl Lyrical Nanoha As' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Black Butler: Book of Murder' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('(The) Eccentric Family (TV)' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Read or Die' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Durarara!!' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Broken Blade (movie series)' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Yu Yu Hakusho: Ghost Files' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Fate/stay night: Unlimited Blade Works' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Ga-Rei-Zero' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Macross Plus Movie Edition' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Kaiji' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Gintama Season' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Tsubasa: Spring Thunder' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('(The) Story of Saiunkoku' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Crest of the Stars' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('On Your Mark (movie)' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Urusei Yatsura: Beautiful Dreamer (movie)' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Gintama' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Hanamonogatari' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('KONOSUBA - Gods blessing on this wonderful world!' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Toward the Terra' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Mind Game (movie)' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Genshiken' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam Seed' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Goku Sayonara Zetsub? Sensei' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Daicon films (special)' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('One Piece Film Z (movie)' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Baby Steps' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('City Hunter' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Redline (movie)' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Big Windup!' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Saga of Tanya the Evil' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Initial D: Second Stage' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('K-ON! (movie)' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('InuYasha: The Final Act' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Jormungand Perfect Order' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('(The) Dog of Flanders (movie)' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Mah? Sensei Negima!: M? Hitotsu no Sekai (OAV)' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Gintama: The Movie' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('(The) Disastrous Life of Saiki K.' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Lunar Legend Tsukihime' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Zan Sayonara Zetsub? Sensei' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Rurouni Kenshin: Reflection' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Hanasaku Iroha: Home Sweet Home (movie)' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Aggressive Retsuko' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Fate/stay night: Heavens Feel I. presage flower (movie)' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Kurenai' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Steins;Gate: The Movie - Load Region of Dejà Vu' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Kyousougiga' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Girls Last Tour' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Barakamon' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('(The) Irresponsible Captain Tylor' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Death Parade' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Detective Conan: The Lost Ship in The Sky (movie )' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Patema Inverted (movie)' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Banner of the Stars' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Yona of the Dawn' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Revolutionary Girl Utena' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Hidamari Sketch × Honeycomb' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Wagnaria!!' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Barefoot Gen (movie)' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Children Who Chase Lost Voices' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed: The Fourteenth Target' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell S.A.C. Solid State Society D' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('My-HiME' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Natsume Y?jin-Ch?: Itsuka Yuki no Hi ni' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Sound! Euphonium' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Hozukis Coolheadedness' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('One Piece' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Shigofumi - Letters from the Departed' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Trigun: Badlands Rumble' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Hidamari Sketch × Hoshimittsu' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('INTERSTELLA : The tory of the ecret tar ystem' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Silver Spoon' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Lucky Star' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Tsukimonogatari' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('RahXephon' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('My Teen Romantic Comedy SNAFU TOO!' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Laid-Back Camp' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Gurren Lagann the Movie –Childhoods End-' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Tsukigakirei' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('His and Her Circumstances' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('(The) Seven Deadly Sins: Revival of The Commandments' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Vampire Hunter D: Bloodlust' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Kobato.' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Berserk: The Golden Age Arc I - The Egg of the King' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Doukyusei -Classmates-' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('House of Five Leaves' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('School Rumble: Extra Class' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Nekomonogatari' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Glass Mask' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('(The) Ancient Magus Bride: Those Awaiting a Star' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('My Love Story!!' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Ergo Proxy' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Ghost in the Shell: Arise' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Tenchi Muyo! Ryo-Ohki' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Love, Chunibyo y Other Delusions!' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('Strawberry Marshmallow' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Initial D: Third Stage (movie)' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Master Keaton' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Banner of the Stars III' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Attack on Titan: No Regrets' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Final Fantasy VII: Advent Children' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Attack on Titan' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Fullmetal Alchemist: The Movie - Conqueror of Shamballa' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Macross Plus' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Hayate the Combat Butler!!' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Daily Lives of High School Boys' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Hy?ka' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Hidamari Sketch: Sae/Hiro Sotsugy?-hen' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Tekkonkinkreet' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Initial D: Final Stage' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Food Wars! The Third Plate' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Tari Tari' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Detective Conan: The Private Eyes Requiem' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('Moshidora' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Shakugan no Shana' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('A Letter to Momo' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Rage of Bahamut: Genesis' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Little Witch Academia' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('(The) Cat Returns' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('xxxHOLiC: Shunmuki' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('xxxHOLiC: R? Adayume' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Kinos Travels: Life Goes On' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Mobile Suit Gundam: The th MS Team' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Heartcatch Precure! Hana no Miyako de Fashion Show…Desu ka!?' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Sword Art Online the Movie: Ordinal Scale' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('JoJos Bizarre Adventure: Stardust Crusaders Egypt Arc' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Kamichu!' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Hidamari Sketch × Hoshimittsu' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('GATE' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Noein - to your other self' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Seto no Hanayome' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('H?zuki no Reitetsu' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Scrapped Princess' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Ushio y Tora' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Shonen Onmyouji' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('Food Wars! The Third Plate' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Zan Sayonara Zetsub? Sensei Bangai-chi' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Tiger y Bunny The Movie -The Rising-' , 'Moe');
INSERT INTO animes (nombre,genero) VALUES ('White Album' , 'Gore');
INSERT INTO animes (nombre,genero) VALUES ('Full Metal Panic! The Second Raid' , 'Kodomo');
INSERT INTO animes (nombre,genero) VALUES ('Tenchi Muyo! War on Geminar' , 'Shonen');
INSERT INTO animes (nombre,genero) VALUES ('Hidamari Sketch ×' , 'Sh?jo');
INSERT INTO animes (nombre,genero) VALUES ('Queen Millennia' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Megalobox' , 'Josei');
INSERT INTO animes (nombre,genero) VALUES ('Gunslinger Girl' , 'Mahô shôjo');
INSERT INTO animes (nombre,genero) VALUES ('(The) Disastrous Life of Saiki K.' , 'Mecha');
INSERT INTO animes (nombre,genero) VALUES ('Inuyashiki Last Hero' , 'Sentai');
INSERT INTO animes (nombre,genero) VALUES ('Colorful' , 'Spokon');
INSERT INTO animes (nombre,genero) VALUES ('Detective Conan: The Raven Chaser' , 'Post-apocaliptico');
INSERT INTO animes (nombre,genero) VALUES ('Another' , 'Meitantei');
INSERT INTO animes (nombre,genero) VALUES ('Giovannis Island' , 'Sh?nen-ai y Yaoi');
INSERT INTO animes (nombre,genero) VALUES ('Planetarian' , 'Sh?jo-ai y Yuri');
INSERT INTO animes (nombre,genero) VALUES ('Full Metal Panic! Invisible Victory' , 'Hentai');
INSERT INTO animes (nombre,genero) VALUES ('Akira' , 'Ecchi');
INSERT INTO animes (nombre,genero) VALUES ('Blood+' , 'Harem');
INSERT INTO animes (nombre,genero) VALUES ('Waiting in the Summer' , 'Harem Reverso');
INSERT INTO animes (nombre,genero) VALUES ('Strawberry Marshmallow' , 'Magical Girlfriend');
INSERT INTO animes (nombre,genero) VALUES ('Fullmetal Alchemist: Brotherhood' , 'Anime progresivo');
INSERT INTO animes (nombre,genero) VALUES ('Case Closed The Movie: The Time Bombed Skyscraper' , 'Bish?jo');
INSERT INTO animes (nombre,genero) VALUES ('Hi Score Girl' , 'Bish?nen');
INSERT INTO animes (nombre,genero) VALUES ('From the New World' , 'Kemono');
INSERT INTO animes (nombre,genero) VALUES ('Aria the Animation' , 'Super deformed');
INSERT INTO animes (nombre,genero) VALUES ('Detective Conan: Magician of the Silver Sky' , 'Seinen');
INSERT INTO animes (nombre,genero) VALUES ('Macross Frontier: Itsuwari no Utahime' , 'Gore');