INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'your name.');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Fullmetal Alchemist: Brotherhood');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Steins;Gate');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Clannad After Story');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Rurouni Kenshin: Trust y  Betrayal');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Code Geass: Lelouch of the Rebellion R');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Spirited Away');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'A Silent Voice');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Cowboy Bebop');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Mushishi: The Next Chapter');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Disappearance of Haruhi Suzumiya');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Princess Mononoke');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', '(The) Legend of the Galactic Heroes');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Mushi-Shi');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Death Note');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Maria Watches Over Us rd Season');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Made in Abyss');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Maria Watches Over Us Season : Printemps');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Code Geass: Lelouch of the Rebellion');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Gintama');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'anohana: The Flower We Saw That Day');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Descending Stories: Showa Genroku Rakugo Shinju');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Maria Watches Over Us th Season');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Gintama');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Gintama (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Bunny Drop');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Evangelion: . You Can (Not) Advance');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Monster');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Grave of the Fireflies');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Cross Game');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Ghost in the Shell: Stand Alone Complex nd GIG');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Summer Wars');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Fighting Spirit');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Fullmetal Alchemist');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Hunter × Hunter');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Nodame Cantabile');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', '(The) Girl Who Leapt Through Time');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Centimeters Per Second');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Nausicaä of the Valley of the Wind');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Gurren Lagann');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Garden of Sinners');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Wolf Children');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'My Neighbor Totoro');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Baccano!');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Honey and Clover II');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Natsumes Book of Friends');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Gintama: The Final Movie');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hajime no Ippo: New Challenger');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Kanon');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Star Blazers');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'GTO: Great Teacher Onizuka');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Kinos Journey');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Howls Moving Castle');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Time of Eve');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Puella Magi Madoka Magica');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Mushishi Tokubetsu-hen: Hihamukage');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Natsumes Book of Friends');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Millennium Actress');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Time of Eve');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Monogatari Series Second Season');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Kaleido Star');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Mononoke');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Kids on the Slope');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Natsumes Book of Friends');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', '(The) Melancholy of Haruhi Suzumiya');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Gankutsuou: The Count of Monte Cristo');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Clannad');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Planetes');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'NANA');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Looking Up At The Half-Moon');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Castle in the Sky');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Your Lie in April');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Whisper of the Heart');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Samurai Champloo');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Ouran High School Host Club');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'A Place Further Than the Universe');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Gurren Lagann the Movie – The Lights in the Sky Are Stars');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', '(The) Beast Player Erin');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Ghost in the Shell: Stand Alone Complex');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Maria Watches Over Us');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Aria the Origination');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Spice and Wolf II');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Angel Beats!');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Moribito - Guardian of the Spirit');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'March comes in like a lion');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Haikyu!! Second Season');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'My Hero Academia');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'ef: a tale of melodies');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'ef: a tale of memories');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Haikyu!!');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Black Lagoon: The Second Barrage');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Welcome to the NHK');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Re:ZERO -Starting Life in Another World-');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Legend of the Galactic Heroes: Overture to a New War');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Mushishi: Zoku-Shō: Suzu no Shizuku');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', '(The) Tale of the Princess Kaguya');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Honey and Clover');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Sword of the Stranger');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Haibane Renmei');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Shōwa Genroku Rakugo Shinjū');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Twelve Kingdoms');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Hunter X Hunter');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'My Hero Academia');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Cowboy Bebop: The Movie');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Tokyo Godfathers');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Toradora!');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Romeo × Juliet');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Owarimonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Maison Ikkoku');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Major');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Evangelion: . You Are (Not) Alone');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Shirobako');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Hellsing Ultimate');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Chihayafuru');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Tsubasa Toyo Revelations');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Katanagatari');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Mobile Suit Gundam UC');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', '(The) Garden of Words');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Full Metal Panic! The Second Raid');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Gintama.');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Hunter X Hunter');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Fate/Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'ERASED');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'BECK: Mongolian Chop Squad');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Kimi ni Todoke - From Me to You');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', '(La) Maison en Petits Cubes');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Den-noh Coil');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Bakuman');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'One Piece Episode of Nami: Kōkaishi no Namida to Nakama no Kizuna');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Natsumes Book of Friends');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Attack on Titan');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'JoJos Bizarre Adventure: Diamond Is Unbreakable');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Nodame Cantabile: Paris');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Lupin the Third: Part');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Berserk');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Brave King GaoGaiGar Final');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Kaiba');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Ping Pong');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Princess Tutu');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Conan, the Boy in Future');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Hotarubi no Mori e');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Azumanga Daioh');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Full Metal Panic? Fumoffu');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Nodame Cantabile: Finale');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Eden of the East');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', '(The) Rose of Versailles');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Mushishi Zoku-Shō Tokubetsu-hen: Odoro no Michi');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'unter X Hunter: G I Final');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Haikyu!!');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Yuri!!! on Ice');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Girls und Panzer der Film');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Natsume Yūjin-Chō Roku');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Mob Psycho');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Assassination Classroom');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Kimi ni Todoke nd Season');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Maquia - When the Promised Flower Blooms');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Hanasaku Iroha - Blossoms for Tomorrow');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Trigun');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Ghost in the Shell: Stand Alone Complex: Solid State Society');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Paprika');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Spice and Wolf');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Magnetic Rose');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'School Rumble: nd Semester');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'R.O.D -The TV-');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Violet Evergarden');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Ashita no Joe');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Sound! Euphonium');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Berserk: The Golden Age Arc III - The Advent');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', '(The) Eccentric Family');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Gungrave');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Last Exile');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Bakuman.');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Rurouni Kenshin');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Legend of the Galactic Heroes: My Conquest is the Sea of Stars');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Comedy');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Land of the Lustrous');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'When Marnie Was There');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Skip Beat!');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Natsume Yūjin-Chō Go');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'In This Corner of the World');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'xxxHOLiC: Kei');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Attack on Titan');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Neon Genesis Evangelion: The End of Evangelion');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Bakemonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', '(The) Super Dimension Fortress Macross: Do You Remember Love?');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Master Keaton');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Kikis Delivery Service');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hunter X Hunter: Greed Island');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Romeo and the Black Brothers');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Hajime no Ippo - Champion Road');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Super Dimension Fortress Macross');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Gintama');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'One Outs');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Tiger y  Bunny');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Black Lagoon');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Neon Genesis Evangelion');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Fate/stay night: Unlimited Blade Works');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Ghost in the Shell: Stand Alone Complex - Individual Eleven');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', '(The) Boy and The Beast');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', '(The) Anthem of the Heart');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Fate/Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Food Wars! Shokugeki no Soma');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Mobile Suit Gundam  Second Season');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Macross Frontier');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Darker than Black');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Nichijou - My Ordinary Life');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Space Brothers');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Gosick');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'No Game, No Life Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'One Punch Man');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Lupin III: The Castle of Cagliostro');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Aria the Avvenire');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Welcome to THE SPACE SHOW');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Denpa teki na Kanojo');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Monthly Girls Nozaki-kun');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Nobodys Boy Remi');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Elfen Lied');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Emma: A Victorian Romance Second Act');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Kizumonogatari Part : Reiketsu');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'My Hero Academia');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Rainbow - Nisha Rokubō no Shichinin');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Wolfs Rain');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'No Game, No Life');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Ghost in the Shell: Stand Alone Complex - The Laughing Man');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Magical Girl Lyrical Nanoha the Movie nd As');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Junjō Romantica');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Tokyo Magnitude .');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Eureka Seven');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'School Rumble');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Parasyte -the maxim-');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Hinamatsuri');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Kizumonogatari Part : Nekketsu (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Kill la Kill');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Ghost in the Shell (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Puella Magi Madoka Magica the Movie Part : Eternal');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Now and Then, Here and There');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Berserk: The Golden Age Arc II - The Battle for Doldrey (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Puella Magi Madoka Magica the Movie Part : Beginnings');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Kizumonogatari Part : Tekketsu (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Wagnaria!!');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Kimagure Orange Road: The Movie');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Lovely Complex');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Porco Rosso (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', '(The) Place Promised in Our Early Days (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Hikaru No Go: New Year Special');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'planetarian: Hoshi no Hito (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Mobile Suit Gundam - The Movie Trilogy');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hajime no Ippo - Mashiba vs. Kimura');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Puella Magi Madoka Magica The Movie Part : Rebellion');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Cardcaptor Sakura Movie : The Sealed Card');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Wind Rises (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Legend of the Galactic Heroes: A Hundred Billion Stars, A Hundred Billion Lights');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Detroit Metal City');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', '(The) Slayers Next');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'One Piece Film Strong World (movie )');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Strawberry Panic!');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'KenIchi the Mightiest Disciple');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Princess Jellyfish');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Bamboo Blade');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Initial D: Fourth Stage');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Mobile Suit Gundam');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Owarimonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Bakuman.');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Silver Spoon');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Hikaru no Go');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'ReLIFE');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Hajime no Ippo Rising');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Banner of the Stars II');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Higurashi no Naku Koroni Kai');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Gunbuster');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'ReLIFE');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Food Wars! The Second Plate');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Case Closed: The Phantom of Baker Street (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Samurai');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Voices of a Distant Star');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'lam Dunk');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Doraemon the Movie: Nobita and the Steel Troops: The New Age');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', '(The) Ancient Magus Bride');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Full Moon o Sagashite');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Miss Kobayashis Dragon Maid');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'A Lull in the Sea');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Mobile Suit Zeta Gundam');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Psycho-Pass');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Sayonara, Zetsubou-Sensei');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', '(The) Story of Saiunkoku Second Series');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'FLCL');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Treasure Island');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Case Closed: Captured in Her Eyes (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Case Closed: The Last Magician of the Century (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', '(The) Secret World of Arrietty (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Genshiken');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Touch (TV)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Kyo kara Maoh! rd Series');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Black Lagoon: Robertas Blood Trail');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Log Horizon');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Genshiken');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Big Windup! Season');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Case Closed: Countdown to Heaven (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Kaleido Star: Legend of Phoenix - Layla Hamilton Story');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Saint Seiya: The Hades Chapter - Sanctuary');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Junjō Romantica');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Aria - The Natural');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Claymore');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Zoku Sayonara Zetsubō Sensei');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Giant Robo');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Legend of the Galactic Heroes: Spiral Labyrinth');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Nisemonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Ace of Diamond: Second Season');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', '(The) Garden of Sinners/recalled out summer (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Non Non Biyori Repeat');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Fruits Basket');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'From Up On Poppy Hill (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Perfect Blue (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'When They Cry - Higurashi');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Kimagure Orange Road');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Birdy the Mighty Decode:');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Penguindrum');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Soul Eater');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Full Metal Panic!');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Hanada Shōnen-shi');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Hare+Guu Deluxe');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Baby Blue (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'xxxHOLiC: Rō');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Emma: A Victorian Romance');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Macross Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Space Battleship Yamato');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Fairy Tail Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Mobile Suit Gundam: The Origin');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'One Piece "DY" Ace no Shi wo Koete! Luffy Nakama to no Chikai');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Chihayafuru');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Tatami Galaxy');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Tamayura: Sotsugyō Shashin (movie series)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', '(The) Vision of Escaflowne');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Mobile Suit Gundam: Iron-Blooded Orphans');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Magical Girl Lyrical Nanoha As');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Black Butler: Book of Murder');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', '(The) Eccentric Family (TV)');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Read or Die');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Durarara!!');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Broken Blade (movie series)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Yu Yu Hakusho: Ghost Files');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Fate/stay night: Unlimited Blade Works');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Ga-Rei-Zero');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Macross Plus Movie Edition');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Kaiji');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Gintama Season');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Tsubasa: Spring Thunder');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', '(The) Story of Saiunkoku');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Crest of the Stars');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'On Your Mark (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Urusei Yatsura: Beautiful Dreamer (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Gintama');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Hanamonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'KONOSUBA - Gods blessing on this wonderful world!');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Toward the Terra');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Mind Game (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Genshiken');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Mobile Suit Gundam Seed');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Goku Sayonara Zetsubō Sensei');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Daicon films (special)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'One Piece Film Z (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Baby Steps');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'City Hunter');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Redline (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Big Windup!');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Saga of Tanya the Evil');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Initial D: Second Stage');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'K-ON! (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'InuYasha: The Final Act');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Jormungand Perfect Order');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', '(The) Dog of Flanders (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Mahō Sensei Negima!: Mō Hitotsu no Sekai (OAV)');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Gintama: The Movie');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', '(The) Disastrous Life of Saiki K.');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Lunar Legend Tsukihime');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Zan Sayonara Zetsubō Sensei');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Rurouni Kenshin: Reflection');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hanasaku Iroha: Home Sweet Home (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Aggressive Retsuko');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Fate/stay night: Heavens Feel I. presage flower (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Kurenai');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Steins;Gate: The Movie - Load Region of Dejà Vu');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Kyousougiga');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Girls Last Tour');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Barakamon');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', '(The) Irresponsible Captain Tylor');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Death Parade');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Detective Conan: The Lost Ship in The Sky (movie )');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Patema Inverted (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Banner of the Stars');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Yona of the Dawn');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Revolutionary Girl Utena');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Hidamari Sketch × Honeycomb');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Wagnaria!!');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Barefoot Gen (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Children Who Chase Lost Voices');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Case Closed: The Fourteenth Target');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Ghost in the Shell S.A.C. Solid State Society D');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'My-HiME');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Natsume Yūjin-Chō: Itsuka Yuki no Hi ni');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Sound! Euphonium');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Hozukis Coolheadedness');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'One Piece');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Shigofumi - Letters from the Departed');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Trigun: Badlands Rumble');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Hidamari Sketch × Hoshimittsu');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'INTERSTELLA : The tory of the ecret tar ystem');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Silver Spoon');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Lucky Star');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Tsukimonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'RahXephon');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'My Teen Romantic Comedy SNAFU TOO!');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Laid-Back Camp');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Gurren Lagann the Movie –Childhoods End-');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Tsukigakirei');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'His and Her Circumstances');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', '(The) Seven Deadly Sins: Revival of The Commandments');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Vampire Hunter D: Bloodlust');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Kobato.');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Berserk: The Golden Age Arc I - The Egg of the King');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Doukyusei -Classmates-');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'House of Five Leaves');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'School Rumble: Extra Class');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Nekomonogatari');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Glass Mask');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', '(The) Ancient Magus Bride: Those Awaiting a Star');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'My Love Story!!');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Ergo Proxy');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Ghost in the Shell: Arise');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Tenchi Muyo! Ryo-Ohki');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Love, Chunibyo y  Other Delusions!');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Strawberry Marshmallow');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Initial D: Third Stage (movie)');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Master Keaton');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Banner of the Stars III');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Attack on Titan: No Regrets');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Final Fantasy VII: Advent Children');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Attack on Titan');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Fullmetal Alchemist: The Movie - Conqueror of Shamballa');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Macross Plus');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Hayate the Combat Butler!!');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Daily Lives of High School Boys');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Hyōka');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Hidamari Sketch: Sae/Hiro Sotsugyō-hen');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Tekkonkinkreet');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Initial D: Final Stage');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Food Wars! The Third Plate');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Tari Tari');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Detective Conan: The Private Eyes Requiem');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Moshidora');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Shakugan no Shana');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'A Letter to Momo');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Rage of Bahamut: Genesis');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Little Witch Academia');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', '(The) Cat Returns');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'xxxHOLiC: Shunmuki');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'xxxHOLiC: Rō Adayume');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Kinos Travels: Life Goes On');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Mobile Suit Gundam: The th MS Team');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Heartcatch Precure! Hana no Miyako de Fashion Show…Desu ka!?');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Sword Art Online the Movie: Ordinal Scale');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'JoJos Bizarre Adventure: Stardust Crusaders Egypt Arc');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Kamichu!');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Hidamari Sketch × Hoshimittsu');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'GATE');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Noein - to your other self');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Seto no Hanayome');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hōzuki no Reitetsu');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Scrapped Princess');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Ushio y  Tora');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Shonen Onmyouji');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Food Wars! The Third Plate');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Zan Sayonara Zetsubō Sensei Bangai-chi');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Tiger y  Bunny The Movie -The Rising-');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'White Album');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Full Metal Panic! The Second Raid');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Tenchi Muyo! War on Geminar');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Hidamari Sketch ×');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Queen Millennia');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Megalobox');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Gunslinger Girl');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', '(The) Disastrous Life of Saiki K.');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Inuyashiki Last Hero');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Colorful');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Detective Conan: The Raven Chaser');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Another');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'Giovannis Island');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Planetarian');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Full Metal Panic! Invisible Victory');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Akira');
INSERT INTO ropa (categoria,anime) VALUES ('Pantalon', 'Blood+');
INSERT INTO ropa (categoria,anime) VALUES ('Camisa', 'Waiting in the Summer');
INSERT INTO ropa (categoria,anime) VALUES ('Camiseta', 'Strawberry Marshmallow');
INSERT INTO ropa (categoria,anime) VALUES ('Saco', 'Fullmetal Alchemist: Brotherhood');
INSERT INTO ropa (categoria,anime) VALUES ('Medias', 'Case Closed The Movie: The Time Bombed Skyscraper');
INSERT INTO ropa (categoria,anime) VALUES ('Gorro', 'Hi Score Girl');
INSERT INTO ropa (categoria,anime) VALUES ('Chaqueta', 'From the New World');
INSERT INTO ropa (categoria,anime) VALUES ('Gorra', 'Aria the Animation');
INSERT INTO ropa (categoria,anime) VALUES ('Pantaloneta', 'Detective Conan: Magician of the Silver Sky');
INSERT INTO ropa (categoria,anime) VALUES ('Bufanda', 'Macross Frontier: Itsuwari no Utahime');