CREATE OR REPLACE PACKAGE PC_PROFESORES IS
    PROCEDURE AD_PROFESORES(XNAME IN VARCHAR, XVIDA IN XMLTYPE);
    PROCEDURE EL_PROFESORES(XID IN VARCHAR);
    PROCEDURE MO_PROFESORES(XID IN VARCHAR,XNAME IN VARCHAR);
    FUNCTION CO_PROFESORES(PROID IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_HOJAVIDA(PROFID IN VARCHAR) RETURN XMLTYPE;
    FUNCTION CO_TIEMPO RETURN SYS_REFCURSOR;
END PC_PROFESORES;
/
CREATE OR REPLACE PACKAGE PC_TALLERES IS
    PROCEDURE AD_TALLERES(xid IN VARCHAR,xmodle IN VARCHAR,xkind IN CHAR,xdow IN VARCHAR,xtod IN VARCHAR,xduration IN NUMBER,xroom IN VARCHAR);
    FUNCTION CO_TALLERES(tallid IN VARCHAR) RETURN SYS_REFCURSOR;
END PC_TALLERES;
/
