/*INSERT INTO MBDAA01.DATOS VALUES('carlos.murillo-i@mail.escuelaing.edu.co','Carlos Murillo','Colombia','manuel.murillo.1999@gmail.com',NULL,NULL);
INSERT INTO MBDAA01.DATOS VALUES('miguel.sanchez-g@mail.escuelaing.edu.co','Miguel Sanchez','Colombia','miguel.sanchez@gmail.com',NULL,NULL);


DELETE FROM MBDAA01.DATOS WHERE CORREO = 'miguel.sanchez-g@mail.escuelaing.edu.co';
UPDATE MBDAA01.DATOS SET CORREO = ':3' WHERE CORREO = 'carlos.murillo-i@mail.escuelaing.edu.co';


GRANT UPDATE, DELETE
ON MBDAA01.DATOS
TO MIGUEL;
*/
CREATE TABLE DATOS(
    CORREO VARCHAR2(50),
    NOMBRE VARCHAR2(50),
    PAIS VARCHAR2(50) ,
    EMAIL VARCHAR(50) ,
    TAMA_O VARCHAR2(50),
    URL VARCHAR2(50)
    );
   
INSERT INTO DATOS
SELECT mb.CORREO, mb.NOMBRE, mb.PAIS, mb.EMAIL, mb.TAMA_O, mb.URL
FROM MBDAA01.DATOS mb;

/
CREATE OR REPLACE PACKAGE PC_VALIDACIONES IS
	PROCEDURE AD_CORREO(XCORREO IN VARCHAR);
	PROCEDURE AD_FECHA(XFECHA IN DATE);
	PROCEDURE AD_JUSTIFICACION(XJUSTIFICACION IN VARCHAR);
	PROCEDURE AD_ESTADO(XESTADO IN VARCHAR);
	PROCEDURE AD_CODIGO(XCODIGO IN NUMBER);
    PROCEDURE MO_JUSTIFICACION(XNUMERO IN NUMBER, XJUSTIDFICACION IN VARCHAR);
    PROCEDURE MO_EVIDENCIA(XNUMERO IN NUMBER,XEVIDENCIA IN VARCHAR);
    PROCEDURE MO_ESTADO(XNUMERO IN NUMBER,XESTADO IN CHAR);
END PC_VALIDACIONES;
/
CREATE OR REPLACE PACKAGE PC_LOGROS IS
	PROCEDURE AD_CORREO(XCORREO IN VARCHAR);
	PROCEDURE AD_CATEGORIA(XCATEGORIA IN CHAR);
	PROCEDURE AD_NOMBRE(XNOMBRE IN VARCHAR);
	PROCEDURE AD_FECHA(XFECHA IN DATE);
    PROCEDURE MO_CATEGORIA(XCATEGORIA IN VARCHAR);
END PC_LOGROS;
/