CREATE OR REPLACE PACKAGE BODY PA_ENCPRODUCTOS IS
	PROCEDURE AD_ANIME(XNOMBRE IN VARCHAR, XGENERO IN VARCHAR) IS
	BEGIN
		PC_PRODUCTOS.AD_ANIME(XNOMBRE,XGENERO);
	END AD_ANIME;
	
    PROCEDURE AD_FIGURA(XPERANIME IN VARCHAR, XTAMA_O IN VARCHAR) IS
	BEGIN
		PC_PRODUCTOS.AD_FIGURA(XPERANIME,XTAMA_O);
	END AD_FIGURA;
	
    PROCEDURE AD_PRODUCCIONES(XAUTOR IN NUMBER, XANIME IN NUMBER) IS
	BEGIN
		PC_PRODUCTOS.AD_PRODUCCIONES(XAUTOR,XANIME);
	END AD_PRODUCCIONES;
	
    PROCEDURE AD_ELENCOS(XANIME IN NUMBER, XPERSONAJES IN NUMBER) IS
	BEGIN
		PC_PRODUCTOS.AD_ELENCOS(XANIME,XPERSONAJES);
	END AD_ELENCOS;
	
    PROCEDURE AD_INVENTARIO(XANIME IN NUMBER, XFIGURA IN NUMBER) IS
	BEGIN
		PC_PRODUCTOS.AD_INVENTARIO(XANIME,XFIGURA);
	END AD_INVENTARIO;
	
    PROCEDURE AD_PERSONAJE(XNOMBRE IN VARCHAR, XNOMBREANIMES IN VARCHAR) IS
	BEGIN
		PC_PRODUCTOS.AD_PERSONAJE(XNOMBRE,XNOMBREANIMES);
	END AD_PERSONAJE;
	
    PROCEDURE AD_AUTOR(XNOMBRE IN VARCHAR) IS
	BEGIN
		PC_PRODUCTOS.AD_AUTOR(XNOMBRE);
	END AD_AUTOR;
	
    PROCEDURE AD_ROPA(XCATEGORIA IN VARCHAR, XANIME IN VARCHAR) IS
	BEGIN
		PC_PRODUCTOS.AD_ROPA(XCATEGORIA,XANIME);
	END AD_ROPA;
	
    PROCEDURE AD_EJEMPLAR(XCANTIDAD IN VARCHAR, XPRECIO IN VARCHAR, XFIGURA IN VARCHAR, XROPA IN VARCHAR, XANIME IN VARCHAR, XVENTA IN VARCHAR, XSEDE IN VARCHAR) IS
	BEGIN
		PC_PRODUCTOS.AD_EJEMPLAR(XCANTIDAD,XPRECIO,XFIGURA,XROPA,XANIME,XVENTA,XSEDE);
	END AD_EJEMPLAR;
	
	PROCEDURE EL_FIGURA(XID IN NUMBER) IS
	BEGIN
		PC_PRODUCTOS.EL_FIGURA(XID);
	END EL_FIGURA;
	
	PROCEDURE EL_ROPA(XID IN NUMBER) IS
	BEGIN
		PC_PRODUCTOS.EL_ROPA(XID);
	END EL_ROPA;
	
	FUNCTION CON_ANIME_GENERO(XGENERO IN VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_PRODUCTOS.CON_ANIME_GENERO(XGENERO);
		RETURN CONSULTA;
	END;
	
    FUNCTION CONSULTAR_FIGURA(XGENERO IN VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_PRODUCTOS.CONSULTAR_FIGURA(XGENERO);
		RETURN CONSULTA;
	END;
	
    FUNCTION CON_ANIME_AUTOR(XAUTORES IN VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_PRODUCTOS.CON_ANIME_AUTOR(XAUTORES);
		RETURN CONSULTA;
	END;
	
    FUNCTION CON_ANIME_ROPA(XANIME IN VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_PRODUCTOS.CON_ANIME_ROPA(XANIME);
		RETURN CONSULTA;
	END;
    
    FUNCTION CON_MAX_EJEMPLARES RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_PRODUCTOS.CON_MAX_EJEMPLARES;
		RETURN CONSULTA;
	END;
END PA_ENCPRODUCTOS;
/
CREATE OR REPLACE PACKAGE BODY PA_GERPROVEEDOR IS
	PROCEDURE AD_PROVEEDOR(XNOMBRE IN VARCHAR) IS
	BEGIN
		PC_PROVEEDOR.AD_PROVEEDOR(XNOMBRE);
	END;
	
    PROCEDURE AD_COMPRA(XVALOR IN NUMBER, XEJEMPLAR IN NUMBER, XPROVEEDOR IN NUMBER) IS
	BEGIN
		PC_PROVEEDOR.AD_COMPRA(XVALOR, XEJEMPLAR, XPROVEEDOR);
	END;
	
    PROCEDURE EL_PROVEEDOR(XID IN NUMBER) IS
	BEGIN
		PC_PROVEEDOR.EL_PROVEEDOR(XID);
	END;
	
	FUNCTION CONSULTAR_PROVEEDOR(XNOMBRE IN VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_PROVEEDOR.CONSULTAR_PROVEEDOR(XNOMBRE);
		RETURN CONSULTA;
	END;
END PA_GERPROVEEDOR;
/
CREATE OR REPLACE PACKAGE BODY PA_EMPPERSONA IS
	PROCEDURE AD_CLIENTE(XTIPODOC IN VARCHAR, XNUMDOC IN VARCHAR, XTARJETA IN NUMBER) IS
	BEGIN
		PC_PERSONA.AD_CLIENTE(XTIPODOC,XNUMDOC,XTARJETA);
	END;
	
    PROCEDURE AD_TARJETADESCUENTO(XDESCUENTO IN NUMBER) IS
	BEGIN
		PC_PERSONA.AD_TARJETADESCUENTO(XDESCUENTO);
	END;
	
    FUNCTION CONSULTAR_DESCUENTO(XTIPODOC IN VARCHAR, XNUMDOC IN VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_PERSONA.CONSULTAR_DESCUENTO(XTIPODOC,XNUMDOC);
		RETURN CONSULTA;
	END;
    
    FUNCTION CONSULTAR_DESCUENTO_DISPO RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_PERSONA.CONSULTAR_DESCUENTO_DISPO;
		RETURN CONSULTA;
	END;
END PA_EMPPERSONA;
/
CREATE OR REPLACE PACKAGE BODY PA_GERSEDE IS
	PROCEDURE AD_SEDE(XDIRECCION IN VARCHAR) IS
	BEGIN
		PC_SEDE.AD_SEDE(XDIRECCION);
	END AD_SEDE;
	
    PROCEDURE AD_CONTROL(XSEDE IN NUMBER, XVENTA IN NUMBER) IS
	BEGIN
		PC_SEDE.AD_CONTROL(XSEDE,XVENTA);
	END AD_CONTROL;
	
    PROCEDURE AD_CONTRATO(XTIPO IN VARCHAR, XEMPLEADO IN NUMBER) IS
	BEGIN
		PC_SEDE.AD_CONTRATO(XTIPO,XEMPLEADO);
	END AD_CONTRATO;
	
	PROCEDURE EL_SEDE(XDIRECCION IN VARCHAR) IS
	BEGIN
		PC_SEDE.EL_SEDE(XDIRECCION);
	END EL_SEDE;
	
    FUNCTION CONSULTAR_SEDES RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_SEDE.CONSULTAR_SEDES;
		RETURN CONSULTA;
	END;
    
    FUNCTION CONSULTAR_SEDES_GERENTES(XID IN VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_SEDE.CONSULTAR_SEDES_GERENTES(XID);
		RETURN CONSULTA;
	END;
END PA_GERSEDE;
/
CREATE OR REPLACE PACKAGE BODY PA_EMPVENTA IS
	PROCEDURE AD_VENTA(XEMPLEADO IN NUMBER, XFORMAPAGO IN VARCHAR, XVALORPAGAR IN NUMBER, XTIPODOC IN VARCHAR, XNUMDOC IN VARCHAR) IS
    BEGIN
		PC_VENTA.AD_VENTA(XEMPLEADO,XFORMAPAGO,XVALORPAGAR,XTIPODOC,XNUMDOC);
	END AD_VENTA;
    
    FUNCTION CONSULTAR_CLIENTES_DIARIOS RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_VENTA.CONSULTAR_CLIENTES_DIARIOS;
		RETURN CONSULTA;
	END;
	
	FUNCTION CONSULTAR_VENTAS RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_VENTA.CONSULTAR_VENTAS;
		RETURN CONSULTA;
	END;
END PA_EMPVENTA;
/
CREATE OR REPLACE PACKAGE BODY PA_DIREMPLEADO IS
	PROCEDURE AD_EMPLEADO(XCARGO IN VARCHAR, XSALARIO IN NUMBER, XTIPOCONTRATO IN VARCHAR, XSEDE IN NUMBER, XTIPODOC IN VARCHAR, XNUMDOC IN VARCHAR) IS
	BEGIN
		PC_EMPLEADO.AD_EMPLEADO(XCARGO,XSALARIO,XTIPOCONTRATO,XSEDE,XTIPODOC,XNUMDOC);
	END AD_EMPLEADO;
	
    PROCEDURE AD_GERENTE(XIDEMPLE IN NUMBER, XSEDE IN NUMBER ,XNOMBRE IN VARCHAR,XINFORMACION IN XMLTYPE) IS
    BEGIN
		PC_EMPLEADO.AD_GERENTE(XIDEMPLE,XSEDE,XNOMBRE,XINFORMACION);
	END AD_GERENTE;
	
	PROCEDURE EL_EMPLEADO(XID IN NUMBER) IS
	BEGIN
		PC_EMPLEADO.EL_EMPLEADO(XID);
	END EL_EMPLEADO;
	
    PROCEDURE EL_GERENTE(XIDEMPLE IN NUMBER) IS
	BEGIN
		PC_EMPLEADO.EL_GERENTE(XIDEMPLE);
	END EL_GERENTE;
	
    FUNCTION CONSULTAR_GERENTE(XNOMBRE IN VARCHAR) RETURN SYS_REFCURSOR IS CONSULTA SYS_REFCURSOR;
	BEGIN
		CONSULTA := PC_EMPLEADO.CONSULTAR_GERENTE(XNOMBRE);
		RETURN CONSULTA;
	END;
END PA_DIREMPLEADO;