EXECUTE PA_ENCPRODUCTOS.AD_ANIME('BATMAN','Gore');

EXECUTE PA_ENCPRODUCTOS.AD_FIGURA('KANEKAS','Real');

EXECUTE PA_ENCPRODUCTOS.AD_AUTOR('Stan Lee');

EXECUTE PA_ENCPRODUCTOS.EL_FIGURA(1);

SELECT PA_ENCPRODUCTOS.CON_ANIME_GENERO('Gore') FROM DUAL;

EXECUTE PA_GERPROVEEDOR.AD_PROVEEDOR('Pepe Grillo');

EXECUTE PA_EMPPERSONA.AD_CLIENTE('CC','123456789',50);

SELECT PA_EMPPERSONA.CONSULTAR_DESCUENTO('CC','123456789') FROM DUAL;

EXECUTE PA_GERSEDE.AD_SEDE('Carrera 95 N 124-78');

SELECT PA_GERSEDE.CONSULTAR_SEDES FROM DUAL;

EXECUTE PA_EMPVENTA.AD_VENTA(1,'Efectivo',541564,'CC','123456789');

SELECT PA_EMPVENTA.CONSULTAR_VENTAS FROM DUAL;

